### ISSUE TITLE
Please, help me with maps.geshergalicia.org

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-rs#1]
Forgive me, [lovisoa](https://github.com/lovasoa): I know you have a lot of things to do but I would like to try [your prototype](https://github.com/lovasoa/dezoomify-rs) for **very large images** I must download. Nevertheless, I don't know anything about [rust](https://www.rust-lang.org/) 😥.
_How_ can I do, please?
Example: https://maps.geshergalicia.org/cadastral/baranow-1850/. I've tried Generic Dezoomer (url: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://maps.geshergalicia.org/cadastral/baranow-1850/7/{{Y}}/{{X}}.jpg) but it's _too large_ (32000 x 24064 pixels) and, even by choosing a smaller scale (but I'm _not_ interested in), **the tiles loaded are mismatched** 😰. I'm really confused ...
Kind regards.

**Comment by rigel71** [comment]
me too the same problem 
http://www.asmilano.it/Divenire/document.htm?idDoc=10637440&idUa=10637439&first=0&last=0
help! :-(

**Comment by lovasoa** [comment]
Hello all!

I released the first functional versions of dezoomify-rs today.
The usage instructions are in the [README](https://github.com/lovasoa/dezoomify-rs#dezoomify-rs).
I now provide pre-compiled binaries for windows, macos, and linux, so you don't have to know rust to use it.

**Comment by rigel71** [comment]
Hi! Lovasoa
I downloaded dezoomify-rs and unzipped. When I open the exe file a window opens for a second time then disappears. So I can't proceed. how do i go to open it?
I created the yaml file, but I can't continue

**Comment by lovasoa** [comment]
You should not open the exe file by double clicking on it. Follow the instructions from the README: https://github.com/lovasoa/dezoomify-rs#launch-dezoomify-rs

**Comment by rigel71** [comment]
thanks, I am very little in computer science :-P

**Comment by rigel71** [comment]
I understood the procedure I tried with the file example.yaml and it works. Now how do I get url_template?
for example I have to dezoomify the image in this url http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536765.tif&JTL=7,2423. 
how do I modify it to insert in the yaml file?
**http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536765.tif** 
then I have to add 
**_files/13/{{x/tile_size}}_{{y/tile_size}}.jpg** ?
and the number 13 remain or change?
Then I have to change the variables x and y? where I find this values?
Sorry, but I'm really inexperienced, but I want to learn

**Comment by lovasoa** [comment]
@rigel71 I created [a detailed step-by-step tutorial](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example) taking your use-case as an example. Let me know if you find it useful :)

**Comment by lovasoa** [comment]
![lowqual](https://user-images.githubusercontent.com/552629/61598217-6c714300-ac1a-11e9-8482-e43f29a5bbbe.jpg)

**Comment by lovasoa** [comment]
Do not hesitate to open new issues if you encounter new problems.
