### ISSUE TITLE
Difficulties to create YAML file with archiviodistatovenezia.it

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-rs#10]
I'm trying to download the IIIF [cadastral maps of Noale](http://archiviodistatovenezia.it/divenire/ua.htm?idUa=17289), the four largest in the series (see above the window «**pagina/carta**»: _0062191_, _0062201_, _0062211_, _0062221_). I'm mortified by my nectitude, but I cannot understand how to create the YAML file (/info.json).

**Comment by lovasoa** [comment]
You don't need to create a `tiles.yaml` file for this one, or even to use a dezoomifier for that matter. You can simply request the server for the full image: 

`http://www.archiviodistatovenezia.it/fast/iipsrv2.fcgi?FIF=/mnt/links/siasve/./01/10/110368.tif&CVT=jpeg`

When browsing the image with the network monitor opened, you notice that it make requests to : 

```
http://www.archiviodistatovenezia.it/fast/iipsrv2.fcgi?FIF=/mnt/links/siasve/./01/10/110368.tif&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number
```

The `iipsrv2.fcgi` in the URL is a sign that the server uses the IIPImage Server. This is a free software, and the documentation for the protocol they use is on their website: https://iipimage.sourceforge.io/documentation/protocol/

 Reading the documentation, you notice that you can simply use the CVT parameter to export the full image.

![native-lowqual](https://user-images.githubusercontent.com/552629/66990743-0e43e700-f0c7-11e9-80b6-670f7dd14c45.jpg)

**Comment by Arekkusu1998** [comment]
Sorry @lovasoa: I tried Your method these days but **it doesn't work**. 
The screen that comes out is the following.
![Immagine1](https://user-images.githubusercontent.com/48092608/67508147-bb52cc80-f690-11e9-8025-75022e98f800.png)
There's worse news: after having tried to dezoomify maps in vain, **all the documents that can be viewed on [the website](http://archiviodistatovenezia.it/divenire/collezioni.htm) are no longer reachable**: the window goes black, no document is loaded and a warning appears above. 
Here is the screen.
![Immagine2](https://user-images.githubusercontent.com/48092608/67508229-e0473f80-f690-11e9-9236-ece3f815f435.png)
Is it a kind of damn security device (which I've never been until a few weeks ago), a system's glitch or is it something else?

**Comment by lovasoa** [comment]
Their site indeed seems to be broken now.

**Comment by Arekkusu1998** [comment]
Nope, **@lovasoa**, I think You're almost wrong this time😢.
This day, the website always worked and I was able to dezoomify medium-large **1:2000** maps, simply using Dezoomify (just copy & paste the image link, clicking on it). But, in the exact instant in which I arrived at the giant **1:1000** maps and adopted Your method, _everything stopped and now the website of the Venice State Archives is again in the complete crash_. I think direct downloads inhibits the viewing of all the material, for everyone; maybe a new security system🙄...
Please, I ask You again -when the website return operative- **how to construct the info.json string** for the maps listed above:
- 0062191
- 0062201
- 0062211
- 0062221

Each map has a serial number: see «**pagina/carta**» at the top right of the viewing window.

**Comment by Arekkusu1998** [comment]
Forgive my insistence, @lovasoa; I badly explained myself.
I've used [Dezoomify](https://ophir.alwaysdata.net/dezoomify/dezoomify.html) successfully yesterday the whole day, getting 20 medium-large maps; the website had **never** any interruptions😊. Also, I'm dezoomifying maps (slowly) with Dezoomify **right now** ... _and the website isn't disturbed in any way_! I conclude that **NEITHER _Dezoomify_ NOR _Dezoomify-RS_ lead to the crash of the Venice Archives portal**, but the DIRECT download (by modifying the url string in CVT=jpeg) does😵.
For this I ask You, please, _how to build the info.json file for the aforementioned maps_ 🙏, so I can obtain what I want and I don't break the experience of anyone.

**Comment by lovasoa** [comment]
Ok, I'm sorry I misunderstood. If you read the iipimage protocol documentation, you see that it can also generate zoomify- and deepzoom- compatible meta files. You just have to change the url

For instance, if you notice in your network monitor a request like:
```
http://www.archiviodistatovenezia.it/fast/iipsrv2.fcgi?FIF=/mnt/links/siasve/./01/10/110368.tif&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number
```

You can replace `FIF` with `DeepZoom` and add `.dzi` after the name of the image:
```
http://www.archiviodistatovenezia.it/fast/iipsrv2.fcgi?DeepZoom=/mnt/links/siasve/./01/10/110368.tif.dzi
```

This results in a valid deepzoom URL that you can give to `dezoomify-rs`.
