### ISSUE TITLE
Tile indices with leading zero in the custom YAML dezoomer

### ISSUE THREAD

**Issue by tojoshuazhang** [lovasoa/dezoomify-rs#100]
I was trying to construct a YAML file for this image:
https://highres.factum-arte.org/Caravaggio/Calling/

However don't know how to resolve the issue with leading zero. Could you help? Thank you!

1st tile:
https://highres.factum-arte.org/Caravaggio/Calling/The_Calling_Colour_254ppi_Flat.tiles/l6/01/l6_01_01.jpg
last tile: 
https://highres.factum-arte.org/Caravaggio/Calling/The_Calling_Colour_254ppi_Flat.tiles/l6/64/l6_64_68.jpg

**Comment by lovasoa** [comment]
Unfortunately, this is not yet supported in the generic yaml dezoomer. If you are interested and now rust, you can add it [here](https://github.com/lovasoa/dezoomify-rs/blob/master/src/custom_yaml/tile_set.rs).

The generic dezoomer does support leading zeroes, but it doesn't support tile indices that start at 1 such as these.

**Comment by lovasoa** [comment]
I'll leave this issue open to track support for the feature you were mentioning, but in your case, you do not need it. Your image is in the KRPano format, which is supported directly by dezoomify-rs. You do not need to create a yaml file at all: 

```
dezoomify-rs "https://highres.factum-arte.org/Caravaggio/Calling/pano.xml"
```

**Comment by tojoshuazhang** [comment]
Thank you lovasoa!

**Comment by lovasoa** [comment]
![lowres](https://user-images.githubusercontent.com/552629/105717961-08bb8a80-5f21-11eb-9395-4390f3be6d1f.jpg)

**Comment by MrChrisWin** [comment]
Do you have a way to separate out the multiple layers?
For example: [http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/shared/viewer.html](http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/shared/viewer.html) has color, 3d and color + 3d. 
The layer.xml stores the various size. [http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/panos/layers.xml](http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/panos/layers.xml)
Thanks.

**Comment by tojoshuazhang** [comment]
@lovasoa 
I wonder if you noticed the above comment MrChrisWin left? on this site, there are two types of constructions so the method to add pano.xml at the end of URL does not work for the other type. such as:
http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/shared/viewer.html

is there any easy solution? Thank you!

**Comment by lovasoa** [comment]
I am not *adding pano.xml at the end of the URL*, I am using my browser's network monitor to find the URL of the meta-information file, which may or may not end in *pano.xml*.

**Comment by lovasoa** [comment]
@MrChrisWin , can you open a separate issue describing the problem with the unsupported "layers.xml" ? I don't think it's related to this issue.

**Comment by lovasoa** [comment]
I did it, see #102
