### ISSUE TITLE
Impossible to dezoomify images from http://archiviodistatovenezia.it/

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-rs#101]
Good morning, **@lovasoa**: I hope You're well.
In the last few weeks it's no longer possible to use dezoomify-rs on any document or image from the Digital Collection of the State Archives of Venice. Using [this image](http://archiviodistatovenezia.it/divenire/ua.htm?idUa=18027) and using the string for the IIIF protocol (http://www.archiviodistatovenezia.it/fast/iipsrv.fcgi?IIIF=/mnt/links/siasve/./01/13/113646.tif/info.json) as an example, the result is as follows.
![Proof](https://user-images.githubusercontent.com/48092608/105697414-d0a64e80-5f04-11eb-945f-96aa4a221caf.png)

**Comment by lovasoa** [comment]
The URL you give seems to be incorrect. Opening it in a browser gives the following: 

![image](https://user-images.githubusercontent.com/552629/105719223-55ec2c00-5f22-11eb-9539-b697446ba3f9.png)

**Comment by lovasoa** [comment]
This is an IIPImage server. Using the [IIPImage dezoomer](https://github.com/lovasoa/dezoomify-rs#iipimage)  seems to work: 

```
dezoomify-rs "http://www.archiviodistatovenezia.it/fast/iipsrv.fcgi?FIF=/mnt/links/siasve/./01/13/113646.tif"
```

**Comment by Arekkusu1998** [comment]
Thanks for Your kindness and zeal to answer me😌.
I assure You that the first URL **wasn't** incorrect: until two weeks ago, this was the format that dezoomify-rs received; then, overnight, it reported the «_404 Bad Request_» Error and many images on DIVENIRE Portal became difficult to consult. IMO, something is changed . 

One last question: how should the parameters `--parallelism 1 --retries 10 --retry-delay 5s` can be entered?

**Comment by lovasoa** [comment]
To be able to provide parameters, you shouldn't start dezoomify-rs by double-clicking on it, but instead start it from the command line. Here is an example: https://www.youtube.com/watch?v=tld7w32KqqI

**Comment by Arekkusu1998** [comment]
Thank You very much, **@lovasoa**🤗🤗!!
