### ISSUE TITLE
Support KRPano images with scenes

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#102]
KRPano files with "scene" elements are currently not supported.

_Originally posted by @MrChrisWin in https://github.com/lovasoa/dezoomify-rs/issues/100#issuecomment-767048175_

> Do you have a way to separate out the multiple layers?
> For example: [http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/shared/viewer.html](http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/shared/viewer.html) has color, 3d and color + 3d. 
> The layer.xml stores the various size. [http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/panos/layers.xml](http://www.highres.factum-arte.org/Velazquez_Saint_Thomas/panos/layers.xml)
Thanks.

**Comment by lovasoa** [comment]
@MrChrisWin here is a pre release that adds support for krpano scenes, such as the ones in your example: 
https://github.com/lovasoa/dezoomify-rs/releases/tag/build-5978692c7aba91a745957b803283644d0a2cfd41

Are you interested in testing it on more similar krpano images ? If it works correctly, I'll release this version for everyone to use. 

NB: only extracting the images themselves is supported, metadata such as the scene names are not included, which may make it a little bit harder to identify images.

**Comment by tojoshuazhang** [comment]
@lovasoa I tested on other images on this site and it works just great! Thank you!

**Comment by MrChrisWin** [comment]
> @MrChrisWin here is a pre release that adds support for krpano scenes, such as the ones in your example:
> https://github.com/lovasoa/dezoomify-rs/releases/tag/build-5978692c7aba91a745957b803283644d0a2cfd41
> 
> Are you interested in testing it on more similar krpano images ? If it works correctly, I'll release this version for everyone to use.
> 
> NB: only extracting the images themselves is supported, metadata such as the scene names are not included, which may make it a little bit harder to identify images.

It works wonderfully. Thank you.

**Comment by lovasoa** [comment]
Ok, thanks for testing it. I'll make a new release !

**Comment by lovasoa** [comment]
Here is a new development build that adds support for detecting image and scene names, which should help with choosing the image you need: https://github.com/lovasoa/dezoomify-rs/releases/tag/build-e643c39905919ca95880373e731c6604d29e1653
