### ISSUE TITLE
Download from Nypl, Arts & Culture (with serial images)

### ISSUE THREAD

**Issue by Iskander1220** [lovasoa/dezoomify-rs#104]
Hi, and sorry for my English. How I can download files with program from links? —

https://digitalcollections.nypl.org/items/a419ffb7-fbd9-f904-e040-e00a18063f5c
Serial images:
https://artsandculture.google.com/exhibit/botticelli-featuring-dante/VgKCKADf-6d1JA?hl=en

**Comment by Iskander1220** [comment]
Even if you can, the question is not on the topic: the assembly of tiles is in memory, or on the disk?

**Comment by lovasoa** [comment]
> https://digitalcollections.nypl.org/items/a419ffb7-fbd9-f904-e040-e00a18063f5c

The images on that site are not tiled, and you can download them directly from the site itself. You don't need an external program.

![image](https://user-images.githubusercontent.com/552629/106438097-50d53280-6476-11eb-8a87-aa5cd21a811b.png)


>  https://artsandculture.google.com/exhibit/botticelli-featuring-dante/VgKCKADf-6d1JA?hl=en

I don't know what you mean by *serial images*, but google arts and culture is supported. See https://dezoomify-rs.ophir.dev/

> the assembly of tiles is in memory, or on the disk?

Individual tiles are not saved to disk before being assembled. But this doesn't prevent downloading images that are larger than the available RAM thanks to the *streaming* nature of some image savers implemented in dezoomify-rs, such as *PNG* and *IIIF*. See the  *Supported output image formats* on the [dezoomify-rs website](https://dezoomify-rs.ophir.dev/).

**Comment by Iskander1220** [comment]
> I don't know what you mean by _serial images_

It was meant that the program downloads such links:

https://artsandculture.google.com/asset/melencolia-i/GgHjdLYYfayf3g?hl=ru

But when the link believes — 

https://artsandculture.google.com/exhibit/botticelli-featuring-dante/VgKCKADf-6d1JA?hl=en

Where the briefly collected image selection is collected (which can be spilled to the right and left), then how in this case download the links of individual images in the highest resolution?

**Comment by Iskander1220** [comment]
> The images on that site are not tiled, and you can download them directly from the site itself.

About NYPL - I just wanted to find out why such a link the program downloads in secondary quality (inaccessible on the site) -

https://digitalcollections.nypl.org/items/ad4ea2ed-52c0-cfb1-e040-e00a1806797e

And this in the same average quality does not download that instead of 760px did not have to swing a huge TIFF -

https://digitalcollections.nypl.org/items/a419ffb7-fbd9-f904-e040-e00a18063f5c

**Comment by lovasoa** [comment]
The nypl dezoomer was contributed externally by @winkidney (see https://github.com/lovasoa/dezoomify-rs/pull/82). It is useful only when NYPL does not offer high-quality downloads. In your case, the site offers a high-quality TIFF image (independently of the zoomable image). You should download the high-res tiff (and eventually convert it to another format if file size is a concern). 
dezoomify-rs works only on the zoomable image, it looks at the highest quality image available in the zoomable image viewer.

**Comment by Iskander1220** [comment]
Thanks for answers! And on downloading images on the [link](https://artsandculture.google.com/exhibit/botticelli-featuring-dante/VgKCKADf-6d1JA?hl=en) there is no solution yet?

**Comment by Iskander1220** [comment]
Found out that [for the first image](http://lh4.ggpht.com/Ou9rZdNPfEBpgj2uaU4piBlmX2FxNrMsF0G0ETC4SoSoAg2pV8ADDrfyuM3n=s9999) by reference [from here](https://artsandculture.google.com/exhibit/botticelli-featuring-dante/VgKCKADf-6d1JA?hl=en) — there is an XML-file:
[http://lh4.ggpht.com/Ou9rZdNPfEBpgj2uaU4piBlmX2FxNrMsF0G0ETC4SoSoAg2pV8ADDrfyuM3n=g](http://lh4.ggpht.com/Ou9rZdNPfEBpgj2uaU4piBlmX2FxNrMsF0G0ETC4SoSoAg2pV8ADDrfyuM3n=g)
Is it not supported by the program?

**Comment by lovasoa** [comment]
The URL you should pass dezoomify is the one of the artwork itself. You can click on the name of an artwork to get to its dedicated page.

![image](https://user-images.githubusercontent.com/552629/106515530-1f8c4f00-64d6-11eb-95c7-71eec125e773.png)

**Comment by Iskander1220** [comment]
Thank you very match!
