### ISSUE TITLE
The Met Museum

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#108]
Hello again.

Any chance with The Met Museum?

It has an impressive collection of paintings. As a button shows:
https://www.metmuseum.org/art/collection/search/437881

It is one of the most famous works of him.

They have a lot in Google Arts & Culture; but I think the quality of the images is higher on your web page

![image](https://user-images.githubusercontent.com/66141658/106798394-2d6cdc00-665e-11eb-98a1-31fc060a0cdf.png)

![image](https://user-images.githubusercontent.com/66141658/106798447-42e20600-665e-11eb-94f4-345540445b3b.png)

**Comment by lovasoa** [comment]
Hello !
  This is not a tiled zoomable image, you don't need any tool to download it, you can just right-click on it.

https://images.metmuseum.org/CRDImages/ep/original/DP353257.jpg

![](https://images.metmuseum.org/CRDImages/ep/original/DP353257.jpg)
