### ISSUE TITLE
Issue with IIPImage

### ISSUE THREAD

**Issue by tojoshuazhang** [lovasoa/dezoomify-rs#109]
this is the view page:
https://publications.artic.edu/renoir/reader/paintingsanddrawings/section/135639/135639_anchor

this is is one of the tile files:
https://publications-images.artic.edu/fcgi-bin/iipsrv.fcgi?fif=osci/Renoir_11/Color_Corrected/G39094sm2.ptif&jtl=4,11

so I typed in this:
dezoomify-rs --header "Referer: https://publications.artic.edu/" "https://publications-images.artic.edu/fcgi-bin/iipsrv.fcgi?fif=osci/Renoir_11/Color_Corrected/G39094sm2.ptif"

but got error message saying "tried all of the dezoomers, none succeeded". 

Did I do something wrong? or this site needs a different approach?

**Comment by lovasoa** [comment]
I fixed the bug and uploaded the image to wikimedia : https://commons.wikimedia.org/wiki/File:Two_Sisters_(On_the_Terrace).jpg

**Comment by lovasoa** [comment]
Fixed by https://github.com/lovasoa/dezoomify-rs/commit/93bb6f531b9dae01921be1e496099599fe97341f

**Comment by tojoshuazhang** [comment]
@lovasoa Thank you!
