### ISSUE TITLE
Downloading images from Laurenziana

### ISSUE THREAD

**Issue by Iskander1220** [lovasoa/dezoomify-rs#110]
Hi, and sorry from my English.
How to correctly download from here? —

http://mss.bmlonline.it/s.aspx?Id=AWOMqsS4I1A4r7GxMX6Q&c=XVIII.%20L%27Inferno%20di%20Dante%20Alighieri#/oro/30

http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto06_PrimaParte\.\P003245_90inf.47\pyr\Plut._90__inf._47_0030.tif/TileGroup0/{{X}}-{{Y}}-0.jpg

**Comment by lovasoa** [comment]
This website uses a format that is supported by dezoomify. You can use [dezoomify-extension](https://lovasoa.github.io/dezoomify-extension/)  to find the URL to give to dezoomify. In this case : 

```
http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto06_PrimaParte\.\P003245_90inf.47\pyr\Plut._90__inf._47_0030.tif/ImageProperties.xml
```
