### ISSUE TITLE
Support for easyzoom.com?

### ISSUE THREAD

**Issue by tojoshuazhang** [lovasoa/dezoomify-rs#111]
I wonder if dezoomify-rs supports easyzoom.com? 

one example:
https://easyzoom.com/image/241504?fbclid=IwAR07XwRCdjECCha1DGz8xGEsUcLKTVUduHcjrPpUueVOegjixi7dby4UAD0

**Comment by lovasoa** [comment]
Hello !
  Yes, you can download images from easyzoom. See: https://github.com/lovasoa/dezoomify/issues/439

**Comment by lovasoa** [comment]
![verylowqual](https://user-images.githubusercontent.com/552629/107865884-6af61400-6e6b-11eb-8c11-167f894b5d3c.jpg)

(reduced quality to fit on github)

**Comment by tojoshuazhang** [comment]
@lovasoa Thank you!
