### ISSUE TITLE
Downloading from uurl.kbr.be

### ISSUE THREAD

**Issue by Iskander1220** [lovasoa/dezoomify-rs#112]
Hi, and sorry from my English. How to correctly download from Belgium library? — https://uurl.kbr.be/1713340

**Comment by lovasoa** [comment]
Hello !
  See https://github.com/lovasoa/dezoomify/issues/120

**Comment by Iskander1220** [comment]
Hello! For what reason is the [bottom and right, there are strips increasing](https://i.imgur.com/cA72bVy.jpg) the image and which is not [in the original](https://uurl.kbr.be/1841172)? Is it possible to avoid this?

**Comment by lovasoa** [comment]
Hello, 
  Currently  you have to crop the image manually. If https://github.com/lovasoa/dezoomify-rs/issues/115 gets implemented, you will be able to to it with the custom yaml dezoomer in dezoomify-rs.

**Comment by Iskander1220** [comment]
Hello, dear **lovasoa**. Could you tell me how your program seeks that the tiles become active? That is, if you try to open [this link](https://viewerd.kbr.be/display/A/1/5/8/9/6/1/8/zoomtiles/BE-KBR00_A-1589618_0000-00-00_0003/2-0-0.jpg) in the browser, then there will be an error, but your program somehow does so that the link becomes active. Due to what happens?

**Comment by lovasoa** [comment]
If you want to understand that, you need to read about the [HTTP protocol](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol) and [HTTP headers](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields). In the precise exemple you give, I think the server is checking the [Referer header](https://en.wikipedia.org/wiki/HTTP_referer).

Links are not "active" or "inactive", it's just that the same server can answer differently to requests for the same path that  have different headers.

**Comment by Iskander1220** [comment]
Thank you. What about the active/inactive links - in one manual, wrote that this site when accessing the user loads tiles of images to a specific folder and therefore if you do not contact the page, then the tiles will actually not be accessible.
