### ISSUE TITLE
Difference in files

### ISSUE THREAD

**Issue by Iskander1220** [lovasoa/dezoomify-rs#113]
Hi, and sorry from my English. What is the difference in files: on the site - colors is brighter, and if you download the image with program (tif, etc.) - on the contrary?

https://digital.bodleian.ox.ac.uk/objects/bb971cd2-a682-45e5-866f-31ce76482afe/surfaces/758a0fdd-6495-4851-84de-fa9f74eb7a7a/
https://iiif.bodleian.ox.ac.uk/iiif/image/758a0fdd-6495-4851-84de-fa9f74eb7a7a/info.json
https://digital.bodleian.ox.ac.uk/derivatives/758a0fdd-6495-4851-84de-fa9f74eb7a7a/full.jpg

**Comment by lovasoa** [comment]
Hi,
  Yes, indeed, they look very slightly different. You would need to ask the museum if you want to know why.
