### ISSUE TITLE
Ask for new support from the website of the Forbidden City of China

### ISSUE THREAD

**Issue by Shiraishi1** [lovasoa/dezoomify-rs#116]
Can the pictures on the website of the National Palace Museum be downloaded? look forward to. thank you
If it can't be opened, it may be that the IP address is limited to China. There are great pictures on the website, but there are no effective tools to download
https://minghuaji.dpm.org.cn/paint/list?keyword=
https://minghuaji.dpm.org.cn/paint/appreciate?id=0b74c41220e341fe970033688ea26c23

**Comment by lovasoa** [comment]
Hello,
  You can use the [generic dezoomer](https://github.com/lovasoa/dezoomify-rs#Generic) : 
  `dezoomify-rs "https://minghuaji-1259446244.cos.ap-beijing.myqcloud.com/bundle/20615e20e5e44c4abbd40f0194f40a47/12/{{X}}_{{Y}}.png" -H "Referer: https://minghuaji.dpm.org.cn/paint/appreciate?id=0b74c41220e341fe970033688ea26c23"`

![dezoomified](https://user-images.githubusercontent.com/552629/108179561-099da180-7106-11eb-8d57-6dab5b7405c0.png)

**Comment by Shiraishi1** [comment]
Hello, thank you very much for your technical support, but when I tried to download, the resource was rejected. But browsing on the website is normal. Hope to get your help

You are denied by bucket referer rule

<Error>
<Code>AccessDenied</Code>
<Message>You are denied by bucket referer rule</Message>
<Resource>minghuaji-1259446244.cos.ap-beijing.myqcloud.com/bundle/20615e20e5e44c4abbd40f0194f40a47/12/{{X}}_{{Y}}.png</Resource>
<RequestId>NjAyY2RlM2VfZTNjNzJhMDlfMWMxMTNfNTdlZDI1NA==</RequestId>
<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OWI2NmQ0YjJkZWE3NjcxYTUzN2Q1NDQzNjY0ZmI3ZTMyM2ZmNDIwNzRiNjkxOTlkMGNjZDA3N2ZlYzU4MTNiMTM=</TraceId>
</Error>

Enter an URL or a path to a tiles.yaml file:
https://minghuaji-1259446244.cos.ap-beijing.myqcloud.com/bundle/20615e20e5e44c4abbd40f0194f40a47/12/{{X}}_{{Y}}.png
[ETA:0s] ########################################    0/0    Computing the URLs of the image tiles...
[2021-02-17T09:10:35Z WARN  dezoomify_rs] network error: HTTP status client error (403 Forbidden) for url (https://minghuaji-1259446244.cos.ap-beijing.myqcloud.com/bundle/20615e20e5e44c4abbd40f0194f40a47/12/0_0.png). Retrying tile download [ETA:0s] ########################################    1/1    Requesting the ti
