### ISSUE TITLE
Signature check for loaded tiles

### ISSUE THREAD

**Issue by Iskander1220** [lovasoa/dezoomify-rs#117]
Hi, and sorry from my English. Is it possible to check the downloadable tiles by signature? Because (for example), for the Harvard Library, tiles are often not fitted, leaving black squares. This expectation does not help:

`dezoomify-rs --parallelism 1 --timeout 60s --retry-delay 25s`

**Comment by lovasoa** [comment]
I'm not not sure what you mean by signature... Can you give an example to illustrate your problem?

**Comment by Iskander1220** [comment]
I mean the ability to check the downloaded files by their signature - that is, the characteristic initial text within them. For example, JPG files usually have the text "JFIF", by which you can recognize the downloaded file. That is, the program can download the first tile, find out its format, and if it is JPG - download and check the rest for the presence of JFIF in its initial bytes. Thus, it seems to me that there will be no missed files and correspondingly black squares.

**Comment by Iskander1220** [comment]
Although there may be a setting that allows you to download the tile while it does not really jump?

**Comment by lovasoa** [comment]
dezoomify-rs does already detect invalid tiles. It displays a warning in the console when it encounters them. What are you suggesting it should do instead ?

Could you provide an example to illustrate your problem ? An URL, the expected result, and what you get instead.

**Comment by Iskander1220** [comment]
I wanted to avoid that when downloading images from here - [https://iiif.lib.harvard.edu/manifests/view/drs:5141187](url) - the black empty tiles were downloaded, which integrate into images [screenshot](https://fastpic.ru/view/114/2021/0218/_39060bbdd30e1f7d3cdf68f708ca034c.jpg.html)

Is it possible to try to download tiles until it contains a normal image?

**Comment by lovasoa** [comment]
There is no black empty tile, there is *no* tile in the image at the position where you see a black square.

> Is it possible to try to download tiles until it contains a normal image?

Yes, you can specify `--retries 10` and it will retry each tile download 10 times if they fail. Returning something other than a valid image file counts as failure.

![dezoomified](https://user-images.githubusercontent.com/552629/108384084-b103fc80-720a-11eb-9d11-1e4501f0cb04.jpg)
