### ISSUE TITLE
Redownload missed Tiles

### ISSUE THREAD

**Issue by renoir789** [lovasoa/dezoomify-rs#119]
Just pulled down this http://gds.astro.rub.de/ however upon completion there were 20 tiles missed out of 704,000.

Is there anyway to re-run and just redownload the missed tiles?

**Comment by lovasoa** [comment]
No, there is no way to do that currently. You can set the retry policy beforehand, but once your image has been created, all the intermediary tiles are deleted

**Comment by Iskander1220** [comment]
Hi and sorry for my English! I sometimes break the Internet connection and the resulting tiles appear as a result. Is there a team to handle such cases?

**Comment by lovasoa** [comment]
There is currently no option to save the tiles to disk, but here are the options you can play with:

```
    -n, --parallelism <parallelism>
            Degree of parallelism to use. At most this number of tiles will be downloaded at the same time [default: 16]

    -r, --retries <retries>
            Number of new attempts to make when a tile load fails before giving up. Setting this to 0 is useful to speed
            up the generic dezoomer, which relies on failed tile loads to detect the dimensions of the image. On the
            contrary, if a server is not reliable, set this value to a higher number [default: 1]
        --retry-delay <retry-delay>
            Amount of time to wait before retrying a request that failed. Applies only to the first retry. Subsequent
            retries follow an exponential backoff strategy: each one is twice as long as the previous one [default: 2s]
        --timeout <timeout>
            Maximum time between the beginning of a request and the end of a response before the request should be
            interrupted and considered failed [default: 30s]
```

You could set parallelism to 1, retries to 10, retry-delay to 10s, and timeout to 60s.

**Comment by lovasoa** [comment]
This will make downloads much slower, but also much more reliable under a flaky internet connection.

**Comment by lovasoa** [comment]
I added a tile cache in the latest development version. 
You can re-run dezoomify-rs with the same tile cache to download only the missing images.
Can you test it and give feedback before I release it ?
