### ISSUE TITLE
add support for mootools (rgo.ru)

### ISSUE THREAD

**Issue by lustyffh** [lovasoa/dezoomify-rs#120]
https://geoportal.rgo.ru/iipview/691

maps over there seem to be driven by mootools. Neither extension nor the offline dezoomify can handle it.

**Comment by lovasoa** [comment]
Hello !
  This site already works with dezoomify-rs. You can use the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/) to find the image metadata URL: 

```
https://geoportal.rgo.ru/iipsrv?FIF=691.tif
```

However, the server checks the HTTP referer and cookies, so you will have to tweak the requests. You can use [dezoomify-rs](https://dezoomify-rs.ophir.dev/)'s header options for that:

```
dezoomify-rs  "https://geoportal.rgo.ru/iipsrv?FIF=691.tif"  -H 'Referer: https://geoportal.rgo.ru/iipview/691' -H 'Cookie: drupal=1; SSESS6c3a1f70ceb7757cb895a66048ccbd30=eLcriK0dxK2r-sxmABtZ_Fbuf-wvjWWb56hXRyT03ZE; has_js=1'
```

(copy the header values from your own browser)

See this page about protected images: https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages



![map](https://user-images.githubusercontent.com/552629/112283480-79b0c180-8c88-11eb-843f-4ba08374b454.jpg)

**Comment by lovasoa** [comment]
![map](https://user-images.githubusercontent.com/552629/112285095-38211600-8c8a-11eb-9cfa-e5fcbd8bbd1d.png)

**Comment by lustyffh** [comment]
wow, thanks a lot for prompt help!

**Comment by lovasoa** [comment]
Не за что 😉

**Comment by Arekkusu1998** [comment]
Огромное спасибо, @lovasoa 🤗!! У меня тоже была такая же проблема.

**Comment by Arekkusu1998** [comment]
**Warning**: this dezoomification method is **deprecated**. It doesn't work anymore. 
For other problems with Russian websites see Issue #222.
