### ISSUE TITLE
Suggestion about command-line option

### ISSUE THREAD

**Issue by poorfish** [lovasoa/dezoomify-rs#121]
U got a great job, dezoomfy help me a lot, thank you.

I used download images under batch mode(`xargs -d '\n' -n 1 ./dezoomify-rs < ./urls.txt`), lots and frequently, then I got files like this
```
dezoomified_0001.png
dezoomified_0002.png
dezoomified_0003.png
dezoomified_0004.png
...
dezoomified.png
```
Actually I may rename these filename as "birds-01.png" or "birds-01-metmuseum.png", one by one.

So I think may batch work can be efficiently if command-line option has a new parameter that it could customize prefix/surfix of filename.

**Comment by lovasoa** [comment]
You can already specify an output filename on the command-line. 

```
dezoomify-rs "https://input-url" "output-file.jpg"
```

So you can update your small xargs script to set the output file name you want.


For handling the batching in dezoomify-rs itself, we already have an issue to track it: https://github.com/lovasoa/dezoomify-rs/issues/17

**Comment by poorfish** [comment]
Got it, thanks
