### ISSUE TITLE
GigaThyssen (high-res painting from Thyssen-Bornemisza Museum)

### ISSUE THREAD

**Issue by Scanirus** [lovasoa/dezoomify-rs#122]
It is possible to download images in high resolution from Thyssen-Bornemisza Museum website using dezoomify?

https://www.museothyssen.org/conectathyssen/gigathyssen/metropolis

https://www.museothyssen.org/conectathyssen/gigathyssen

**Comment by lovasoa** [comment]
Hello !
  You can use the [Generic Dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) with this site : 

```
https://sc4hvcfl151058502cff46683.s3.amazonaws.com/gigapixel/4g120f739ca2a34c473ca265561ffc1639dy/4g120f739ca2a34c473ca265561ffc1639dy_5_{{X}}_{{Y}}.jpg
```


![canvas](https://user-images.githubusercontent.com/552629/113276466-240b9300-92e0-11eb-85f2-20fa0d58a76e.jpg)
(quality reduced to fit on github)

**Comment by Scanirus** [comment]
Thank you so much!!

**Comment by Scanirus** [comment]
Hello!

Please, help with this image from Musée Fabre:

http://oeuvresgigapixels.museefabre.montpellier3m.fr/steen.html

http://oeuvresgigapixels.museefabre.montpellier3m.fr/steen.tiles/l6/12/l6_12_7.jpg > I tried to replace end of line for {{X}}_{{Y}}, but it didn't work)

**Comment by lovasoa** [comment]
This is not related to GigaThyssen, I'm opening a separate issue.

**Comment by lovasoa** [comment]
Thank you for opening this : we have identified the zoomable format behind this image and are going to add support for it. We are consolidating all reports about this format to https://github.com/lovasoa/dezoomify/issues/808
