### ISSUE TITLE
Musée Fabre

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#123]
Hello!

Please, help with this image from Musée Fabre:

http://oeuvresgigapixels.museefabre.montpellier3m.fr/steen.html

http://oeuvresgigapixels.museefabre.montpellier3m.fr/steen.tiles/l6/12/l6_12_7.jpg > I tried to replace end of line for {{X}}_{{Y}}, but it didn't work)

_Originally posted by @Scanirus in https://github.com/lovasoa/dezoomify-rs/issues/122#issuecomment-813004050_

**Comment by lovasoa** [comment]
Hello !
  You should read the dezoomify FAQ, in particular this question: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#dezoomify-cannot-find-a-dezoomer-for-my-page-what-to-do-

  In this case, this is a krpano image, which is supported by dezoomify and dezoomify-rs. The image metadata URL to give dezoomify is : 

```
http://oeuvresgigapixels.museefabre.montpellier3m.fr/steen.xml
```

![dezoomified_0003](https://user-images.githubusercontent.com/552629/113505591-15231b80-9540-11eb-8eb0-cf7a9e98e4e6.jpg)
(quality reduced to fit on github)

**Comment by lovasoa** [comment]
I uploaded the full resolution image to wikimedia

https://commons.m.wikimedia.org/wiki/File:Comme_les_vieux_chantent,_les_enfants_piaillent.jpg

I encourage you to do the same with the other pictures you download

**Comment by Scanirus** [comment]
Thanks!

You are doing a very big and important thing. Of course, it's not very good that out of the many thousands of people (5,000+, and this is just the number of those using the extension in Chrome) who use Dezoomify, almost no one uploads the downloaded images to Wikimedia.

As I understand it, there are API standards that allow you to automatically place this data about a loaded object?

![Wiki](https://user-images.githubusercontent.com/81745178/113579754-66f59f80-962d-11eb-8515-4a7411856dd3.jpg)

**Comment by lovasoa** [comment]
Maybe there are, but I usually just copy and paste the information from another similar page, and edit it as needed.
