### ISSUE TITLE
zoom works on webpage but dzi file returns 404 in the network inspector

### ISSUE THREAD

**Issue by ellipsograph** [lovasoa/dezoomify-rs#124]
Sorry for the crossposting this, but I've tried this in both the web form and dezoomify-rs, and decided that this is probably the most appropriate venue.

This page includes zoomable images:
    https://www.rockislandauction.com/detail/68/610/none-none

The Dezoomify extension passes this url to the online form:
    https://cdn.rockislandauction.com/dev_cdn/68/dzi/610_files/0/0_0.jpg
but the form isn't happy with anything other than a metadata file.

Fair enough.

The network inspector shows the metadata file to be:
    https://cdn.rockislandauction.com/dev_cdn/68/dzi/610.dzi?cachebust=2019-09-19T20:29:38.000Z
but it also shows the xml file to be 404 (so I'm not sure how it manages to work).

In the network inspector sidebar, I see this:
    Referrer Policy:strict-origin-when-cross-origin

and further down:
    Origin | https://www.rockislandauction.com
    Referer | https://www.rockislandauction.com/

Using the latest version of dezoomify-rs, I tried specifying a referrer header, but that didn't work.
    ./dezoomify-rs --header "Referrer: https://www.rockislandauction.com/" "https://cdn.rockislandauction.com/dev_cdn/68/dzi/610.dzi?cachebust=2019-09-19T20:29:38.000Z"

also:
    ./dezoomify-rs --header "Referrer: https://www.rockislandauction.com/" "https://cdn.rockislandauction.com/dev_cdn/68/dzi/610.dzi"

Neither worked.

Is this a bug? Am I missing something, or doing something wrong?

**Comment by lovasoa** [comment]
This is not a tiled image, but a static jpeg on their server. You don't need dezoomify.

```
https://cdn.rockislandauction.com/dev_cdn/68/610.jpg?cachebust=2019-09-19T20:29:38.000Z
```

![](https://cdn.rockislandauction.com/dev_cdn/68/610.jpg?cachebust=2019-09-19T20:29:38.000Z)

**Comment by ellipsograph** [comment]
Thanks for taking a look. Sorry for wasting your time.

**Comment by lovasoa** [comment]
it's not wasted; next time someone wants to download an image from  
rockislandauction, they'll find this thread in their search results.
