### ISSUE TITLE
Login onto tile server

### ISSUE THREAD

**Issue by jmlatgpixel** [lovasoa/dezoomify-rs#125]
Hello,
Some websites require you to login before the connection to their zoomable images.
They will then send you a cookie that grants access to the tile server.
Is there a way to transfer that cookie to dezoomify-rs?
If yes then the user agent header used by the initial browser should also be used by dezoomify-rs.

Thanks

**Comment by lovasoa** [comment]
Hello, yes, dezoomify-rs can do that.
Have a look at the README and the documentation.

**Comment by lovasoa** [comment]
https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie

**Comment by jmlatgpixel** [comment]
Hello lovasoa,
Thanks for the links.
My cookie question was for dezoomify-rs, not the online version.
Additionally is it possible to set the header 'user agent' in dezoomify-rs?
Have a nice day!

**Comment by lovasoa** [comment]
Yes, you can set any HTTP header, including cookies and user agent using the `--header` option. Run `dezoomify-rs --help` for help.

**Comment by jmlatgpixel** [comment]
Great!
Thanks
