### ISSUE TITLE
Gigapixel art from Palais des Beaux Arts de Lille

### ISSUE THREAD

**Issue by Scanirus** [lovasoa/dezoomify-rs#126]
Hello,

Can't download gigapixel images from pba.lille.fr:

https://pba.lille.fr/Collections/Images-en-gigapixels#

https://pba.lille.fr/gigapixels/Gigapixelweb/gigapixels_bouts_paradis/gigapixels.tiles/l8/31/l8_31_32.jpg

---
I tried different download methods, but apparently I'm doing something wrong...

**Comment by lovasoa** [comment]
Hello,
  This is a krpano image : 

```
https://pba.lille.fr/gigapixels/Gigapixelweb/gigapixels_bouts_paradis/index.xml
```

You can find the image metadata URL using you browser's developer tools network panel. Read the dezoomify FAQ: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#dezoomify-cannot-find-a-dezoomer-for-my-page-what-to-do-

**Comment by lovasoa** [comment]
![c](https://user-images.githubusercontent.com/552629/114081810-50f61200-98ad-11eb-846d-3afe8766d493.jpg)

**Comment by Scanirus** [comment]
Thanks!

![KRP](https://user-images.githubusercontent.com/81745178/114082206-252b5a00-98b6-11eb-9722-5ae4fc830b91.jpg)
