### ISSUE TITLE
Arnolfini Portrait from closertovaneyck

### ISSUE THREAD

**Issue by Scanirus** [lovasoa/dezoomify-rs#127]
Hello!

If not difficult, please help with this image too:

http://closertovaneyck.kikirpa.be/verona/#viewer/rep1=2&id1=6cb22ad3c438b92c720d16b4d91d98ca

Sea Dragon > http://test.com/y/xy_files/1/2_3.jpg > http://test.com/y/xy.dzi.

http://data.closertovaneyck.be/verona/tiles/26-VIS-UH/16/27_49.jpg
http://data.closertovaneyck.be/verona/tiles/{{Y}}-VIS-UH/16/{{X}}_{{Y}}.dzi (didn't work)

**Comment by lovasoa** [comment]
See https://github.com/lovasoa/dezoomify/issues/366

You should be able to use the generic dezoomer
