### ISSUE TITLE
Issues with British Geological Survey IIIF

### ISSUE THREAD

**Issue by jolyonralph** [lovasoa/dezoomify-rs#129]
This doesn't seem to work.

http://pubs.bgs.ac.uk/diva/diva-v4.1.0/json_files/B07310.json

--

ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - custom: The 'custom' dezoomer cannot handle this URI
 - google_arts_and_culture: The 'google_arts_and_culture' dezoomer cannot handle this URI
 - zoomify: The 'zoomify' dezoomer cannot handle this URI
 - generic: The 'generic' dezoomer cannot handle this URI
 - pff: The 'pff' dezoomer cannot handle this URI
 - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
 - nypl: The 'nypl' dezoomer cannot handle this URI
 - iiif: Unable to create the dezoomer: Invalid IIIF info.json file: missing field `width` at line 1 column 101597
 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 1:1 Unexpected characters outside the root element: {
 - krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 1:1 Unexpected characters outside the root element: {

dezoomify-rs expects a zoomable image meta-information file URL. To find this URL, you can use the dezoomify browser extension, which you can download at
- https://lovasoa.github.io/dezoomify-extension/ 
If this doesn't help, then your image may be in a format that is not yet supported by dezoomify-rs.
You can ask for a new format to be supported by opening a new issue on https://github.com/lovasoa/dezoomify-rs/issues

**Comment by lovasoa** [comment]
This format is not supported by dezoomify. If you want to open a feature request, please give more context and information instead of just a link to a json file.

**Comment by jolyonralph** [comment]
My apologies, I assumed it was a standard(ish) IIIF file because it uses an IIIF viewer for display. I have no idea what they did with it.

Here's the context - the page that specific json file was referenced by:

http://pubs.bgs.ac.uk/publications.html?pubID=B07310

**Comment by Professor-Carrot** [comment]
I'm also experiencing the same problems while attempting to download scans vintage BGS maps. For example, this is an old scan of a geologic map of the Snowdonia mountain range:

https://largeimages.bgs.ac.uk/iip/mapsportal.html?id=1001609

Using both the CLI and the web extension gives the same output. In regard to server side software, they seem to using https://iipimage.sourceforge.io
