### ISSUE TITLE
unable to parse bl.uk urls from dezoomify-rs

### ISSUE THREAD

**Issue by Jarshvor** [lovasoa/dezoomify-rs#131]
I am trying to use dezoomify-rs with the following url.
`http://www.bl.uk/manuscripts/Viewer.aspx?ref=add_ms_10366_f020r`
`http://www.bl.uk/manuscripts/Proxy.ashx?view=add_ms_10366_f020r_files/0/0_0.jpg`

It works perfectly fine with the browser extension (which appearently selects the deepzoom dezoomer when choosing auto).
However it fails when trying `auto` or even `-d deepzoom` with dezoomify-rs.

`ERROR Dezoomer error: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 1:1 Unexpected characters outside the root element: T
`
Reading that the deepzoom dezoomer expects a dzi file I also tested with the following urls:
`http://www.bl.uk/manuscripts/Proxy.ashx?view=add_ms_10366_f020r.dzi`

There is something I might not be doing right as the error is still the same.

------------------------------------------------------------------------------------------
On another note, let me congratulate you for such a great and generous tool. I just came from reading that whole arts and culture controversy issue, and have to say my admiration for this project has doubled now that I know all the troubles entailed.
Merci beaucoup! ;)

**Comment by lovasoa** [comment]
You can download the image by providing the meta-information file: `http://www.bl.uk/manuscripts/Proxy.ashx?view=add_ms_10366_f020r.xml`

And thank you for showing your appreciation :)

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/118269666-4daf0100-b4bf-11eb-9ac0-b617fbdd8eae.jpg)

**Comment by lovasoa** [comment]
I'll close this issue and open a new one as a feature request for auto-detecting dzi files ending in `.xml`, like it's done in the dezoomify website (https://github.com/lovasoa/dezoomify-extension/issues/8)
