### ISSUE TITLE
Error on entering with format

### ISSUE THREAD

**Issue by DimoNline** [lovasoa/dezoomify-rs#133]
When I input just a link - it works. But if I enter output file- it drops an erroro
`Enter an URL or a path to a tiles.yaml file:
http://boschproject.org/dzi/99_100_101_MCPVIS_files/0/0_0.jpg image.jpg
ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:
...`
![image](https://user-images.githubusercontent.com/19239834/119825572-c3738d80-beff-11eb-8e00-77527236239e.png)

**Comment by lovasoa** [comment]
This is the expected behavior.

**Comment by lovasoa** [comment]
To enter an output file name, you have to provide it as an argument to the program when you launch it, not **when it asks you for an URL** .

**Comment by lovasoa** [comment]
Instead of double-clicking the executable, you should first open a terminal, and then type the program name and arguments before hitting enter.

https://omics.pnl.gov/software/command-line-application-help
