### ISSUE TITLE
Add option to output original unjoined tiles

### ISSUE THREAD

**Issue by tim-nz** [lovasoa/dezoomify-rs#134]
It would be great to be able to output the original tile files. Then they could be stitched together losslessly using something like [jpegjoin](https://jpegclub.org/jpegtran/).

Ideally, they would have a naming structure that made it easy to order the tiles, e.g. [x index]-[y index].jpg.

**Comment by lovasoa** [comment]
Duplicate of https://github.com/lovasoa/dezoomify-rs/issues/26

**Comment by lovasoa** [comment]
I added a tile cache in the latest development version. Can you test it and give feedback before I release it ?
