### ISSUE TITLE
dezoomify-rs error with Salzburg Museum

### ISSUE THREAD

**Issue by tojoshuazhang** [lovasoa/dezoomify-rs#135]
using this page as example:
https://sammlung-online.salzburgmuseum.at/detail/collection/cbdb01e0-7999-4fd3-85be-1d69d3314f39

I got the info.json file and construct below command:
dezoomify-rs --compression 0 -H "Referer: https://sammlung-online.salzburgmuseum.at/" https://sammlung-online.salzburgmuseum.at/iiif/iiif/2/abbdb985-81b6-46f8-90cd-e9bea1351e2c/info.json

It started to run but return error:
dezoomify_rs] network error: error sending request for url (https://smglx1.smca.at/iiif/iiif/2/abbdb985-81b6-46f8-90cd-e9bea1351e2c/0,0,512,512/512,512/0/default.jpg): error trying to connect: The certificate's CN name does not match the passed value. (os error -2146762481).

**Comment by lovasoa** [comment]
It looks like the info.json contains incorrect information : 

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/552629/121482013-fe2ff800-c9cc-11eb-9a4b-b83a64f52157.png">


You can download the file, and replace `smglx1.smca.at` with `sammlung-online.salzburgmuseum.at`

**Comment by tojoshuazhang** [comment]
@lovasoa Thank you!
