### ISSUE TITLE
GLIBC_2.29 not found

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#136]
I've been trying to use dezoomify-rs for a while but I have been encountering an issue.

On Linux Mint 18.2 and 19.3, as well as MX Linux 19.4, I receive an error along the lines of:
>/home/user/Desktop/dezoomify-rs: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/user/Desktop/dezoomify-rs)

Apparently glibc is a very important Linux c library, it is recommended to update the entire OS rather than tinker with glibc. The Linux Mint 19.3 and MX Linux 19.4 that I tested on were fairly recent distributions, but apparently they still use an older glibc. Is it practical to make dezoomify-rs compatible with older glibc versions? If not, I'll try to find a Linux distribution built on the correct glibc.

Thanks.

_Originally posted by @Yaroslavlskiy in https://github.com/lovasoa/dezoomify/issues/559#issuecomment-861618406_

**Comment by lovasoa** [comment]
Ok, I've reconfigured the CD pipelines to create dezoomify-rs development builds from ubuntu-18.04 instead of 20.04.

Can you test the latest development build on  
https://github.com/lovasoa/dezoomify-rs/releases ?

If it works okay, I'll update the production pipeline too.

**Comment by lovasoa** [comment]
https://github.com/lovasoa/dezoomify-rs/releases/tag/build-a689f3c54da299ffa8c9adf9cdf0c70c9f82392c

**Comment by Yaroslavlskiy** [comment]
Using Linux Mint 19.3 and MX Linux 19.4, the regular tile address http://ars1.ru/art/img/8/8805-dz/12/0_1.jpg does produce an error:

>ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:
>
> - custom: The 'custom' dezoomer cannot handle this URI
> - google_arts_and_culture: The 'google_arts_and_culture' dezoomer cannot handle this URI
> - zoomify: The 'zoomify' dezoomer cannot handle this URI
> - generic: The 'generic' dezoomer cannot handle this URI
> - pff: The 'pff' dezoomer cannot handle this URI
> - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
> - nypl: The 'nypl' dezoomer cannot handle this URI
> - iiif: Unable to create the dezoomer: Invalid IIIF info.json file: expected value at line 1 column 1
> - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 1:1 invalid utf-8: corrupt contents
> - krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 1:1 invalid utf-8: corrupt contents
>
>dezoomify-rs expects a zoomable image meta-information file URL. To find this URL, you can use the dezoomify browser extension, which you can download at
>- https://lovasoa.github.io/dezoomify-extension/ 
>If this doesn't help, then your image may be in a format that is not yet supported by dezoomify-rs.
>You can ask for a new format to be supported by opening a new issue on https://github.com/lovasoa/dezoomify-rs/issues

But the generic address http://ars1.ru/art/img/8/8805-dz/12/{{X}}_{{Y}}.jpg works fine.

Using Linux Mint 18.2 it gives this error:
>/home/user/Desktop/dezoomify-rs: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/user/Desktop/dezoomify-rs)

The older version of dezoomify-rs gives both the GLIBC_2.27 and GLIBC_2.29 not found errors on this OS. Linux Mint 18.2 was released in July 2017, perhaps it is not worth worrying about.

Please let me know if I should test anything else.

Thanks.

**Comment by lovasoa** [comment]
ok, great it works as expected

**Comment by lovasoa** [comment]
I'll try to release that to stable tomorrow

**Comment by lovasoa** [comment]
closed by 060687b1dce0b4261a41afbac677addeb2da8331

**Comment by lovasoa** [comment]
v2.6.7 has been released, with compatibility with older linux distributions: https://github.com/lovasoa/dezoomify-rs/releases/tag/v2.6.7
