### ISSUE TITLE
Śląska Biblioteka Cyfrowa

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-rs#137]
Good summer, @lovasoa. I hope you're very fine🤗.
I've a little dilemma  with the above website: Idk if **[dezoomify-rs](https://github.com/lovasoa/dezoomify-rs)** can apply to it. 
F.e., I want to download [this map](https://www.sbc.org.pl/dlibra/publication/1666/edition/1508/content) (13708x14449 px) without conversion _.djvu-to-.jpg._ Is it possible? Maybe creating a `tiles.yaml`... 
Thank You in advance and sorry me for a maybe boring question.

**Comment by lovasoa** [comment]
If the source image is in djvu, you are never going to get anything "better" than the original.
This is not a tiled image, this is just a djvu file rendered in the browser.

**Comment by lovasoa** [comment]
You can use imagemagick to convert from djvu to a more classical image format.

I uploaded the file to wikimedia:
https://commons.wikimedia.org/wiki/File:Stara_Kamienica_1886_map.jpg

**Comment by Arekkusu1998** [comment]
Thanks for Your kind advice!
