### ISSUE TITLE
ERROR PNG encoding error: Zero width not allowed

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#138]
Hello Lovasoa,

I'm having problems as well with the kbr.be site ..

URL : https://viewerd.kbr.be/gallery.php?map=A/1/6/1/6/2/4/8/BE-KBR00_A_1616248_0000_00_00_0001.jpg
URL from 1 tile : https://viewerd.kbr.be/display/A/1/6/1/6/2/4/8/zoomtiles/BE-KBR00_A_1616248_0000_00_00_0001/4-0-0.jpg

So, in dezoomify-rs.exe I enter : 
dezoomify-rs --header "Referer: https://viewerd.kbr.be/display/A/1/6/1/6/2/4/8/zoomtiles/BE-KBR00_A_1616248_0000_00_00_0001/4-{{X}}-{{y}}.jpg"

This results is following error : 
" ERROR PNG encoding error: Zero width not allowed "

![Screenshot-error](https://user-images.githubusercontent.com/86778933/124114654-1d222700-da6d-11eb-86ce-8b2f8c7651a7.JPG)

Hope you can help me out.
Great extension so far !! 

Boris

_Originally posted by @BorisDekorte in https://github.com/lovasoa/dezoomify/issues/120#issuecomment-872147654_

**Comment by lovasoa** [comment]
It looks like you are typing the command-line **inside of dezoomify**.

Once you have started dezoomify, it's too late, you cannot pass arguments to it.
You should read about how the command-line work, and how to launch a program with arguments: https://superuser.com/questions/617174/pass-parameters-via-command-line-argument-to-exe

And you are mistaking the header and the actual tile URL template you are giving to dezoomify. Your command should look like:

```
dezoomify-rs --header "Referer: http://the-viewer-page-url" http://the-tile-url-template-with-{{X}}-and-{{Y}}
```

(this is the command to type into your command prompt, not inside dezoomify-rs)

**Comment by BorisDekorte** [comment]
Hi Lovasoa,

Thanks for the reply. However i'm still getting the same error.
My workflow : 

1. i open the command prompt
2. i drag the "dezoomify-rs" file into the command prompt
3. Enter
4. command prompt asks : "Enter an URL or a path to a tiles.yaml file:"
5. I enter my specific command
dezoomify-rs --header "Referer: https://viewerd.kbr.be/” "https://viewerd.kbr.be/display/A/1/6/1/6/2/4/8/zoomtiles/BE-KBR00_A_1616248_0000_00_00_0001/4-{{X}}-{{Y}}.jpg”
6. Error (see image attached)
<img width="1278" alt="Screenshot" src="https://user-images.githubusercontent.com/86778933/124155483-d2b5a000-da96-11eb-8118-973d85ee6700.png">


could you please point out what i'm missing ?
Many thanks in advance !

Boris

**Comment by lovasoa** [comment]
You are still typing the command inside dezoomify-rs instead of on the command prompt.
When dezoomify-rs tells you "enter an url", you can only... enter an url ! Not add commandline options.

**Comment by lovasoa** [comment]
```
cd /path/to/the/folder/with/dezoomify-rs/
./dezoomify-rs --header "Referer: https://viewerd.kbr.be/" "https://viewerd.kbr.be/display/A/1/6/1/6/2/4/8/zoomtiles/BE-KBR00_A_1616248_0000_00_00_0001/4-{{X}}-{{Y}}.jpg"
```

**Comment by BorisDekorte** [comment]
Now it worked. Thank you so much !
