### ISSUE TITLE
Cannot output .png 

### ISSUE THREAD

**Issue by bguisset** [lovasoa/dezoomify-rs#139]
Hello,

Apologies in advance since I think it is a very basic question. I am trying to download a Google Arts & Culture image (https://artsandculture.google.com/asset/a-wooded-watershed-daniel-garber/oAEAyv_UZh1cUg).

I have succesfully downloaded dezoomify-rs. I managed to download the image in all but the highest resolution level.  I assume that the full resolution is higher than the maximum allowed for a .jpeg file, which seems to be the default output format. I understand that I need to change the output format to .png.  From the explanations in the readme file, it seems easy, but somehow I fail to execute the instructions ("_for instance, entering dezoomify-rs http://example.com/ my_image.png on the command line will create a PNG image_").  I tried quite a few commands, without success.

In the application, Dezoomify asks "Enter a URL or a path to a tiles.yaml file".  Is there something that I should add to the URL to change the format or is it more complicated than that?

Thanks for the help,

Bertrand

**Comment by lovasoa** [comment]
Yes, this is a recurring issue for dezoomify-rs users. You need to launch the application from the command line, typing the arguments on the command line, instead of double-clicking on the application from your file browser.

**Comment by lovasoa** [comment]
https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt

**Comment by bguisset** [comment]
Thanks a lot. It worked.  

Now I can't open the 5go .png that I created, but that's another issue :-) .

Bertrand

**Comment by lovasoa** [comment]
Yes, huge png files are not very useful. For visualization, it's better to download the image as IIIF
