### ISSUE TITLE
HTTP status client error (403 Forbidden) for url ...

### ISSUE THREAD

**Issue by GabZach** [lovasoa/dezoomify-rs#140]
I have just downloaded the latest version and run it on macOS Big Sur.

I get many of the following error messages:

[2021-07-14T17:38:37Z WARN  dezoomify_rs::network] network error: HTTP status client error (403 Forbidden) for url (https://lh3.googleusercontent.com/gwn4lnxKs3dRcNXmGn2ZDRutfyGdZZ37L_LPxHJkcjm0S97-EbZWmmEO9ZgXasraGA=x2-y0-z2-tlkYgF1iARsagvsJ8nJLHRFgBmwU). Retrying tile download in 2.48s.
...
ERROR Could not get any tile for the image

The URL: 
https://artsandculture.google.com/story/self-portrait-as-the-allegory-of-painting-c-1638-9/hwLCm5iuhIvaKQ

Is there anything I'm doing wrong?

Version:
dezoomify-rs 2.7.1
lovasoa

**Comment by lovasoa** [comment]
Hello ! The URL to use is the URL of the painting itself, not the URL of the nice google arts story.

https://artsandculture.google.com/asset/self-portrait-as-the-allegory-of-painting-la-pittura-artemisia-gentileschi/wwENmp3dXLo4kg

**Comment by GabZach** [comment]
Thanks a lot! of course, i should have seen that right away ... thanks all the more.
