### ISSUE TITLE
Got "Unable to find the token in the page" when download from Google Art and Culture

### ISSUE THREAD

**Issue by maghsk** [lovasoa/dezoomify-rs#141]
Image URL: https://artsandculture.google.com/asset/the-meeting-of-dido-and-aeneas-sir-nathaniel-dance-holland/XQGCpNt3tbJiAw
Error message: `ERROR Dezoomer error: Unable to create the dezoomer: Unable to find the token in the page`
Command: `dezoomify-rs -l -d google_arts_and_culture "https://artsandculture.google.com/asset/the-meeting-of-dido-and-aeneas-sir-nathaniel-dance-holland/XQGCpNt3tbJiAw" my_image.png`

**Comment by lovasoa** [comment]
Hello,
  I cannot reproduce your issue. The download works fine.

```
target/release/dezoomify-rs -l -d google_arts_and_culture 'https://artsandculture.google.com/asset/the-meeting-of-dido-and-aeneas-sir-nathaniel-dance-holland/XQGCpNt3tbJiAw' my_image.png`
[ETA:0s] ########################################   20/20   Finished tile download
Image successfully saved to 'my_image.png' (current working directory: /home/olojkine/dev/dezoomify-rs)
```

  Please make sure you are using the latest version of dezoomify-rs when reporting an issue.

![my_image](https://user-images.githubusercontent.com/552629/126912293-556acc6e-a5f5-497a-820f-37edda08122d.png)
