### ISSUE TITLE
sinica.edu.tw support

### ISSUE THREAD

**Issue by mappingmonkey** [lovasoa/dezoomify-rs#142]
Getting an error trying to download images from sinica.edu.tw. For example

 https://iiif.rchss.sinica.edu.tw/map_moi_land/item.php?f=AdminMap_64005_2 has the following .json

https://iiif.rchss.sinica.edu.tw/loris/map_moi_land/AdminMap_64005_2.jp2/info.json

When I run it through dezoomify-rs or dezoomify it gives the following error

`[ETA:0s] ########################################    0/0    Computing the URLs of the image tiles...
[2021-07-26T07:37:29Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://iiif.rchss.sinica.edu.tw/loris/map_moi_land%2FAdminMap_1000101_2.jp2/0,0,10137,13438/10137,13438/0/default.jpg). Retrying til[ETA:0s] ########################################    1/1    Finished tile download`

Comparing the tile URL's

dezoomify generated

`https://iiif.rchss.sinica.edu.tw/loris/map_moi_land/AdminMap_1000101_2.jp2/0,0,10137,13438/10137,13438/0/default.jpg`

web generated

`https://iiif.rchss.sinica.edu.tw/loris/map_moi_land/AdminMap_1000101_2.jp2/0,0,10137,13438/1268,/0/default.jp`

Is it possible to resolve?

Thanks

**Comment by lovasoa** [comment]
The info.json file on their side is invalid.

You can download the image directly from their server, they don't seem to have any tiling.

https://iiif.rchss.sinica.edu.tw/loris/map_moi_land/AdminMap_64005_2.jp2/0,0,13491,9844/6746,/0/default.jpg

![](https://iiif.rchss.sinica.edu.tw/loris/map_moi_land/AdminMap_64005_2.jp2/0,0,13491,9844/6746,/0/default.jpg)
