### ISSUE TITLE
Build for older Mac Versions (Invalid Instruction)?

### ISSUE THREAD

**Issue by skepticalwaves** [lovasoa/dezoomify-rs#143]
I'm stilling rocking a Mac Pro 1,1 for various reasons, however I can't run the precompiled version provided for OSX because it has been compiled with CPU instructions I don't have. I'd like to request a compiled version for "older" macs.

Thanks!

**Comment by lovasoa** [comment]
Hello! You can compile the software from source for your architecture by installing the rust toolchain (rustup), then running `cargo build --release` from the root of this repo.

**Comment by skepticalwaves** [comment]
Here's hoping the rust build system supports old hardware...
