### ISSUE TITLE
Current version on crates.io?

### ISSUE THREAD

**Issue by Messere** [lovasoa/dezoomify-rs#144]
Current version on github is 2.7.1, but latest version on crates.io is still 2.6.6. Would it be possible to update it?

**Comment by lovasoa** [comment]
Done: https://crates.io/crates/dezoomify-rs

Just out of curiosity: is there a particular reason why you are using dezoomify-rs from crates.io ?

**Comment by Messere** [comment]
I'm installing dezoomify-rs on Gentoo, using Gentoo's ebuild system. It's easier to write a cargo based ebuild if complete source code is available via crates. 

Thanks for quick update!
