### ISSUE TITLE
Test the new beta release

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#15]
I just released a new version of dezoomify-rs in beta yesterday.  The new version requests the image tiles in a non-blocking manner, which should make the whole process faster than it used to be. 

Can you please test this beta version and report any issues or regressions, including performance regressions ?

https://github.com/lovasoa/dezoomify-rs/releases/tag/v1.6.0-beta

@Arekkusu1998, @rigel71, @zern, @autur

**Comment by rigel71** [comment]
Hi,
i test two maps IIF.
I used dezoomify-rs 1.5.5 and the new version
I tested with the command on the prompt dezoomyfy-ra tiles.yaml result.png
and in 1.5.5 map downoladed on 44 min. 994mb
in new beta version on 7 min. 994 mb

I tested also in command info.json
with 1.5.5 map downloaded in 24 min. 52.4mb jpg
in beta version 4 min 53.700 mb jpg
new version in very faster :-)

**Comment by lovasoa** [comment]
Hello all ! I'm very happy to see these results ! Even in my own tests (on linux), I didn't see such large performance improvements. 44 to 7 minutes is a 6x speedup! Thank you for helping test the software. If no one reports any regression in the coming days, then I'm going to release the new version as stable.

And merry Christmas to you too :)

**Comment by rigel71** [comment]
Merry Christmas and a happy new year!

**Comment by MrChauNguyen** [comment]
The beta works fine on Win10x64. 
Is there a way to get around memory allocation issue? 
I'm trying to download level 8 zoom which has 20,160 tiles. I have 24GB RAM, of which 8GB is dedicated to RAMDisk. I have enable virtual memory features in Win10.
Thank you.
![Capture](https://user-images.githubusercontent.com/59969833/72541187-0e7f8a00-3850-11ea-88f6-87982fd0939f.PNG)

**Comment by lovasoa** [comment]
@MrChrisWin : I moved your comment to #16
