### ISSUE TITLE
National Palace Museum taiwan's iiif manifest cannot be downloaded

### ISSUE THREAD

**Issue by jeanmondonville** [lovasoa/dezoomify-rs#152]
Hi,
The National Palace Museum in Taipei has a new image system(https://digitalarchive.npm.gov.tw). Their info.json(https://iiifod2.npm.gov.tw/iiif/2/K2A%2FK2A000866N000000000PAA/info.json) can be downloaded successfully, but the iiif manifest always fails(https://digitalarchive.npm.gov.tw/Painting//setJson?pid=3782&Dept=P)
![no](https://user-images.githubusercontent.com/93721727/140598661-6f119d45-90a8-4207-8065-f4ea7b16fe7e.jpg)
.
So can you teach me how to download this kind of iiif manifest, download mutiple images at a time. I hope I can get a lot of resources from this website.
Your help would be greatly appreciated.

**Comment by lovasoa** [comment]
It's the info.json file that you should pass to dezoomify-rs.

```
dezoomify-rs https://iiifod2.npm.gov.tw/iiif/2/K2A%2FK2A000866N000000000PAA/info.json
```

![dezoomified_0002](https://user-images.githubusercontent.com/552629/140605635-3e8dbce4-2763-44b4-92f1-97c8367b4e89.jpg)
