### ISSUE TITLE
The Morgan Library and format .zif

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#153]
Hi how are things?
In The Morgan Library they have tremendously interesting things. As a wonderful Blessed shows:
https://www.themorgan.org/collection/commentary-apocalypse/110807/thumbs
I have managed to download the .zif files of all the pages; but I don't see a way to find a converter for these files (preferably in batch) to .jpg or .png format, for example.
Is there a tool (that you know) that allows you to do this?
Thank you so much. Regards,

**Comment by lovasoa** [comment]
zif images are just tiff

https://github.com/lovasoa/ZIF#zif

https://zif.photo/

You can mass convert them on the commandline with imagemagick, for instance
