### ISSUE TITLE
Help, can't download images correctly!!!

### ISSUE THREAD

**Issue by 954097023** [lovasoa/dezoomify-rs#155]
I'm new to this and I see that your tool is very powerful, but I can't download the images correctly.

Reason: network problem.

I use the tool to download in mainland China prompting an error, using windows connection VPN to download or using the US VPS command to run the tool can not be downloaded properly, is there any way to optimize this tool for network connection problems?

![1](https://user-images.githubusercontent.com/45094614/141956484-c07b8260-16e3-45ca-bef4-212701df421c.jpg)

![image](https://user-images.githubusercontent.com/45094614/141956468-d14ab68f-b3e7-41cd-aea4-50b2918125f5.png)

**Comment by lovasoa** [comment]
Hello, from your screenshots, it looks like it's the same image as in  https://github.com/lovasoa/dezoomify-rs/issues/152

The server behind https://iiifod2.npm.gov.tw/iiif/2/K2A%2FK2A000866N000000000PAA/info.json seems inaccessible for me too, so this does not seem to be an issue with dezoomify, but rather with their server.

![image](https://user-images.githubusercontent.com/552629/142000600-3a521c55-5f48-417f-bd9d-ec6c3030fd06.png)

**Comment by 954097023** [comment]
The picture is this link:https://digitalarchive.npm.gov.tw/Painting/IIIFViewer?pid=16&Dept=P

**Comment by 954097023** [comment]
> 你好，从你的截图来看，和[#152中的](https://github.com/lovasoa/dezoomify-rs/issues/152)图片是一样的 [](https://github.com/lovasoa/dezoomify-rs/issues/1
> 
> https://iiifod2.npm.gov.tw/iiif/2/K2A%2FK2A000866N000000000PAA/info.json背后的服务器对我来说似乎也无法访问，所以这似乎不是 dezoomify 的问题，而是他们的服务器的问题。
> 
> ![图片](https://user-images.githubusercontent.com/552629/142000600-3a521c55-5f48-417f-bd9d-ec6c3030fd06.png)

**Comment by 954097023** [comment]
图片是这个链接：https : //digitalarchive.npm.gov.tw/Painting/IIIFViewer?pid=16&Dept=P
