### ISSUE TITLE
https://wwii.germandocsinrussia.org/

### ISSUE THREAD

**Issue by atk3289** [lovasoa/dezoomify-rs#156]
Please add a dezoomer for this website

**Comment by lovasoa** [comment]
Looks like that site does not have tiled images.
The images can be downloaded directly from the site without any external tooling.
 
https://wwii.germandocsinrussia.org/pages/73791/zooms/8

**Comment by atk3289** [comment]
What about maps like these:
https://wwii.germandocsinrussia.org/pages/313709/map

**Comment by lovasoa** [comment]
that one is tiled. Should work with the generic dezoomer

https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial
