### ISSUE TITLE
https://aste.capitoliumart.it/it/lot/59274

### ISSUE THREAD

**Issue by emallen1973** [lovasoa/dezoomify-rs#158]

**Comment by emallen1973** [comment]
I need help downloading an image from https://aste.capitoliumart.it/it/lot/59274.

Dezoomify does not work using the usual method.

**Comment by lovasoa** [comment]
Hello !
  You can use the [Generic Dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) with this site : 

https://dezoomify.ophir.dev/#https://max1.prodibicdn.com/rd0ee8yleg28d51/00/13/{{X}}_{{Y}}.jpg

**Comment by emallen1973** [comment]
Thank you so much.

Enrique
