### ISSUE TITLE
Network error, maybe is beacouse VPN

### ISSUE THREAD

**Issue by STGreyLibary** [lovasoa/dezoomify-rs#159]
Hi!

Chinese govement banned artsandculture.google.com, normally i use VPN to visit this website.

` - google_arts_and_culture: Unable to download required data: network error: error sending request for url (https://artsandculture.google.com/asset/the-fisherman-and-the-syren-leighton-lord-frederic/wwF5y052mfTeow): error trying to connect: tcp connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)`

Whether using a VPN or not, it shows this error.

Please help.

**Comment by lovasoa** [comment]
I'm not sure I can help. You can contact your VPN vendor and ask them about command-line applications
