### ISSUE TITLE
When an IIIF server offers jpg/webp/png/tif image tiles,  dezoomify-rs only download jpg tiles

### ISSUE THREAD

**Issue by HaaiSo** [lovasoa/dezoomify-rs#160]
hello, sorry for my bad english.

The IIIF server in Harvard University provides 4 image formats, but i can't select png tiles. I can only select what formats I saved, but not what formats I download.
example： 'https://ids.lib.harvard.edu/ids/iiif/48431621/info.json'

If we can download png/tif tiles and compose to a png/tif file，（example ’https://ids.lib.harvard.edu/ids/iiif/48431621/0,0,1024,1024/1024,/0/default.tif‘），then we can get real lossless pictures.

**Comment by lovasoa** [comment]
Fixed in 2.8.0. png tiles are now preferred over jpeg ones when they are available
