### ISSUE TITLE
What method to use to download this image? 

### ISSUE THREAD

**Issue by itkind** [lovasoa/dezoomify-rs#164]
https://sammlungen.ub.uni-frankfurt.de/freimann/content/zoom/8252319

Thank you!

**Comment by CharlyAlonso** [comment]
Hi,

I'm afraid this website does not use a mosaic method. They have the images for direct download.

https://sammlungen.ub.uni-frankfurt.de/download/webcache/2000/8252319?orig=true
https://sammlungen.ub.uni-frankfurt.de/download/webcache/2000/8252320?orig=true
https://sammlungen.ub.uni-frankfurt.de/download/webcache/2000/8252321?orig=true
....

Of course, it is my opinion.

Greetings,

**Comment by itkind** [comment]
Thank you for your help.
