### ISSUE TITLE
Add support for gigapixel images using Secondcanvas viewer

### ISSUE THREAD

**Issue by takaji10** [lovasoa/dezoomify-rs#171]
Example: https://www.mauritshuis.nl/en/our-collection/artworks/253-the-garden-of-eden-with-the-fall-of-man/
I found this JSON file, but it didn't work with dezoomify-rs: https://sc9bfffn178962304b143b28d.s3.amazonaws.com/web/15w039083525c8294828129b18301fa/a15vey17897785656f54ae0_en.json

Scroll down until the image comes into view as the main object, and then it's possible to zoom into a gigapixel-sized image.

Edit: I was able to get this working using the generic dezoomer and following the YouTube tutorial (https://youtu.be/SY1dZe7MrUQ) and then inputting the modified link into dezoomify-rs.

Thanks!

**Comment by lovasoa** [comment]
Thank you for opening this : we have identified the zoomable format behind this image and are going to add support for it. We are consolidating all reports about this format to https://github.com/lovasoa/dezoomify/issues/808
