### ISSUE TITLE
1.how to set the storage location? 2.how to change the compression rate?

### ISSUE THREAD

**Issue by jack112111** [lovasoa/dezoomify-rs#172]
dear master, thanks for you genius dezoomify-rs!
I'm very amature in coding, i can just use the basic function of dezoomify, but it still help very much.
i have 2 questions as below:
1.how to set the storage location of dezoomify-rs ? 2.how to change the compression rate?

**Comment by lovasoa** [comment]
You can run `dezoomify-rs --help` to view a list of options.

You can set the compression to 0 and target location to `my_folder` with 

```
dezoomify-rs --compression 0 https://yourimage.com/ my_folder/my_image.jpg
```

To learn how to launch command-line applications with arguments, you can find many useful resources on the internet.
