### ISSUE TITLE
dezoomify-rs uses artsandculture.google.com addresses with special characters and does not work.

### ISSUE THREAD

**Issue by rokili** [lovasoa/dezoomify-rs#177]
https://artsandculture.google.com/asset/der-ungl%C3%A4ubige-thomas-michelangelo-merisi-named-caravaggio/OAEjjQkNdRL9sg

https://artsandculture.google.com/asset/der-ungläubige-thomas-michelangelo-merisi-named-caravaggio/OAEjjQkNdRL9sg

Is this address unresolvable because it contains special character? What can you do?

**Comment by lovasoa** [comment]
duplicate of #178
