### ISSUE TITLE
Google Arts & Culture is no longer available for download

### ISSUE THREAD

**Issue by zern** [lovasoa/dezoomify-rs#178]
Google Arts & Culture is no longer available for download
Can you update and support it
Thank you

**Comment by lovasoa** [comment]
I think I found the change and how to adapt to it.

Please test the changes on dezoomify, and I'll adapt them to dezoomify-rs

https://github.com/lovasoa/dezoomify/issues/638

**Comment by Tricesimo** [comment]
I'd like to help test, using this one:
https://artsandculture.google.com/asset/the-fourth-estate-giuseppe-pellizza-da-volpedo/9AExoJykUS5d5g

Please let me know how I can help.

**Comment by rokili** [comment]
@lovasoa 
Waiting for dezoomify-rs to update!
thank you so much!!!

**Comment by lovasoa** [comment]
For those who want to help, you can sponsor my work on dezoomify on https://github.com/sponsors/lovasoa/

**Comment by lovasoa** [comment]
> I'd like to help test, using this one: https://artsandculture.google.com/asset/the-fourth-estate-giuseppe-pellizza-da-volpedo/9AExoJykUS5d5g


This one now works on https://dezoomify.ophir.dev

![dezoomify result](https://user-images.githubusercontent.com/552629/179362854-0eadb603-a333-44e5-b719-17b737baa8c6.jpg)

**Comment by rirgang** [comment]
> I think I found the change and how to adapt to it.
> 
> Please test the changes on dezoomify, and I'll adapt them to dezoomify-rs
> 
> [lovasoa/dezoomify#638](https://github.com/lovasoa/dezoomify/issues/638)

Working perfectly. Thanks

**Comment by lovasoa** [comment]
I just published dezoomify-rs v2.9.0 which supports the new google arts & culture pages :slightly_smiling_face:

**Comment by lovasoa** [comment]
v2.9.1 fixes an issue in v2.9.0, it should be able to download anything from Google Arts & Culture. Let me know if you encounter an issue with an image.
