### ISSUE TITLE
PFF file support

### ISSUE THREAD

**Issue by look2020** [lovasoa/dezoomify-rs#18]
Hi,

I'm not sure if this large image can be downloaded by using dezoomify-rs:
http://digital2.library.ucla.edu/viewItem.do?ark=21198/zz0019pd69

This seems to be the image's tile info like width, height, number of tiles and tile size:
http://digital2.library.ucla.edu/zoomify/servlet/zoomifyservlet.ZoomifyServlet?file=\\ad\Dlib\dlcontent-prod\yuhan\zoomify\21198-zz0019pd69_736971_master.pff&requestType=1

One of the image files:
http://digital2.library.ucla.edu/zoomify/servlet/zoomifyservlet.ZoomifyServlet?file=\\ad\Dlib\dlcontent-prod\yuhan\zoomify\21198-zz0019pd69_736971_master.pff&requestType=0&begin=45112577&end=45132342&vers=106&head=15331

But I do not know how to create the proper URL rule in the .yaml template. Can someone help?

Thank you very much!

**Comment by lovasoa** [comment]
This looks like a pff image. I do not have the time to check right now, but I think you can download the whole file and then convert it to jpeg with https://github.com/lovasoa/pff-extract

**Comment by lovasoa** [comment]
I added support for zoomify PFF in dezoomify-rs. This will be available in version v1.7.0, you will be able to download it in a few minutes, once it finishes building.

**Comment by lovasoa** [comment]
![small](https://user-images.githubusercontent.com/552629/72739701-7b728700-3ba4-11ea-9968-a4ce2bf2dc5d.jpg)

**Comment by look2020** [comment]
@lovasoa , this is really an amazing tool to download very large images! I also found it can even save those large dimension (over 30000 pixel) images to JPG format and the file size is much much less than that of the same image downloaded via http://ophir.alwaysdata.net/dezoomify/dezoomify.html. This is going to save my hard drive space. Great work!

**Comment by lovasoa** [comment]
Be careful when saving large JPEG images, though. The JPEG format limits image sizes to a maximum of 65,535×65,535 pixels.
