### ISSUE TITLE
Web version working great but downloaded application not working. Help please

### ISSUE THREAD

**Issue by LionFish777** [lovasoa/dezoomify-rs#181]
Not sure if I am doing something wrong. The website works great but I cannot get the application to work on same URL.

![image](https://user-images.githubusercontent.com/111300436/184673467-c0eea5ff-60e6-4c0c-b37c-a839625790ee.png)

Please help and thanks!

**Comment by MrChrisWin** [comment]
You don't need dezoomify-rs. When I visited the link, there is a download icon right on the image.

**Comment by LionFish777** [comment]
I don't think that image is the highest resolution image available, which is why I am using the application.
My question is why isn't the application working for me. I have tried many urls from different websites; the application displays the same message for all of them. I have not gotten it to work one time, which is why I am wondering if I am missing a step. The web version works very well. I just wanted to see if the application was faster.

Thanks again

**Comment by MrChrisWin** [comment]
Please keep in mind that some museums do not provide nor keep high resolution images on their servers. Philadelphia museum and High Museum of Atlanta are some of examples of museums who don't. I can see they have concerns about people reproducing prints of the artworks, which the museum themselves do as a source of income.
The application works on many sites like National Gallery of Art in DC and UK National Gallery of Art. You just have to figure that part out on your own. I find looking at CLOSED issues providing ample of hints. Good luck.

**Comment by LionFish777** [comment]
I see. Thanks for the explanation.
