### ISSUE TITLE
Dezoomify doesn't work on scrolls.uchicago.edu

### ISSUE THREAD

**Issue by YuriFerro** [lovasoa/dezoomify-rs#184]
I tried downloading the zoomable images from this site (particulary this image: https://scrolls.uchicago.edu/view-scroll/210) but the site, extension and app doesn't seem to work. I also tried following the method on FAQs. Can anyone help? Sorry for being a newbie.

**Comment by Benomrans** [comment]
Hello,
Zoom in to the last tile, obtain the url, which is : https://s3.us-east-2.amazonaws.com/scrolls/MET-1990-54_files/17/424_5.jpeg
then change it to : https://s3.us-east-2.amazonaws.com/scrolls/MET-1990-54_files/17/{{X}}_{{Y}}.jpeg 
and pass it to dezoomify-rs and wait for the magic.!  ( that's a huge image with 111690 px ).

**Comment by YuriFerro** [comment]
> Hello, Zoom in to the last tile, obtain the url, which is : https://s3.us-east-2.amazonaws.com/scrolls/MET-1990-54_files/17/424_5.jpeg then change it to : [https://s3.us-east-2.amazonaws.com/scrolls/MET-1990-54_files/17/{{X}}_{{Y}}.jpeg](https://s3.us-east-2.amazonaws.com/scrolls/MET-1990-54_files/17/%7B%7BX%7D%7D_%7B%7BY%7D%7D.jpeg) and pass it to dezoomify-rs and wait for the magic.! ( that's a huge image with 111690 px ).

Thank you so much! I shall use the same method to download other images i couldn't before.
