### ISSUE TITLE
tiles.yaml download multiple image files at once

### ISSUE THREAD

**Issue by bruh-creater** [lovasoa/dezoomify-rs#186]
is it possible to download like 5 different image files at once?

https://trove.nla.gov.au/imageservice/nla.news-page5655/
https://trove.nla.gov.au/imageservice/nla.news-page5656/
https://trove.nla.gov.au/imageservice/nla.news-page5657/
https://trove.nla.gov.au/imageservice/nla.news-page5658/
https://trove.nla.gov.au/imageservice/nla.news-page5659/
https://trove.nla.gov.au/imageservice/nla.news-page5660/

**Comment by lovasoa** [comment]
This question has been asked before. 

See https://github.com/lovasoa/dezoomify-rs/issues/17
and https://github.com/lovasoa/dezoomify-rs/issues/163
