### ISSUE TITLE
factum-arte.com

### ISSUE THREAD

**Issue by Scanirus** [lovasoa/dezoomify-rs#188]
Hello,

Please help with downloading images from this site:

http://www.highres.factum-arte.org/Old-Woman-Cooking-Eggs/shared/viewer.html

http://www.highres.factum-arte.org/Old-Woman-Cooking-Eggs/panos/01_COLOUR_Vieja_Friendo_Huevos_8bits_sRGB_300ppi.tiles/l5/13/l5_13_10.jpg

(replace 13_10 for {{X}}_{{Y}} didn't work in dezoomify-rs)

**Comment by MrChrisWin** [comment]
try:
`dezoomify-rs --parallelism 2 --retries 2  --retry-delay 10s "https://highres.factum-arte.org/Old-Woman-Cooking-Eggs/panos/layers.xml"
`

**Comment by Scanirus** [comment]
Thank you!

Image received)

**Comment by lovasoa** [comment]
I am publishing a new version of dezoomify-rs, v2.11.0, which adds a new command-line argument: `--min-interval`.

`--min-interval` allows setting a minimum delay between consecutive tile requests, making it easier for the remote server to handle, and thus preventing getting banned or crashing the remote server.

See https://github.com/lovasoa/dezoomify-rs/issues/206
