### ISSUE TITLE
Receiving error messages when attempting to execute dezoomify-rs for KBR.be image

### ISSUE THREAD

**Issue by CloisteredMetaphysician** [lovasoa/dezoomify-rs#189]
Hi,

I'm currently trying to execute dezoomify-rs for an image on KBR.be on a Mac (https://uurl.kbr.be/1929124). I'm following the instructions that are on the relevant thread relating to kBR.be (https://github.com/lovasoa/dezoomify/issues/120), but every time I attempt to execute the command, I receive an error message. 

I first changed the directory with `cd /user/[username]/desktop/dezoomify-rs-macos/`

I then entered the command in the same terminal window: 
```
./dezoomify-rs --header "Referer: https://viewerd.kbr.be/" "https://viewerd.kbr.be/display/B/0/7/7/7/1/2/5/0000-00-00_00/zoomtiles/BE-KBR00_B-10777125_0000-00_00_00_0001/3-{{X}}-{{Y}}.jpg"
```

it runs for a bit, and I then receive an error message: "ERROR PNG encoding error: Zero width not allowed". Another user posted about encountering this error message, but I don't think I'm making the same mistake they did, which was pasting the ./dezoomify-rs code into the prompt for URL.

What am I doing wrong?

**Comment by lovasoa** [comment]
It looks like you just copy-pasted the URL from my message on without following the instructions before :slightly_smiling_face: 

The message says: 

> 1. First you have to find out the tile URLs template. We have [a tutorial dedicated to that](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial)

**Comment by lovasoa** [comment]
In your case, you can follow the instructions, and find the actual url pattern in your case to be

`https://viewerd.kbr.be/display/B/0/7/7/7/1/2/5/0000-00-00_00/zoomtiles/BE-KBR00_B-10777125_0000-00-00_00_0001/4-{{X}}-{{Y}}.jpg`

![image](https://user-images.githubusercontent.com/552629/200132310-a61ce6b5-2380-4ab1-ad8c-968ca0396e44.png)

**Comment by lovasoa** [comment]
![vrbane pontifex sanctissime](https://user-images.githubusercontent.com/552629/200132823-ea00fb32-f984-49f1-bce0-d467e9d20fe4.jpg)

**Comment by CloisteredMetaphysician** [comment]
Hi, thanks for your reply!

 My edits to my original post reflective that I may've preemptively posted, but my most recent edit followed your instructions with finding the URL. After some trial and error, I found success after removing the auto-italicization the Mac applied to my quotation marks. Not sure why this seemed to be the solution, but it worked!

**Comment by lovasoa** [comment]
Oh, yes, I didn't realize that was the error. If you prepare your command in a text processor, it may replace `"` characters with `”`, which is not a valid quotation character for the terminal.
