### ISSUE TITLE
Would you add SecondCanvas- gigapixel?

### ISSUE THREAD

**Issue by MrChrisWin** [lovasoa/dezoomify-rs#19]
I'm trying to download from https://www.museothyssen.org/en/collection/artists/caravaggio-michelangelo-merisi/saint-catherine-alexandria. The page uses SecondCanvas technology which appears to have a demo at https://github.com/gdmec07131005/SecondCanvasDemo/tree/master/SecondCanvasDemo/SecondCanvasDemo.
Is it possible to add this to dezoomify?
Thank you.

**Comment by lovasoa** [comment]
You don't need dezoomify or any similar tool to download these images. They are not tiled, the full image is present on the page. Just right-click on the image while pressing shift on the viewer page, and click *Save Image As*.

In your example above, the URL of the image is : 

https://imagenes.museothyssen.org/sites/default/files/imagen/2019-09/CARAVAGGIO_Santa%20Catalina%20de%20Alejandr%C3%ADa_81%20%281934.37%29_FOTOH_%23DespuesRest.jpg

**Comment by MrChrisWin** [comment]
Yes they do have an option to download low-res image. But they also have shown the View Gigapixel image which has a json [https://sc4hvcfl151058502cff46683.s3.amazonaws.com/web/index.html?js=4w936q913z0t2j229091702054fe1f1/a4ahhg1810349924254069d_en.json](url). It seems to have infinite zoom.

**Comment by lovasoa** [comment]
Oh, I see, sorry for closing this too fast.

**Comment by lovasoa** [comment]
Looking at the tile URLs, it must be possible to just use the generic dezoomer.

**Comment by MrChrisWin** [comment]
the web version returns this for generic dezoomer:
Error
Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://sc4hvcfl151058502cff46683.s3.amazonaws.com/web/index.html?js=4w936q913z0t2j229091702054fe1f1/a4ahhg1810349924254069d_en.json

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:191)
You should read our Frequently Asked Questions, and, if you think this is an issue with dezoomify itself, report a bug on the bugtracker.

**Comment by MrChrisWin** [comment]
Interestingly, under Inspect in Chrome it shows various director. When I zoom in more, it generates more jpg files. 
![Capture](https://user-images.githubusercontent.com/59969833/72749392-f24d5700-3b87-11ea-9f90-4169b4485169.PNG)

**Comment by lovasoa** [comment]
You can read [our documentation about how to use the generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial).

Here is an example, for the 5th zoom level of your image: `https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://sc4hvcfl151058502cff46683.s3.amazonaws.com/gigapixel/Thyssen_SantaCatalinaDeAlejandria_Caravaggio/img_Thyssen_SantaCatalinaDeAlejandria_Caravaggio_5_{{X}}_{{Y}}.jpg`

**Comment by MrChrisWin** [comment]
OK I'll give it a try.

**Comment by lovasoa** [comment]
I downloaded the 7th zoom level with dezoomify-rs : 

```sh
dezoomify-rs --retries 2 --retry-delay 5s "https://sc4hvcfl151058502cff46683.s3.amazonaws.com/gigapixel/Thyssen_SantaCatalinaDeAlejandria_Caravaggio/img_Thyssen_SantaCatalinaDeAlejandria_Caravaggio_7_{{X}}_{{Y}}.jpg"
```

And I uploaded it to wikimedia: http://commons.wikimedia.org/wiki/File:Saint_Catherine_of_Alexandria_(Caravaggio).jpg

**Comment by MrChrisWin** [comment]
Thank you.

**Comment by lovasoa** [comment]
Thank you for opening this : we have identified the zoomable format behind this image and are going to add support for it. We are consolidating all reports about this format to https://github.com/lovasoa/dezoomify/issues/808
