### ISSUE TITLE
Specify a different filename for tiles.yaml

### ISSUE THREAD

**Issue by hstarcm** [lovasoa/dezoomify-rs#196]
Version: 2.9.4

If I specify a different tiles.yaml filename eg tiles_website_abc.yaml, dezoomify-rs will fail.
`dezoomify-rs.exe tiles_website_abc.yaml`

but once i rename tiles_website_abc.yaml as tiles.yaml, dezoomify-rs will start to download. 
`dezoomify-rs.exe tiles.yaml`

can I specify a different filename for tiles.yaml as I want to use dezoomify-rs simultaneously in multiple CMD windows and also to keep a copy of tiles_website_abc.yaml

**Comment by lovasoa** [comment]
The files just have to *end in*  `tiles.yaml`. You can call your file `website_abc.tiles.yaml`

**Comment by hstarcm** [comment]
Hi,

The solution is good enough for me. Thanks!
