### ISSUE TITLE
Thanks and question

### ISSUE THREAD

**Issue by sabbia001** [lovasoa/dezoomify-rs#2]
Thank you very much for your prototype!
I've tried on Ubuntu, but I can't open the file (is not executable).
So I'm trying on Windows 10, but I get a message like this (I tried with a brand new tiles.yaml and with your template)

"Invalid YAML configuration file: missing field `headers` at line 2 column 13"

Thank you!

**Comment by lovasoa** [comment]
The error message should be fixed in the latest version (by 03c86e7cfcc73042685772839c56ae69346566b0).

Can you give a little more details on the error you got in ubuntu ? You can make a file executable by running in a terminal : 

```sh
chmod +x /path/to/file
```

**Comment by lovasoa** [comment]
Feel free to reopen the issue if needed
