### ISSUE TITLE
[GoogleArts&Culture] Use title as output filename

### ISSUE THREAD

**Issue by skyme5** [lovasoa/dezoomify-rs#20]
- Current behaviour is to save the output image as "**dezoomified**.jpg". 
- Would it be possible to change this behaviour to use the painting name as the output name for _Google Arts & Culture_?

**Comment by lovasoa** [comment]
Yes, it is very much possible! Would you be interested in making this change yourself? I can provide guidance and help!

**Comment by skyme5** [comment]
Sure, I will be happy to _contribute_. I will open a **PR** when it is ready.

**Comment by lovasoa** [comment]
> Sure, I will be happy to _contribute_. I will open a **PR** when it is ready.

Great 👍 Do not hesitate to ask for help. We do already have access to the image name for google arts and culture in the Debug implementation for the zoomlevel : 

https://github.com/lovasoa/dezoomify-rs/blob/master/src/google_arts_and_culture/mod.rs#L99

I think we should change the outfile argument to be an `Option<PathBuf>` : 

https://github.com/lovasoa/dezoomify-rs/blob/master/src/arguments.rs#L15-L17

And use the image name only when the argument is not provided.

Also, we'll have to be careful that there are some characters that cannot appear in file names.

**Comment by lovasoa** [comment]
Do you need help ? The image saving happens here : 

https://github.com/lovasoa/dezoomify-rs/blob/master/src/main.rs#L236-L243

You may want to refactor this into its own function.
