### ISSUE TITLE
Problem with https://collection.barnesfoundation.org

### ISSUE THREAD

**Issue by jeanchartier** [lovasoa/dezoomify-rs#205]
Hello, I can't extract the images from the site https://collection.barnesfoundation.org
The dezoomify extension manages to find an address in .json, but dezoomify-rs only displays error messages. Does anyone have an explanation? THANKS

**Comment by lovasoa** [comment]
Can you have a look at previous discussions about this site ?

https://github.com/lovasoa/dezoomify/issues/417#issuecomment-748219730

**Comment by jeanchartier** [comment]
It looks complicated, but thank you!

**Comment by jeanchartier** [comment]
I succeeded, thank you!
