### ISSUE TITLE
Problem with the site https://www.artic.edu/collection

### ISSUE THREAD

**Issue by jeanchartier** [lovasoa/dezoomify-rs#206]
I have a problem with the site https://www.artic.edu/collection
Dezoomify works for a very short time, after which the site crashes. It is therefore possible to download the small images by waiting 15 minutes between each download, but the larger images are not recomposed to the end. Does anyone have a solution? THANKS !

**Comment by jeanchartier** [comment]
For example: this one : 
https://www.artic.edu/artworks/14655/two-sisters-on-the-terrace

**Comment by lovasoa** [comment]
Do you mean that dezoomify makes the site crash by making too many requests ?

dezoomify-rs has multiple command-line options with which you can play to prevent that

```
    -n, --parallelism <parallelism>
            Degree of parallelism to use. At most this number of tiles will be downloaded at the same time [default: 16]


    -r, --retries <retries>
            Number of new attempts to make when a tile load fails before giving up. Setting this to 0 is useful to speed
            up the generic dezoomer, which relies on failed tile loads to detect the dimensions of the image. On the
            contrary, if a server is not reliable, set this value to a higher number [default: 1]
        --retry-delay <retry-delay>
            Amount of time to wait before retrying a request that failed. Applies only to the first retry. Subsequent
            retries follow an exponential backoff strategy: each one is twice as long as the previous one [default: 2s]
```

you can try `--parallelism 2 --retry-delay 10s`

**Comment by jeanchartier** [comment]
Thank you for your advice. How should I enter these commands in the terminal, after the address name? My first attempt indicate a syntax error.

**Comment by jeanchartier** [comment]
Hello, I now understand the syntax of the -n and -r commands. On the other hand, the site continues to crash after 15/20 seconds, even with --parallelism 1 --retry-delay 20s. Do you have an idea ? THANKS !

**Comment by lovasoa** [comment]
Is it really the site that crashes? How do you see that? Have you tried even longer retry delays?

**Comment by jeanchartier** [comment]
When the download starts showing errors, the site shows an error message if I refresh it. I tried with a longer delay.

**Comment by lovasoa** [comment]
It doesn't seem like a crash, more like a ban. It looks like you are banned for 5 minutes when you start making too many requests. I put a retry delay of 10 minutes to be safe, and it seems to be working so far :

```
dezoomify-rs --tile-cache /tmp/two_sisters_tiles --parallelism 1 --retries 15 --retry-delay 600s
```

I also used the `--tile-cache` argument to avoid having to restart from scratch after failed attempts. It saves the tiles it downloads to the folder you specify, and reuses the ones that were successfully downloaded in previous attempts.

**Comment by lovasoa** [comment]
I uploaded the full image to wikimedia: https://commons.wikimedia.org/wiki/File:Les_Deux_S%C5%93urs_ou_Sur_la_Terrasse.jpg

[![sisters](https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Les_Deux_S%C5%93urs_ou_Sur_la_Terrasse.jpg/619px-Les_Deux_S%C5%93urs_ou_Sur_la_Terrasse.jpg)](https://commons.wikimedia.org/wiki/File:Les_Deux_S%C5%93urs_ou_Sur_la_Terrasse.jpg)

**Comment by jeanchartier** [comment]
That's great, thanks again for your help!

**Comment by lovasoa** [comment]
I am publishing a new version of dezoomify-rs, v2.11.0, which adds a new command-line argument: `--min-interval`.

`--min-interval` allows setting a minimum delay between consecutive tile requests, making it easier for the remote server to handle, and thus preventing getting banned or crashing the remote server.

It is still compatible with the existing arguments, such as `--retry-delay` so you can for instance lower the risk of getting banned and still handle the ban gracefully. But you don't need to reduce the parallelism anymore.

```sh
dezoomify-rs --tile-cache /tmp/two_sisters_tiles --retries 15 --retry-delay 600s --min-interval 1s https://www.artic.edu/iiif/2/3a608f55-d76e-fa96-d0b1-0789fbc48f1e/info.json two_sisters_by_renoir.png
```
