### ISSUE TITLE
How to Batch download

### ISSUE THREAD

**Issue by seane4422** [lovasoa/dezoomify-rs#208]
Hi I'm having an issue batch downloading, I was amazed to see the first result googling this was someone trying to downloading the exact same thing i am 'The book of kells' i'm on a mac here, im trying to get the full rez versions,  i tried the code you suggested in the original post and could not get it to work, any help appreciated, https://digitalcollections.tcd.ie/concern/works/hm50tr726

**Comment by lovasoa** [comment]
Duplicate of #17

**Comment by lovasoa** [comment]
I'm closing this to centralize discussion about batching in #17
