### ISSUE TITLE
no dezoomify-rs file on mac zip

### ISSUE THREAD

**Issue by rotemgrid** [lovasoa/dezoomify-rs#211]
there is no no dezoomify-rs file on mac zip
what am i missing?

**Comment by SBenoit5** [comment]
Use this one : https://dezoomify-rs.ophir.dev/

**Comment by lovasoa** [comment]
[dezoomify-rs-macos.tgz](https://github.com/lovasoa/dezoomify-rs/releases), after decompression, contains an executable file called `dezoomify-rs`. 

![image](https://github.com/lovasoa/dezoomify-rs/assets/552629/b9b10515-0594-4668-8b3f-fdecca55a8c8)
