### ISSUE TITLE
Birmingham Museum and Art Gallery

### ISSUE THREAD

**Issue by jeanchartier** [lovasoa/dezoomify-rs#212]
On the website https://dams.birminghammuseums.org.uk, images are available for download, but they are always imported in sizes smaller than those indicated on the site. For example, on the :

https://dams.birminghammuseums.org.uk/asset-bank/action/viewAsset?id=4089&index=17&total=27&view=viewSearchItem

The advertised size is 9805 x 5865 pixels, but the downloaded file is only 3999 × 2392 pixels.
Do you have a solution for recovering the maximum file size? Thanks for your help!

**Comment by lovasoa** [comment]
This does not look like a zoomable image; dezoomify is not what you need here
