### ISSUE TITLE
archives.lamayenne.fr

### ISSUE THREAD

**Issue by Ayack** [lovasoa/dezoomify-rs#215]
Hello, 

I'm trying to download this image : https://archives.lamayenne.fr/archives-en-ligne/ark:/37963/r144738zwrvr0k/f1?context=ead::FRAD053_005FI_RM_de-3941

Having viewed @agmmnn [reply](https://github.com/lovasoa/dezoomify/issues/701) for the same website, I tried [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) with: `https://archives.lamayenne.fr/archives-en-ligne/iiif/ark:/37963/r144738zwrvr0k/f1/info.json --header "Referer: https://archives.lamayenne.fr/"` but I keep getting `ERROR Could not get any tile for the image. See https://dezoomify-rs.ophir.dev/no-tile-error` and none of the proposed solutions are working.

Could you please tell me what I'm doing wrong?

Thanks.

**Comment by lovasoa** [comment]
Fixed in the latest version.

![dezoomified_0007](https://github.com/lovasoa/dezoomify-rs/assets/552629/663f7d11-4ca6-4834-84a3-e0e3b2b4f923)
