### ISSUE TITLE
uline.com

### ISSUE THREAD

**Issue by PlanetXtreme** [lovasoa/dezoomify-rs#219]
https://www.uline.com/Product/Detail/H-4567/Shopping-Baskets-and-Carts/Convenience-Cart-2-Basket?pricode=WA9733&gadtype=pla&id=H-4567&gclid=Cj0KCQjwtJKqBhCaARIsAN_yS_lzyCbt2F5XbRkXNqRcyldJ06OP1LUKIM5x0Ym7YkP9ku5ImjGpS-kaAuhWEALw_wcB

There's probably a lot like this but this was pretty relavent. They're stored as 256X256 files under img.uline.com, is/image/uline.

**Comment by lovasoa** [comment]
You don't need dezoomify for this; you can download the full images directly from their server.

https://img.uline.com/is/image/uline/H-4567?id=7m-qw0&scl=2&req=tile&rect=0,0,1000,1000&fmt=jpg

![](https://img.uline.com/is/image/uline/H-4567?id=7m-qw0&scl=2&req=tile&rect=0,0,1000,1000&fmt=jpg)

**Comment by PlanetXtreme** [comment]
Hello,
I did notice they had some jpeg files on their server. But the one you linked is not the same quality as what you get when zooming all the way in. But thanks for your assistance, you made a pretty cool tool.
![Ex1](https://github.com/lovasoa/dezoomify-rs/assets/57045482/58d28ba2-44d7-4b8f-bbbb-7c939b00cc9e)

![Ex2](https://github.com/lovasoa/dezoomify-rs/assets/57045482/24ced8c2-fbb1-4c09-a15f-94a0ddbde1c6)
