### ISSUE TITLE
Dezoomify for Micr.io

### ISSUE THREAD

**Issue by cxyfreedom** [lovasoa/dezoomify-rs#221]
I want to download the image [https://i.micr.io/rvFps/the-waterworks-of-money-jpg](https://i.micr.io/rvFps/the-waterworks-of-money-jpg) from micro.io. The image info is: [https://i.micr.io/rvFps/info.json](https://i.micr.io/rvFps/info.json)

OS: MacOS Ventura

I execute the command as follow:

```shell
./dezoomify-rs --header "Referer: https://i.micr.io" --parallelism 1 --retries 5 --retry-delay 5s --logging debug --timeout 120s -d iiif https://i.micr.io/rvFps/info.json
```

Then return the error as. follow:

```shell
WARN  dezoomify_rs::network] invalid image error: The image format could not be determined.
```

Is it support? Thanks

**Comment by lovasoa** [comment]
micr.io does not have a valid iiif server, but you can use the simple generic dezoomer:

```
dezoomify-rs 'https://b.micr.io/rvFps/0/{{X}}-{{Y}}.jpg'
```

![dezoomified](https://github.com/lovasoa/dezoomify-rs/assets/552629/a74854c1-e801-4408-bd28-70d09efa4313)
