### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by autur** [lovasoa/dezoomify-rs#23]
Hello @lovasoa. I have a few minor suggestions for improving dezoomify:

 - [x] 1. I often batch download images with the same name and have to manually rename them before downloading. It would be easier if dezoomify was programmed to automatically rename images to avoid overwriting existing ones: E.g. if "dezoomify.jpg" already exists, then "dezoomify (1).jpg" (I don't actually use these names, just to demonstrate).
 - [x] 2. Make is easier to identify "image not saved" fatal errors in the output, so that users can find them and try again. (This is a problem for me when downloading 50+ images, and inspecting the output for errors). If possible, I would color code the errors RED, or add some salient text to make the errors stand out like: !!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!
 - [x] 3. When users launch dezoomify.exe (not CMD) and provide a bad URL, the program immediately exits. It would be better if dezoomify stayed open so that the user can read the error, check the URL that was typed, and try again.

The new dezoomify works great, by the way :)

**Comment by lovasoa** [comment]
Hello and thank you for the suggestions. Number 1 is already implemented in the latest version. Try it!

**Comment by autur** [comment]
Thank you :) Didn't realize it was updated 10 days ago.

**Comment by MrChrisWin** [comment]
Is there a way to download from this site, [halftadefinizione] ?(https://www.haltadefinizione.com/en/image-bank/leonardo-da-vinci-annunciazione-1472-1475/)

I tried to use Chrome Inspect but no luck to ascertain source file.

**Comment by autur** [comment]
You can find the source in Network Activity - All (Chrome browser). Look for file.dzi
https://jarvis.haltadefinizione.com/images/dzi/db/813c03cf-7399-4360-a93d-da51bd11597c/file.dzi

However, the watermark... Omg, if other websites start using watermarks, we're all screwed 😂😭

**Comment by MrChrisWin** [comment]
Hmm, I thought the logo was SVG file inserted on top of it. Crossing my finger. Will see.

**Comment by MrChrisWin** [comment]
lol. Wow it did add the watermark. Crazy!!!

**Comment by autur** [comment]
Also, check the json file: https://jarvis.haltadefinizione.com/meta/images/search/findByUuid?uuid=813c03cf-7399-4360-a93d-da51bd11597c

There are other links available, including one IIIF link to a 800px jpg: 
https://jarvis.haltadefinizione.com/images/iiif/db/813c03cf-7399-4360-a93d-da51bd11597c/full/800,/0/default.jpg
You can alter it to get the full jpg (replacing "800," with "full"), but this file too has the watermark. 

I conclude from this that all of the public images stored on their servers have the watermark to begin with, and it's not being added during the zooming. So unfortunately, we don't have access to the original ones. 😔 
Maybe @lovasoa can weigh in if I'm wrong.

**Comment by lovasoa** [comment]
Let's try to keep one issue per thread.

**Comment by MrChrisWin** [comment]
**Could an option be added to allow user to specify output file type after the tiles have been downloaded?**
Currently user specifies output file type from command line or if left blank will default to jpg. 
However, in case the specified file type results in encoding error due to exceeding jpg max resolution then user would have to download the tiles again and specify new file type.

For instance I would love to see this option implemented 

After all tiles have finished, user will choose from menu 
1. JPG 
2. TIFF
3. PNG
4. whatever other format supported
5. EXIT

if user selected 1, user can enter a file name or leave blank to default. After JPG is created, provide user with same set of option above to output to another format or to Exit.

By having this option, it will help tremendously to save bandwidth for users who have download limit from their Internet Service Provider.

Thank you.

**Comment by lovasoa** [comment]
What you are describing is indeed a problem, but I think a better solution would be to cache image tiles, deleting the cache only when the final result has been saved. This is a more general solution, and it would allow resuming a download that was previously interrupted, for instance.

**Comment by autur** [comment]
> Hello and thank you for the suggestions. Number 1 is already implemented in the latest version. Try it!

Hey, I was too quick to assume this issue was resolved because I let dezoomify name the files. Upon further testing, the only time it renames files is when no filename is specified. When the file name is specified, it still overwrites, e.g. if I download several images of the same artwork and they're all given a name like "1910 Artwork.jpg" then dezoomify overwrites each one. So the solution I was hoping for is for dezoomify to add a unique identifier whenever it detects another file of the same name.

**Comment by lovasoa** [comment]
Hello,
  I'm not sure it's a good idea to save the image under a different name than the one explicitly provided by the user. When the program creates a filename itself, it's his responsibility to make sure it does not clash with an existing file. When the user provides a filename, we can assume the image should be saved under this exact name. If you are scripting dezoomify to download several images why don't you add an identifier in the output image name ?

**Comment by MrChrisWin** [comment]
does anyone know how to grab the hi-res image from this link? Thank you. They use seadragon as far as I can tell https://www.insidebruegel.net/#p/v=udroom&lan=en&a=1016

**Comment by autur** [comment]
> Hello,
> I'm not sure it's a good idea to save the image under a different name than the one explicitly provided by the user. When the program creates a filename itself, it's his responsibility to make sure it does not clash with an existing file. When the user provides a filename, we can assume the image should be saved under this exact name. If you are scripting dezoomify to download several images why don't you add an identifier in the output image name ?

Basically my workflow is to scrape some website, retrieve the year and title of the artworks, and then use "year-title.jpg" as the output name. A lot of the times there are several copies of the same artwork or artworks with the same title (especially "untitled"). Finding the duplicates and adding the unique identifiers is an additional time-consuming step I was hoping to avoid in the future. I do see your point that if the user gives it a certain name then it must be intentional, but my point is that the users (like me) are not always aware of duplicates when downloading many images and may not want to overwrite existing files by default. The default behavior in Windows, for instance, is to ask you if you want to replace a file or rename it to avoid conflict. Maybe there can be a compromise with dezoomify such as an argument to overwrite (-o) or alternatively to rename (-rn) if duplicates are found.

**Comment by lovasoa** [comment]
I think the easiest for you is just to add a hash of the URL to the output file name. Naming the files with only the year and the title is not a good idea if this information is not unique. 

Your code should look something like :

```
dezoomify-rs "$url" "$year-$title-$(md5 $url).jpg"
```

**Comment by autur** [comment]
My current solution is to use R program to find duplicates and add _1, _2, _3, etc. I like to keep the names as clean as possible, so adding the hash is not an attractive option for me. I just hoped we might eventually have an argument in dezoomify to let the user decide whether he wants the files overwritten or renamed. Anyways, it's just a minor annoyance.

**Comment by lovasoa** [comment]
Suggestion number 1 and 3 are now implemented. I'm thinking about number 2 now. Be ready for a new release very soon ⌛️

**Comment by lovasoa** [comment]
v1.8.5 has all of the suggestions implemented
