### ISSUE TITLE
Not working on google arts and culture story

### ISSUE THREAD

**Issue by Roxcsas** [lovasoa/dezoomify-rs#236]
I tried to download the 360 panorama from https://artsandculture.google.com/story/oQURDM2pcsofJg but it just find one image with 4 different resolutions and if i try to download it i get this error for almost all the tiles:
` WARN  dezoomify_rs::network] network error: HTTP status client error (403 Forbidden) for url ...`

**Comment by MrChrisWin** [comment]
dezoomify-rs is not intended for downloading 360 panorama b/c that use an entirely different technology. dezoomify is only for multi-zoom single image.
