### ISSUE TITLE
Failure to download  a big Arts & Culture image, failure to install  dezoomify-rs.exe  

### ISSUE THREAD

**Issue by Nicolloid** [lovasoa/dezoomify-rs#237]
During the last three days, I tried to download an Arts & Culture image  (https://artsandculture.google.com/asset/twGyqq52R-lYpA). Any attempts and all Dezoomify adons for Chrome/SRWareIron, or Firefox turned out to be futile: having loaded, the tiles either arrange and fully show the undownloadable image (Firefox Save button inactive)or fail to load (all other browsers, including the latest TOR, simply crash).  Attempts to use a proxy through the browser console (or instead of proxy.php. http://127.0.0.1:8181/)gave the same result: 
proxy not found. Finally, my notebook (32-bit Windows 7) rejects installation of any dezoomify-rs.exe - I have tried a dozen of various releases, starting from v1.5.4 to the newest versions (Windows keeps saying that the file version is x64 which is not compatible with the installed system). Probably I did not try all possible solutions, but I thought  faster would be making screenshots of individual tiles and stitching them manually. Unfortunately, the size of the original painting is 3m x 2m!

**Comment by lovasoa** [comment]
What do you mean by "fails to install" ? There is no installer. Can you provide detailed error messages and screenshots?

**Comment by Nicolloid** [comment]
Please find enclosed the error message screenshot (translated). The same
response appeared following my attempts to execute any of the downloaded
.exe files shown here. This clicking  action was mentioned by me as
"installation". I guess, erroneously. If there is another, more correct way
to use the executable files in Windows, please advise.

вт, 9 апр. 2024 г. в 09:46, Ophir LOJKINE ***@***.***>:

**Comment by lovasoa** [comment]
Email attachments don't show up on github, you need to post directly from the github website: https://github.com/lovasoa/dezoomify-rs/issues/237

**Comment by lovasoa** [comment]
Did you solve your issue? If so, can you post the solution to help others who may have the same problem?

**Comment by Nicolloid** [comment]
Dear experts,
Please excuse my delayed (due to personal reasons) response.
I am mailing again the error screenshot.

My problem with the required image file download was solved alternatively, bypassing the use of dezoomify-rs.
However, the problem of running the latter on my 32-bit Windows 7 remains, , and this is what my Windows-7 tells following each attempt to execute dezoomify-rs.exe: 
"The file version (%1) is not compatible with the OS Windows  in use. Check up the system data, in order to know which version of the software you need - x86 (32-bit) or x64 (64-bit), and obtain it from  the program designer. Can not execute dezoomify-rs.exe".

Today I have checked the "Run this program in compatibility mode for" box, and opened the drop-down list. 
If the list starts with Windows Vista, then the application you selected is a 64-bit application. If the list starts with Windows 95, then the application you selected is a 32-bit application.
(the statement by https://www.digitalcitizen.life/3-ways-learn-whether-windows-program-64-bit-or-32-bit/). 
In my case, all eleven dezoomify-rs.exe files I  downloaded (including those packed in x86-marked zips - dezoomify-rs-v1.5.4-x86_64-pc-windows-gnu.zip, dezoomify-rs-v1.5.4-x86_64-pc-windows-gnu.zip)always had their lists started with Windows Vista)

Besides, the failure to run is neither connected with the Java version installed on my laptop.
SO, CAN ANYONE EXPLAIN HOW DO I RUN DEZOOMIFY-RS ON WINDOWS OS x86?

Special thanks for the video reference you mentioned, but it is of no help for me, since it relates to Windows 10.
![Windows notification](https://github.com/lovasoa/dezoomify-rs/assets/166461972/88cacf71-1b11-4ded-990d-ab7bf083f307)

**Comment by lovasoa** [comment]
Hello! Indeed, we do not distribute a 32bit version of dezoomify-rs. It would be possible to create such a version, but I think there wouldn't be a lot of demand for it since almost all computers sold in the last ~10 years are 64bits. Don't you have access to a 64bit computer? 

If you are motivated, it's always possible to recompile dezoomify-rs for windows 32 bits yourself, of course.
