### ISSUE TITLE
CAN ANYONE EXPLAIN HOW DO I RUN DEZOOMIFY-RS ON WINDOWS OS x86?

### ISSUE THREAD

**Issue by Nicolloid** [lovasoa/dezoomify-rs#239]

**Comment by lovasoa** [comment]
Please avoid opening multiple issues for the same problem. 

I'm closing this as a duplicate of https://github.com/lovasoa/dezoomify-rs/issues/237

I asked you a question over there, you will need to provide details about your issue, not just a single sentence in all caps. 

Спасибо.

**Comment by lovasoa** [comment]
And if anyone stumbles on this, there is an example on youtube, for "the barnes collection": https://www.youtube.com/watch?v=tld7w32KqqI
