### ISSUE TITLE
RibaPix?

### ISSUE THREAD

**Issue by RadarEugene1976** [lovasoa/dezoomify-rs#240]
I've tried using the meta information files, extension, etc. Not having much luck. 

https://www.ribapix.com/Roofscape-Whitby-North-Yorkshire_RIBA5710

Thank you in advance for your help!

**Comment by lovasoa** [comment]
The images are not tiled, they are available on the server directly: https://www.ribapix.com/images/thumbs/036/0369448_RIBA5710.jpeg

**Comment by RadarEugene1976** [comment]
> The images are not tiled, they are available on the server directly: https://www.ribapix.com/images/thumbs/036/0369448_RIBA5710.jpeg

But those are not the high resolution images, just thumbs. Is it possible to get the higher res ones using dezoomify?

**Comment by lovasoa** [comment]
No these are the only resolution available
