### ISSUE TITLE
Um am I doing something wrong? 

### ISSUE THREAD

**Issue by Yummy44** [lovasoa/dezoomify-rs#25]
Hi there, when I'm using dezoomify-rs and I've pasted a link to google arts etc, it will give me the option to download a size as normal, and will proceed to download etc. 

However, once downloaded it suddenly closes. Am I missing something? As there seems to be no indication what directory the image file is saved in? Should it appear in the root directory that dezoomify-rs is in?

**Comment by MrChrisWin** [comment]
You have to use it in DOS command prompt. Then CD into the directory you have dezoomify RS. You then can use it now and it won't close .

**Comment by lovasoa** [comment]
I'll close this issue because it's still tracked in #23, but you can still comment here.
There are plans to make dezoomify start an infinite loop when it is started without arguments. After downloading a first image, it would ask for the URL of a new image instead of exiting.
