### ISSUE TITLE
Hathitrust compatability

### ISSUE THREAD

**Issue by qubed** [lovasoa/dezoomify-rs#258]
Hello everyone,

I am having issues when trying to download https://babel.hathitrust.org/cgi/pt?id=gri.ark:/13960/t5t761b44&seq=51

Dezoomify reports:
```
Uncaught Error: Unable to find a proper dezoomer for:
https://babel.hathitrust.org/cgi/pt?id=gri.ark:/13960/t5t761b44&seq=51

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```

Is there a simplified way to download images from hathitrust with dezoomify - Is hathitrust compatible with dezoomification? Cheers!

**Comment by lovasoa** [comment]
You can download directly from their server.

```
https://babel.hathitrust.org/cgi/imgsrv/image?id=gri.ark%3A%2F13960%2Ft5t761b44&seq=51&height=50000
```

![](https://babel.hathitrust.org/cgi/imgsrv/image?id=gri.ark%3A%2F13960%2Ft5t761b44&seq=51&height=50000)
