### ISSUE TITLE
ČÚZK Portal

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-rs#27]
I can't create the info.json or .yaml files for the **zoomable cadastral maps on the ČÚZK Portal**. I provide two examples with different dimensions:
the huge preparatory map of [Katastralgemeinde Landschau](https://www.mza.cz/indikacniskici/index.php#show:MOR121618240) (activate Flash Player to see);
one of the definitive maps of [Katastralgemeinde Schwanenberg](https://archivnimapy.cuzk.cz/uazk/com/com_data/1462-1/1462-1-001_index.html) (for this type of maps, perhaps ČÚZK could be added to the **dezoomify-extension** features, don't?).

In this regard, **@lovasoa**, I offer You my most sincere congratulations for Your genial extension🤗 ... and also _my best wishes for Your health_, given the bad times we live in😰. Take care, please.

**Comment by lovasoa** [comment]
Hello,
  In the first case (the flash page), the format seems to be really custom. I'm not sure it would be worth investing the time to develop a dezoomer for just this case.
  For the second page, the URL format of the tiles is [documented here](https://mapserver.org/cgi/controls.html), you can use this information to create a `tiles.yaml` for your image.  We have a [tutorial](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer) about how to create this yaml file, you can even contribute to it if you want.

**Comment by Arekkusu1998** [comment]
Thanks for Your timely reply, **@lovasoa**. However, I've to ask again 'cause, as You know, my expertise is poor😔.

> For the second page, the URL format of the tiles is documented here, you can use this information to create a tiles.yaml for your image. We have a tutorial about how to create this yaml file, you can even contribute to it if you want.

I've [read about MapServer](https://mapserver.org/cgi/controls.html) carefully and tried to understand how to get the `tiles.yaml` file, but _I really don't understand **anything**_ 😵!! Please, could You not help me as You did with **@rigel71** for the [Milan State Archive](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer)?

**Comment by lovasoa** [comment]
Can you be more precise about what you do not understand in the tiles.yaml format ? I'd rather write a clear explanation once and for all, so that it can serve others too. Your feedback is well appreciated.

**Comment by Arekkusu1998** [comment]
The problem isn't in the `tiles.yaml` format but in how to create that file. The [example](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer) provided concerns an image that uses the IIP image server that supports the IIIF protocol, while here we've **MapServer**. 
For example, a tile has a link address: https://archivnimapy.cuzk.cz/cgi-bin/mapserv.exe?mode=map&map=d%3A%2Fconfms%2Fcom%2Fcom_data%2F1462-1%2F1462-1-001_ol.map&map_imagetype=png24&mapext=2656.25+-4062.5+2812.5+-3906.25&imgext=2656.25+-4062.5+2812.5+-3906.25&map_size=256+256&imgx=128&imgy=128&imgxy=256+256
For a dummy like me, this is just a bunch of mysterious data and numbers.
It isn't intuitive to understand how to manipulate the links obtained from the analysis of the image _when faced with an unknown format_ (such as MapServer), so I don't know if it will be possible to create a _universal_ tutorial that _**anyone**_ can understand.

**Comment by lovasoa** [comment]
The yaml dezoomer allows you to dezoom images that are in a custom format. To use it, you have to study yourself the pattern of the URLs of the tiles that compose your image. So, you have to take the URL of a tile, and using the documentation, and trial and error, try to understand what each part of it means. At first, it looks like a bunch of mysterious data and numbers, but when you look at all the tile URLs, you'll see that that largest part of the URL is common to all tiles, and only small parts (a few numbers) change from tile to tile. Your first goal is to identify these parts.

When you have identified these parts, you have to try and understand which part is responsible for what. For that, you can use the documentation you found, and simple trial and error: try altering the numbers in the URL yourself, and see what changes in the image.

 The goal is to find one number in the URL such that when you change it, another tile appears with the same y-coordinate in the image, the same zoom level, but a different x coordinate. Then find a second number such that when you change it, a tile appears with  same x-coordinate in the image, the same zoom level, but a different y coordinate. 

Once you identified these two numbers in the URL, replace them with `{{x}}` and `{{y}]}`.

The yaml dezoomer works by generating all the possible values of X and Y between the bounds you gave. So you have to determine a minimal value, a maximal value, and a step. The minimal value is the smallest value you can put in the URL without getting an error, the maximal value is the largest, and the step is the size of your tiles: if tiles are 256x256, then you'll want dezoomify-rs to generate x values of 0, 256, 512, etc, so the step between successive values of X and Y are the width and height of tiles.

Finally, create the yaml file with the information you gathered : 

```yaml
url_template: "http://...{{x}}...{{y}}..."

variables:
  - name: x
    from: 0 # Minimal value by which you can replace {{x}} in the url without getting an error, usually 0
    to: 6824 # Maximal value by which you can replace {{x}} in the url without getting an error
    step: 256 # The width of a tile

  - name: y
    from: 0 # Minimal value by which you can replace {{y}} in the url without getting an error, usually 0
    to: 17025 # Maximal value by which you can replace {{y}} in the url without getting an error
    step: 256 # The height of a tile (usually the same as the width)
```


Let me know if you need more help. If you can get it, you can publish detailed instructions for others in the wiki.

**Comment by lovasoa** [comment]
closed as per https://github.com/lovasoa/dezoomify-extension/issues/31
