### ISSUE TITLE
Extract the binary from the compressed file...

### ISSUE THREAD

**Issue by coldingfish** [lovasoa/dezoomify-rs#30]
Hi, I downloaded Dezoomify-rs for MacOS but can't extract the file for its lack of an extension. What extension should I add in order to extract it?

**Comment by lovasoa** [comment]
The file that you download is not compressed, it is the binary. Apple makes it super difficult to execute unsigned binaries on MacOS, so I made you a small video: https://youtu.be/EL0VSkMgGFQ

**Comment by coldingfish** [comment]
It's solved. Thank you very much.

**Comment by lovasoa** [comment]
Release v1.8.6 now allows downloading the application as a tar archive, that will hopefully make it easier to execute.
