### ISSUE TITLE
Support for Quru/qis image server

### ISSUE THREAD

**Issue by MrChrisWin** [lovasoa/dezoomify-rs#32]
bonhams.com uses quru/qis image server tech https://github.com/quru/qis.

The original page: [https://www.bonhams.com/auctions/25444/lot/63/](url)

Tile image has the form: [https://images1.bonhams.com/image?src=Images%2Flive%2F2019-04%2F25%2F24868924-1-2.jpg&width=3352&height=4912&autosizefit=0&format=jpg&strip=1&stats=0&tile=36%3A64](url)

I tried to feed this into dezoomify-rs but failed: `https://images1.bonhams.com/image?src=Images%2Flive%2F2019-04%2F25%2F24868924-1-2.jpg&width=3352&height=4912&autosizefit=0&format=jpg&strip=1&stats=0&tile={{X}}%3A{{Y}}`

Also tried: `https://images1.bonhams.com/image?src=Images%2Flive%2F2019-04%2F25%2F24868924-1-2.jpg` and it returns a lower resolution image (1966x2880); the full size image would be at 3352x4912. 

Does anyone have a suggestion on what to do? Thank you.

**Comment by lovasoa** [comment]
Hi !
  I think you have a problem with the way you do write links in your comments. If you paste a link, it will be clickable automatically, no need to select it and press "add link". If you want a clickable link with custom text, then write the text, then select it, press add link, and then paste the url. The result should look like : `[your text](https://yoursite.com)`.

**Comment by lovasoa** [comment]
For how to download the image, a quick look at [dezoomify's issues](https://github.com/lovasoa/dezoomify/issues?q=bonhams) leads to https://github.com/lovasoa/dezoomify/issues/123 which explains how to download images from this site. Just replace the part of the URL after `tile=` by `1:1` and you'll get the full high-quality image : 

`https://images1.bonhams.com/image?src=Images%2Flive%2F2019-04%2F25%2F24868924-1-2.jpg&width=3352&height=4912&autosizefit=0&format=jpg&strip=1&stats=0&tile=1:1`

![](https://images1.bonhams.com/image?src=Images%2Flive%2F2019-04%2F25%2F24868924-1-2.jpg&width=3352&height=4912&autosizefit=0&format=jpg&strip=1&stats=0&tile=1:1)

**Comment by MrChrisWin** [comment]
Thank you.
