### ISSUE TITLE
Failing compilation

### ISSUE THREAD

**Issue by technodrome** [lovasoa/dezoomify-rs#34]
Hi and thanks for a wonderful project!

As I am calling dezoomify-rs from a Ruby program and wanted to implement a special program return value if some tiles haven't been downloaded successfully (currently returns `0`), I wanted to try and compile the program myself. However, the compilation fails for `cargo check` with the following errors:

```
error[E0277]: the trait bound `(): std::convert::From<&str>` is not satisfied
   --> src/main.rs:253:33
    |
253 |         "Downloaded all tiles.".into()
    |                                 ^^^^ the trait `std::convert::From<&str>` is not implemented for `()`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<()>` for `&str`

error[E0308]: mismatched types
   --> src/main.rs:263:34
    |
263 |     progress.finish_with_message(&final_msg);
    |                                  ^^^^^^^^^^ expected `str`, found `()`
    |
    = note: expected reference `&str`
               found reference `&()`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `dezoomify-rs`.

```
My environment:
```
rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
```

Thank you kindly for pointing me in the right direction.

**Comment by lovasoa** [comment]
Hello, 
  I cannot reproduce this issue. Did you make any change to the code ?
  The code is compiled with rust 1.42.0 on every commit on macos, windows, and linux, and the compilation works: 
   https://github.com/lovasoa/dezoomify-rs/runs/525952748?check_suite_focus=true

**Comment by lovasoa** [comment]
Can you provide a copy of the exact sequence of commands you use to install rust, clone the code, and compile it ?

**Comment by lovasoa** [comment]
Hmm... I think I guessed your mistake ! Your error message mentions `progress.finish_with_message(&final_msg);` whereas in the real code, it [on line 262](https://github.com/lovasoa/dezoomify-rs/blob/master/src/main.rs#L262). This means you added a line above in the code.

Given what you mention, my guess is that you added something like `success = true;` on line 254.

A statement that ends with a `;` returns `()` in rust, meaning that your code is trying to put `()` into `final_msg`, which should be a string.

Next time, please provide the code you are trying to compile when reporting a compilation error 😉 


And, about your original idea: it sounds like a good idea to me ! Do you want to make a PR ?

**Comment by technodrome** [comment]
Thank you for your hint and sorry about a bit of confusion - I've literally just started with Rust :) 

I do think having return value reflect the actual result of the download operation opens many possibilities. I'd love to implement this but I am just starting with Rust and it would take quite long. If I manage to implement this, I will be sure to open a PR.

**Comment by lovasoa** [comment]
Here is the link to the part of the rust guide about if : https://doc.rust-lang.org/reference/expressions/if-expr.html
What is important and differs from most languages is that if blocks are expressions : 

```rust
let result = if condition { "hello" } else { x = 1; } 
``` 

is not valid, because the if branch has the type `&str` and the else branch has the type `()`

Do not hesitate to submit your PR now even if it's not ready (you can annotate it as Work In Progress), so that we can discuss it.

**Comment by lovasoa** [comment]
I made the change: starting with next release, dezoomify-rs will use a non-zero exit code when only some tiles could be downloaded.

**Comment by technodrome** [comment]
Amazing work, first class suport :)
A big thank you for such attitude!

**Comment by lovasoa** [comment]
Thank you for using the tool and reporting bugs !
