### ISSUE TITLE
National Gallery - Bad request

### ISSUE THREAD

**Issue by kayaksu** [lovasoa/dezoomify-rs#39]
Hi,

The image adress is: https://www.nga.gov/collection/art-object-page.41622.html

I could not download the following file by using the dezoomify-rs. It works when I use the https://ophir.alwaysdata.net/dezoomify site. 

However it gives "ERROR network error: HTTP status client error (400 Bad Request) for url " when I try to use the command line dezoomify-rs. And I want to use the command line dezoomify-rs

I tried:
https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/4/1/6/2/2/41622-primary-0-nativeres.ptif&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number

and

https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/4/1/6/2/2/41622-primary-0-nativeres.ptif

I could not locate the .json file

Could you please help?

**Comment by MrChrisWin** [comment]
try: 
dezoomify-rs   "https://media.nga.gov/iiif/public/objects/4/1/6/2/2/41622-primary-0-nativeres.ptif/info.json"

**Comment by kayaksu** [comment]
> try:
> dezoomify-rs "https://media.nga.gov/iiif/public/objects/4/1/6/2/2/41622-primary-0-nativeres.ptif/info.json"

Thank you!
