### ISSUE TITLE
Precompiled linux binaries are ARM binaries

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#4]
```
$ file ./dezoomify-rs 
./dezoomify-rs: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.7.0, BuildID[sha1]=1ca97108c38f621046310b478aeef9e2d7d5a479, with debug_info, not stripped
```

Provided linux binaries are compiled for `aarch64` (ARM) instead of `x86-64`.

**Comment by lovasoa** [comment]
@eligurevich : This should be fixed now. You can download the correct linux binary from the latest release: https://github.com/lovasoa/dezoomify-rs/releases/latest

**Comment by eligurevich** [comment]
Hello again.
I just downloaded the latest Linux binary and installed it on Ubuntu for
Windows 10. It won't execute the file. I keep getting error "command not
found". I tried "chmod +x dezoomify-rs" and it does not help.

Here is my install sequence:

wget
https://github.com/lovasoa/dezoomify-rs/releases/download/v1.6.1/dezoomify-rs-v1.6.1-x86_64-unknown-linux-gnu.zip
unzip
https://github.com/lovasoa/dezoomify-rs/releases/download/v1.6.1/dezoomify-rs-v1.6.1-x86_64-unknown-linux-gnu.zip
chmod +rwx dezoomify-rs
dezoomify-rs
dezoomify-rs: command not found


Please help. I have been able to use the windows executable just fine, but
I want to use linux.

Thanks
Eli

**Comment by lovasoa** [comment]
Hello, you have to either [prefix the name of the binary with `./`](https://howtoubuntu.org/how-to-execute-a-run-or-bin-file-in-ubuntu) or place the binary in your [path](https://en.wikipedia.org/wiki/PATH_(variable)) (in `/usr/local/bin` for instance)

**Comment by eligurevich** [comment]
Thanks. This worked.
