### ISSUE TITLE
DEZOOMIFY/HTML Help Needed: How can I download the full resolution photo from artsy?

### ISSUE THREAD

**Issue by SeanEatsWorld** [lovasoa/dezoomify-rs#43]
I'm trying to download an image from artsy website for a personal project that I'm working on and they have their high resolution zoom images protected from downloading. I've opened up the view source and tried to find the image source in the HTML but found that they have hidden it pretty well. Can someone help me to see how I can locate the hidden zoom file (high res) that I can download? I tried dezoomify and that doesn't seem to work for me either.

https://www.artsy.net/artwork/jonathan-lasker-scenic-reality

**Comment by lovasoa** [comment]
See #44

**Comment by SeanEatsWorld** [comment]
@lovasoa I actually have a request for a few more photos. I looked at the instructions you sent but not tech-savy enough. Could I request your help with some more by chance? In return I would send you PayPal contribution for your help...

**Comment by lovasoa** [comment]
Hello, 
  If you can pinpoint where the instructions are hard to understand, and exactly what is too technical, maybe I can make them clearer. 
  If you'd rather pay me to download the images for you, you can contact me with a proposition on *contact at ophir dot dev*.

**Comment by SeanEatsWorld** [comment]
ok I sent an email to you
