### ISSUE TITLE
Support for artsy

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#44]
I don't mean to hi-jack this thread but I need some help too. I'm inexperienced and frankly don't know what I'm doing. I don't even know how to properly use this website which is why I'm posting in here. 

I'm trying to download an image from artsy website for a personal project that I'm working on and they have their high resolution zoom images protected from downloading. I've opened up the view source and tried to find the image source in the HTML but found that they have hidden it pretty well. Can someone help me to see how I can locate the hidden zoom file (high res) that I can download? I tried dezoomify and that doesn't seem to work for me either. 

https://www.artsy.net/artwork/jonathan-lasker-scenic-reality

_Originally posted by @SeanEatsWorld in https://github.com/lovasoa/dezoomify-rs/issues/42#issuecomment-628204508_

**Comment by lovasoa** [comment]
Hello and welcome to dezoomify,
  You can open a new thread by creating a [new issue](https://github.com/lovasoa/dezoomify-rs/issues), if you don't want to interrupt an existing conversation. You can use the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) with artsy.

In the case of the image you mention, the template URL to use will be

```
https://d32dm0rphc51dk.cloudfront.net/stQopvPOYqD8Vd-yE9vNTw/dztiles/13/{{X}}_{{Y}}.jpg
```

![dezoomified_1](https://user-images.githubusercontent.com/552629/81859023-f3562a00-9564-11ea-8b64-51b89c7cfef4.jpg)

**Comment by SeanEatsWorld** [comment]
thank you for the quick reply and help, you are very kind.

**Comment by autur** [comment]
@SeanEatsWorld For Artsy images, you don't need dezoomify. You can just change the URL of the image from "large.jpg" to "normalized.jpg" to get the full sized image. Example: 

Original: d32dm0rphc51dk.cloudfront.net/fXtlKxbATxNRvJvuV5vGvg/large.jpg
Modified: d32dm0rphc51dk.cloudfront.net/fXtlKxbATxNRvJvuV5vGvg/normalized.jpg
