### ISSUE TITLE
Unable to parse DZI file with a Byte Order Mark

### ISSUE THREAD

**Issue by macmacleannz** [lovasoa/dezoomify-rs#45]
I am getting the following error using dezoomify-rs
```
ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 1:1 Unexpected characters outside the root element: ﻿
```
Using the same URL I have no problem using Dezoomify on the web

http://www.cartomundi.fr/site/cmfiles/Cartes/SP8/d_Eg-124.jpg/dzc_output.xml

Any clues on what I am doing wrong?

Thanks
Mac

**Comment by lovasoa** [comment]
Hello, and thank you for reporting this. After investigation, I found the origin of the bug. It is in the underlying XML parser library dezoomify-rs uses: https://github.com/RReverser/serde-xml-rs/issues/67

So, this issue will be resolved when https://github.com/RReverser/serde-xml-rs/issues/67 is.

**Comment by lovasoa** [comment]
It looks like the developer of the underlying library is reluctant to fix this bug: https://github.com/netvl/xml-rs/issues/10

**Comment by macmacleannz** [comment]
Thanks for the prompt response! Do I have any other options to undertake multiple downloads? dezoomify-rs has been great for creating batch downloads.

**Comment by lovasoa** [comment]
I can add a workaround for this bug... In the meantime, there is still the node version of dezoomify

**Comment by lovasoa** [comment]
OK, I implemented a workaround for the underlying issue. I'll soon release a new version of dezoomify-rs, and you'll be able to use it with your file.

**Comment by lovasoa** [comment]
You can download the latest build of dezoomify-rs with the fix here: https://github.com/lovasoa/dezoomify-rs/releases/tag/untagged-7390da2b90bad1bc3e9a

**Comment by macmacleannz** [comment]
Fantastic! I get a 404 when clicking on the link.

**Comment by lovasoa** [comment]
Here is the right link : https://github.com/lovasoa/dezoomify-rs/releases/tag/refs%2Fheads%2Fmaster

I didn't realize the release wasn't public.

**Comment by macmacleannz** [comment]
Sorry to be a pain - still getting a 404....

**Comment by macmacleannz** [comment]
Ok got it now. Will let you know it works

**Comment by macmacleannz** [comment]
Perfect - works as expected. Thanks for resolving this bug so promptly!
