### ISSUE TITLE
Problem with DIGitalARhiiv

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-rs#46]
Good morning, **@lovasoa**: I hope You're _fine_ and _safe_ 🤗.
I don't understand how create info.json or .yaml files for the maps on [DIGAR Archiv](https://www.digar.ee/arhiiv/et). F.e., [this one](https://www.digar.ee/viewer/et/nlib-digar:50531/16012).
Honestly, I don't know if this is something more inherent to [dezoomify](https://github.com/lovasoa/dezoomify#dezoomify), [dezoomify-rs](https://github.com/lovasoa/dezoomify-r) or the [dezoomify browser extension](https://github.com/lovasoa/dezoomify-extension/#dezoomify-extension)🤔: I opened the issue here 'cause the images in DIGAR are often very large format.
Thank You in advance.

**Comment by lovasoa** [comment]
You can use the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial), either in dezoomify or dezoomify-rs : 

```
https://www.digar.ee/viewer/slice/16012/21518/9796/0/{{X}}/{{Y}}
```

![dezoomified](https://user-images.githubusercontent.com/552629/82447547-bd56ff80-9aa8-11ea-98c4-ae678b330e58.jpg)
