### ISSUE TITLE
Input/Output Error: Wrong data size 

### ISSUE THREAD

**Issue by macmacleannz** [lovasoa/dezoomify-rs#47]
Using Dev version https://github.com/lovasoa/dezoomify-rs/releases/tag/build-25e9c8d18aa0196c59d5e2050bd6fb3443b9fcd5 processed 100+ images with no problem.

For six or so images get the following error

![image](https://user-images.githubusercontent.com/65611702/82574289-3601ad00-9bca-11ea-9a7f-e207a6c738ec.png)

on the following URL's 

```
dezoomify-rs -l  http://www.cartomundi.fr/site/cmfiles/Cartes/SP8/d_fc1020.jpg/dzc_output.xml Egypt_d_fc1020.png

dezoomify-rs -l  http://www.cartomundi.fr/site/cmfiles/Cartes/SP8/d_fc1021.jpg/dzc_output.xml Egypt_d_fc1021.png

dezoomify-rs -l  http://www.cartomundi.fr/site/cmfiles/Cartes/SP8/d_fc1053.jpg/dzc_output.xml Egypt_d_fc1053.png

dezoomify-rs -l  http://www.cartomundi.fr/site/cmfiles/Cartes/SP8/d_fc1054.jpg/dzc_output.xml Egypt_d_fc1054.png

dezoomify-rs -l  http://www.cartomundi.fr/site/cmfiles/Cartes/SP8/d_fc1055.jpg/dzc_output.xml Egypt_d_fc1055.png
```
I get a corrupted PNG file. It works OK in Dezoomify so I can process manually but am interested in what causes the above error

**Comment by lovasoa** [comment]
Hello, and thank you for testing the beta and reporting bugs. This is highly appreciated. I am going to investigate this.

**Comment by lovasoa** [comment]
Here is the latest pre-release, where this bug is fixed.

**Comment by macmacleannz** [comment]
Perfect! No problem with downloads now.

**Comment by lovasoa** [comment]
Thank you again for reporting this bug early, and preventing it from making it to the final release !
