### ISSUE TITLE
http://boschproject.org support

### ISSUE THREAD

**Issue by gfxhero** [lovasoa/dezoomify-rs#48]
Hi guys, total noob here but I must say the dezoomify chrome extension gave me so much pleasure to download some of my fav artworks grom arts&culture but then I bumped into http://boschproject.org/#/artworks/  which compiles works from another fav artist of mine and I'm kinda stuck. For instance I am trying to download this:
 http://boschproject.org/view.html?pointer=0.786,0.021&i=00MCPVIS 
with the browser extension but actually loads in days...and gives errors, and not the same final output...and don't know how to find the right parameters in order to feed it into the rs desktop version. So please don't mind my message and tell me how can I do this for the works over there. I made a github account just to say thanks for your work and ask for help with this lol.
Goodluck to you all and really nice work you have done! 
Cheers 

P.S. As I would want this to be as lossless as I can, please guide me on how to save in another format as well. Thanks

**Comment by lovasoa** [comment]
Hello,
  You can still use the browser extension with dezoomify-rs. You click the browser extension, and it opens a new tab with a dezoomify and a pre-filled URL in its text field. You copy this URL, and paste it into dezoomify-rs. 
  For instance, for the image you mention, the zoomable image URL found by the browser extension to pass to dezoomify-rs is `http://boschproject.org/dzi/00MCPVIS.dzi`.

**Comment by lovasoa** [comment]
If you want to save the image in a lossless format, you can specify the output file format when you launch dezoomify-rs from the command line like so:

```
dezoomify-rs "http://boschproject.org/dzi/00MCPVIS.dzi" your_image.png
```

(`png` is a lossless image format).

**Comment by lovasoa** [comment]
I downloaded it and published it on wikimedia commons : 

https://commons.wikimedia.org/wiki/File:The_Garden_of_earthly_delights.jpg

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Garden_of_earthly_delights.jpg/1280px-The_Garden_of_earthly_delights.jpg)](https://commons.wikimedia.org/wiki/File:The_Garden_of_earthly_delights.jpg)

**Comment by gfxhero** [comment]
Man, you are amazing. I was able to download the jpeg in zoom level 3 but I was not able to change the format to png. I tried pasting the command line in different forms and I could only get an error. 
Also, it seems that zoom level 0 is out of my RAM so probably I will ask a friend with 64gb to get it for me. 
Thanks again for all your help and sorry for the stupid questions I keep on adding.

![capt1](https://user-images.githubusercontent.com/65922940/83119359-49d07600-a0d8-11ea-8802-beb774e001dc.jpg)
![Untitled-1](https://user-images.githubusercontent.com/65922940/83119362-4a690c80-a0d8-11ea-9bc8-7b94794b05e0.jpg)

**Comment by lovasoa** [comment]
Make sure you are using the latest release of dezoomify, which can download images that do not fit in RAM: https://github.com/lovasoa/dezoomify-rs/releases/latest

In order to choose the image format, you have to launch dezoomify-rs from the command-line. Open cmd.exe on your computer and type `C:\path\where\you\downloaded\dezoomify-rs "http://boschproject.org/dzi/00MCPVIS.dzi" earthly_delights.png`

I don't recommend downloaded the image at zoom level 0. Dezoomify-rs will be able to download it, but no software will be able to open such a large image afterwards, you will end up with an image you cannot use.

**Comment by gfxhero** [comment]
YOU ARE AWESOME! Thank you so much for all your help!
