### ISSUE TITLE
Problems with image assembly

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#49]
Hi.
Since version 1.8.6 I think that the images do not fit well.
Shift the first row and the first column by one pixel.
For example:
dezoomify-rs.exe -r 3 http://www.bl.uk/manuscripts/Proxy.ashx?view=cotton_ms_nero_d_vii_f001r_files/13/{{X}}_{{Y}}.jpg          cotton_ms_nero_d_vii_f001r.jpg

![image](https://user-images.githubusercontent.com/66141658/83302715-1d157f00-a1fc-11ea-889d-0c74470ea49e.png)

By the way, thank you very much for your magnificent work !!!

Bye,

**Comment by lovasoa** [comment]
Additionally, it looks like the server tries to limit the number of requests per second per user, but I could download the full image with : 

```
dezoomify-rs -l --parallelism 1 --retry-delay 5s --retries 10 'http://www.bl.uk/manuscripts/Proxy.ashx?view=cotton_ms_nero_d_vii_f001r.xml' /tmp/output.jpg
```
![output](https://user-images.githubusercontent.com/552629/83305656-72a05a80-a201-11ea-9534-58c330bdb990.jpg)
