### ISSUE TITLE
krpano image format support

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#50]
Good morning from Spain,
I am trying to download the following image:
https://www.mba-lyon.fr/sites/mba/files/gigapixel/monomane/monomane.html

I've come to "detect" an .xml:
https://www.mba-lyon.fr/sites/mba/files/gigapixel/monomane/monomane.xml

But I don't see pharma download it.
I don't know if you can help me, I will understand perfectly well that you don't.
Thanks for your amazing work.

**Comment by lovasoa** [comment]
Hi,
  This zoomable image format (krpano) is supported in dezoomify, but not yet in dezoomify-rs. You can still use the generic dezoomer : 

```
dezoomify-rs --retries 0 --parallelism 1 "https://www.mba-lyon.fr/sites/mba/files/gigapixel/monomane/monomane.tiles/l6/{{Y}}/l6_{{Y}}_{{X}}.jpg"
```

**Comment by lovasoa** [comment]
![envie](https://user-images.githubusercontent.com/552629/83943100-851a2580-a7f9-11ea-9439-f61e5eb6f08d.jpg)

**Comment by CharlyAlonso** [comment]
I discover myself before you !!!!!

**Comment by lovasoa** [comment]
Hey @CharlyAlonso ,
  I added support for krpano in dezoomify-rs. Would you be so kind as to beta-test the new feature before I release it publicly ? The beta version is currently being built, when it is, it will be available on the top of  [the release page](https://github.com/lovasoa/dezoomify-rs/releases), with the identifier `0e884aad1a02cd589c0caba2964452ca5623ca0a`

**Comment by CharlyAlonso** [comment]
Hello

Brilliant brilliant.....

In less than a minute processed the image of the example through the .xml

You are great !!!!!

Thank you very much for everything.
a greeting

**Comment by lovasoa** [comment]
Here is the highest-resolution version, downloaded with the new krpano dezoomer : 

https://commons.wikimedia.org/wiki/File:La_Monomane_de_l%27envie.jpg

[![La monomane de l'envie](https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/La_Monomane_de_l%27envie.jpg/847px-La_Monomane_de_l%27envie.jpg)](https://commons.wikimedia.org/wiki/File:La_Monomane_de_l%27envie.jpg)

**Comment by CharlyAlonso** [comment]
Hello again

It's funny, it usually works well with all images; but some "resist". For example:

dezoomify-rs -l --retries 0 --parallelism 1 "https://www.mba-lyon.fr/sites/mba/files/gigapixel/foujita/foujita.xml" 001.png

Apparently if the boxes are anywhere; but:

![image](https://user-images.githubusercontent.com/66141658/84593672-a27c6e80-ae4d-11ea-907c-d421c34dbc78.png)
