### ISSUE TITLE
add support for IIPImage

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#52]
Hello,
I'm so sorry to bother you again.
I have the following image:
https://www.nga.gov/collection/art-object-page.50724.html
This is the Ginevra de Benci by Leonardo da Vinci
In Google Arts it is published; but in a much lower definition than in the NGA
If I put the URL in dezoomify it starts creating the image; but being so big does not end.
So I wanted to do it with dezoomify-rs; but I am not able to find the configuration file.
I thought about creating a tiles.yaml but I don't know where to get it.
Sorry for the inconvenience.
Thank you so much. Regards,

**Comment by lovasoa** [comment]
Hello, 
  The easiest way to find the URL of the metadata file to pass to dezoomify-rs is to use [dezoomify-extension](https://lovasoa.github.io/dezoomify-extension/). In this case, it yields `https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/5/0/7/2/4/50724-primary-0-nativeres.ptif` (an [IIPImage](https://iipimage.sourceforge.io/documentation/protocol/) url), which is unfortunately not supported yet in dezoomify-rs. So you will have to [write a tiles.yaml file](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer) yourself.

**Comment by CharlyAlonso** [comment]
Hello again
Well, oddly enough, I have got the url of the json with the firefox dezoomify extension:

https://api.nga.gov/iiif/public/objects/5/0/7/2/4/50724-primary-0-nativeres.ptif/info.json

I've put it in the latest version of dezoomify-rs and it worked!

I have Ginevra de Benci's wonderful smile at its highest definition.

Leonardo's smiles are inimitable !!!!!

I am like a child with new shoes !!!

Thanks for everything.
