### ISSUE TITLE
##  The book of Kells: full high-quality download

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#53]
##  The book of Kells: full high-quality download
*extracted from the Trinity College Dublin website*
 - Pages 0 to 100 : http://dl.free.fr/mkRvsCyMP
 - Pages 100 to 200 : http://dl.free.fr/ltFvN0yUe
 - Pages 200 to 300 : http://dl.free.fr/l0US144TB
 - Pages 300 to 339 : http://dl.free.fr/lUCYUgJyH

These links will expire 30 days after they are last downloaded.

>  The Book of Kells contains the four Gospels in Latin based on the Vulgate text which St Jerome completed in 384AD, intermixed with readings from the earlier Old Latin translation. The Gospel texts are prefaced by other texts, including "canon tables", or concordances of Gospel passages common to two or more of the evangelists; summaries of the gospel narratives (Breves causae); and prefaces characterizing the evangelists (Argumenta). The book is written on vellum (prepared calfskin) in a bold and expert version of the script known as "insular majuscule". It contains 340 folios, now measuring approximately 330 x 255 mm; they were severely trimmed, and their edges gilded, in the course of rebinding in the 19th century.

_Originally posted by @lovasoa in https://github.com/lovasoa/dezoomify-rs/issues/17#issuecomment-575932914_

**Comment by CharlyAlonso** [comment]
Hello,
The version that I have is 2450x3200 pixels
Is there another version with more definition ????
Thanks and regards,

**Comment by lovasoa** [comment]
Hello,
  I am going to close this thread since it doesn't seem to be linked to an issue with dezoomify-rs. Commenting is still possible in closed thread, so if someone wants to search for other higher-resolution versions of these images, feel free to post your findings below.

**Comment by SB2020-eye** [comment]
@CharlyAlonso,

I have looked but have not been able to find any higher resolution images.

If you (or anyone reading this) does, we'd love to know! Thanks.
