### ISSUE TITLE
dezoomify-rs 2.0.0

### ISSUE THREAD

**Issue by rigel71** [lovasoa/dezoomify-rs#54]
Hi,
i want to test the new dezoomify from 
http://www.asmilano.it/Divenire/document.htm?idDoc=10637440&idUa=10637439&first=0&last=0
I create tiles.yaml from file .json
i open the terminal and write
dezoomify-rs tiles.yaml result.jpg

Enter an URL or a path to a tiles.yaml file:
dezoomify-rs tiles.yaml result.jpg
ERROR Input/Output error: Impossibile trovare il file specificato. (os error 2)
Enter an URL or a path to a tiles.yaml file:

is there another way to dezoomify with new one?
Thanks

**Comment by lovasoa** [comment]
> Impossibile trovare il file specificato.

It looks like it doesn't find your `tiles.yaml`. 

Do you have the same problem with [older versions](https://github.com/lovasoa/dezoomify-rs/releases) of dezoomify-rs, when both the executable and your yaml file are in the same place ?

**Comment by rigel71** [comment]
yes, I had not checked, perhaps the platform on which the map is based has been updated, something has changed

**Comment by lovasoa** [comment]
Ok, so if the problem does not come from dezoomify, let's close this
