### ISSUE TITLE
krpano image format support #50

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#56]
Hello again

It's funny, it usually works well with all images; but some "resist". For example:

dezoomify-rs -l --retries 0 --parallelism 1 "https://www.mba-lyon.fr/sites/mba/files/gigapixel/foujita/foujita.xml" 001.png

Apparently if the boxes are anywhere; but:

image
![image](https://user-images.githubusercontent.com/66141658/84598268-d8c7e700-ae69-11ea-9e16-57d44e79c74b.png)

**Comment by lovasoa** [comment]
Hello,
  I had a look at this, and I don't think this is a bug in dezoomify-rs. The server is just missing tiles at the highest resolution. You can download the image at other resolutions. Also, if the server tends to return errors when under high load, even if it really has a tile, then you should not use `--retries 0`. Retrying failed downloads takes longer, but it helps ensure you are not missing tiles that are available. In order not to put the server under too much load, you can use `--retry-delay 30s` to wait 30 seconds before retrying a failed tile download.

**Comment by lovasoa** [comment]
Hmm, looking at my download, the parts of the image that were downloaded for meJust zooming into the image on the website itself triggers the same errors as with dezoomify-rs:

![image](https://user-images.githubusercontent.com/552629/84599357-ae7a2780-ae71-11ea-9c3b-a288e8f35833.png)

**Comment by lovasoa** [comment]
Something that would help here would be implementing https://github.com/lovasoa/dezoomify-rs/issues/37

**Comment by lovasoa** [comment]
An example of a very conservative set of parameters to use would be `--parallelism 1 --retry-delay 30s --retries 5`
