### ISSUE TITLE
Error Krpano format unexpected tag in xml file

### ISSUE THREAD

**Issue by mcanabaluc3m** [lovasoa/dezoomify-rs#58]
When Krpano xml file image tag contains mobile or tablet tags dezoomify-rs return error. Manually deleting these tags solve the issue. 

An example of xml is: 
![image](https://user-images.githubusercontent.com/61794579/86904573-34a42980-c111-11ea-9a47-9de098a8227a.png)

**Comment by lovasoa** [comment]
Hi, and thanks for the report ! Can you please copy-paste the XML ? And ideally also provide an URL ?

**Comment by mcanabaluc3m** [comment]
I will add more info when reporting an issue. Thanks for the work, this program is amazing!

**Comment by lovasoa** [comment]
Thank you. Seeing people use it and like it what keeps me motivated on this project 🙂
