### ISSUE TITLE
Can't find pattern for batch download from a site

### ISSUE THREAD

**Issue by SB2020-eye** [lovasoa/dezoomify-rs#71]
Hi. I wrote previously -- and was helped wonderfully -- about downloading images from the Book of Kells (now found at https://digitalcollections.tcd.ie/concern/works/hm50tr726?locale=en ).

The images have changed since that time (at least based on my small sample). (I'm not sure the resolution is any better -- though I wish it was. But there are visible changes in the color. If interested, here is the before:
![page330r-before](https://user-images.githubusercontent.com/56878280/92498652-e242c000-f1c8-11ea-9acf-dcf805c75bc1.jpg)
and the after:
![page330r-after](https://user-images.githubusercontent.com/56878280/92498680-ecfd5500-f1c8-11ea-94d5-1708a4a73c40.jpg)

With the image changes, the url format has also changed.

I can use dezoomify-rs and the `info.json` file to download one image. For example, I can download [page005r](https://digitalcollections.tcd.ie/iiif/2/n583xv45d%2Ffiles%2F2beed59b-a7fd-4c1e-ac9f-d526d3d5956b%2Ffcr:versions%2Fversion1/full/2318,/0/default.jpg) by typing this command into my terminal (Windows 10, Visual Studio Code) and selecting "0" at the prompt to get the largest image version:
`.\dezoomify-rs https://digitalcollections.tcd.ie/iiif/2/n583xv45d%2Ffiles%2F2beed59b-a7fd-4c1e-ac9f-d526d3d5956b%2Ffcr:versions%2Fversion1/info.json C:/Users/Scott/Desktop/Python2/Kells/Originals-All/my_image.png`

However, I cannot find any pattern in the urls between pages/images. Here are three example urls:

page004v: [https://digitalcollections.tcd.ie/iiif/2/hx11xf73g%2Ffiles%2Fffc2b4d2-6212-4430-ae2c-ccd0bc1ecd11%2Ffcr:versions%2Fversion1/full/2433,/0/default.jpg](url)
page005r: [https://digitalcollections.tcd.ie/iiif/2/n583xv45d%2Ffiles%2F2beed59b-a7fd-4c1e-ac9f-d526d3d5956b%2Ffcr:versions%2Fversion1/full/2318,/0/default.jpg](url)
page005v: [https://digitalcollections.tcd.ie/iiif/2/jd472w862%2Ffiles%2F2577066e-9777-4543-aba3-32bd29c84d59%2Ffcr:versions%2Fversion1/full/2396,/0/default.jpg](url)

Referencing the IIIF scheme `{scheme}://{server}{/prefix}/{identifier}/{region}/{size}/{rotation}/{quality}.{format}`, I can't see any pattern in the `{identifier}` between images

Identifiers:
page004v:   hx11xf73g%2Ffiles%2Fffc2b4d2-6212-4430-ae2c-ccd0bc1ecd11%2Ffcr:versions%2Fversion1
page005r:   n583xv45d%2Ffiles%2F2beed59b-a7fd-4c1e-ac9f-d526d3d5956b%2Ffcr:versions%2Fversion1
page005v:   jd472w862%2Ffiles%2F2577066e-9777-4543-aba3-32bd29c84d59%2Ffcr:versions%2Fversion1

I wonder if anyone can help me out. The goal is code to batch download the images from this manuscript. Thanks for your consideration.

**Comment by lovasoa** [comment]
Hello !
  I'm closing this issue since it is not related to dezoomify-rs, but feel free to keep commenting below.

**Comment by lovasoa** [comment]
Here is a small script for scrapping the pages from the website : 

```bash
#!/usr/bin/env bash


for page in $(seq 68)
do
  echo "Page $page"
  downloads=$(
    curl --silent "https://digitalcollections.tcd.ie/concern/works/hm50tr726?locale=en&page=$page" | 
      grep -E --only-matching "/downloads/\w+" |
      uniq |
      tail -n +2
   )
   i=0
   for d in $downloads
   do 
     i=$(($i+1))
     file="kells-$page-$i.jpg"
     echo $file
     curl "https://digitalcollections.tcd.ie$d" > $file
   done
done
```

**Comment by lovasoa** [comment]
The images are being downloaded here: https://github.com/lovasoa/download-book-of-kells/runs/1087107485?check_suite_focus=true

When done, the images will be available here: https://github.com/lovasoa/download-book-of-kells/releases

**Comment by lovasoa** [comment]
https://github.com/lovasoa/download-book-of-kells/releases/download/refs%2Fheads%2Fmaster/kells.zip

**Comment by SB2020-eye** [comment]
Thank you so, so much. Thorough (as always). :)

**Comment by SB2020-eye** [comment]
Hi again. Question...

The images from the zip file you produced and the individual ones I downloaded differ. I would appreciate knowing why that's that case. They differ in file size and (slightly but definitely) in appearance when blown up (to say 1500%).

I'll use page330r as an example.

1. Mine ("page330r.jpg"): file size = 3.2MB
![image](https://user-images.githubusercontent.com/56878280/92659854-2916df80-f2c7-11ea-9161-be6ada8be8ed.png)

2. Zip Folder ("kells-67-1.jpg"): file size = 1.95MB
![image](https://user-images.githubusercontent.com/56878280/92659926-5a8fab00-f2c7-11ea-9946-c92b47023646.png)

I tried for hours to use the script just to run one more comparison of images before asking this question, but I couldn't get it to work on Windows. I'm sure the problem is me. But with WSL running and the Ubuntu 20.04 LTS app, the script goes through some motions, listing out

```
Page 1
Page 2
...
Page 67
Page 68
```

and then stops (produces the prompt for the next command, no error messages). I ran it twice but I couldn't find the files anywhere.

**Comment by lovasoa** [comment]
Github doesn't allow overly large uploads, so I had to (ver slightly) reduce the quality of the images. (See [this line](https://github.com/lovasoa/download-book-of-kells/blob/master/kells.sh#L19))

If the script didn't display any error, on your computer, it worked. The images are saved in the current working directory. On windows with WSL,  you can [access the files from your linux distribution from the "network" tab of the windows file explorer](https://www.howtogeek.com/426749/how-to-access-your-linux-wsl-files-in-windows-10/).

**Comment by SB2020-eye** [comment]
Sorry for the trouble. Yes, I tried explorer.exe . I tried again today. Then I searched manually through perhaps hundreds of files (because I wasn't sure they were indexed for explorer). But I also ran searches. I also uninstalled and reinstalled Ubuntu (and ran the script again), followed by searches. Here are some screenshots:

![image](https://user-images.githubusercontent.com/56878280/92794540-a8ff8100-f37d-11ea-8bae-2ea8c341eaf7.png)

![image](https://user-images.githubusercontent.com/56878280/92794562-ad2b9e80-f37d-11ea-9c97-1fd1865259b0.png)

![image](https://user-images.githubusercontent.com/56878280/92794576-af8df880-f37d-11ea-8ce6-520517766663.png)

The only other mystery I can point to is this virtual drive that evidently gets installed with Ubuntu.

![image](https://user-images.githubusercontent.com/56878280/92794689-c9c7d680-f37d-11ea-9d48-169e863b6e5c.png)

But it does not open, nor can I find a way (by attempting or by googling) to do anything with it.

**Comment by lovasoa** [comment]
How did you install the script and how are you running it ?

What does `curl -v "https://digitalcollections.tcd.ie/concern/works/hm50tr726?locale=en&page=1"` return ?

**Comment by SB2020-eye** [comment]
I just cut and pasted the script into Ubuntu terminal. I also tried changing the save address to a folder in my c drive, but that didn't work (same result -- it went through the motions described before, but the folder was empty afterwards).

Now I can't open Ubuntu terminal (to try your "curl" code). It says, "The process cannot access the file because it is being used by another process." Trying to download Git Bash to test everything there.

**Comment by SB2020-eye** [comment]
I'm running in Git Bash and getting a more expected outcome with the script, I believe:

![image](https://user-images.githubusercontent.com/56878280/92951284-1cf86280-f42c-11ea-9041-28ab42dfcd5e.png)

And I see the files saving to my Desktop. I guess it was something about Ubuntu on Windows (or my attempt at it at least this go-round).

Thanks again!
