### ISSUE TITLE
Advantages of using the custom YAML dezoomer?

### ISSUE THREAD

**Issue by SB2020-eye** [lovasoa/dezoomify-rs#72]
If one is able to use dezoomify-rs to obtain images with, say, the IIIF dezoomer, or the DeepZoom dezoomer, would there be any advantages to using a custom YAML dezoomer?

For example, are there any circumstances in which the custom YAML dezoomer would be accessing higher-resolution/quality images? (That's the main impetus for my question.)

Thanks.

**Comment by lovasoa** [comment]
Hello,
  No, the custom yaml dezoomer is useful only when the zoomable image is in a format that is otherwise not implemented by dezoomify-rs. I can't think of any advantage of using it for an IIIF or a deepzoom image.

**Comment by SB2020-eye** [comment]
Thank you so much for clarifying this. All the best.
