### ISSUE TITLE
Make the URL field in dzi json files optional

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#77]
_Initially reported by @Tricesimo in https://github.com/lovasoa/dezoomify/issues/475_

### Site name and desciption
https://www.christies-media.com/assets/19872-62316484-sz/view/iframe

The webpage has both their regular zoom, but now also a super-zoom, called "BigObjectBase"

If I try using dezoomify using the web address, I get the error that it cannot find a dezoomable object. 

I have installed the dezoomify extension, and while it does appear to find the file:
https://www.christies-media.com/api/files/97b25d1e-14f4-4e9b-9a42-8fdafd81e420/superzoom.dzi
it gives me the same error as before (selected Seadragon)

I also downloaded the dezoomify-rs application, and I get the same errors each time:

ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - iiif: Unable to create the dezoomer: Invalid IIIF info.json file: missing field `width` at line 1 column 152
 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 1:1 Unexpected characters outside the root element: {
 - krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 1:1 Unexpected characters outside the root element: {

I wonder if it's a similar solution to how the Barnes website is working.

Thanks again for your help!

**Comment by lovasoa** [comment]
The current workaround is to manually download the file, add the `Url` field, and open it with dezoomify-rs : 

```json
{
  "Image": {
    "Url": "https://www.christies-media.com/api/files/97b25d1e-14f4-4e9b-9a42-8fdafd81e420/superzoom_files",
    "xmlns": "http://schemas.microsoft.com/deepzoom/2008",
    "Format": "jpg",
    "Overlap": "0",
    "TileSize": "256",
    "Size": {
      "Height": "16384",
      "Width": "16384"
    }
  }
}
```

**Comment by Tricesimo** [comment]
Success again! Thanks for your help.

**Comment by lovasoa** [comment]
In dezoomify-rs v2.4.2, you can now input https://www.christies-media.com/api/files/97b25d1e-14f4-4e9b-9a42-8fdafd81e420/superzoom.dzi and it will just work.

**Comment by Tricesimo** [comment]
That's great! Thanks again for your help!

**Comment by Tricesimo** [comment]
Looks like they've changed it around again. Here is a recent auction item:

https://www.christies.com/lot/lot-vincent-van-gogh-1853-1890-la-mousme-6306076/?from=salesummary&intObjectID=6306076&lid=1

Again, there is a normal zoom, but then there's a link to a superzoom, but it doesn't go the BigObject page like the previous one did. Pasting the page in dezoomify website doesn't work, and I can't figure out how to get the JSON or the dzi file like you showed me in the earlier example.

**Comment by Tricesimo** [comment]
Sorry - I just found it - needed to open the frame in a new window to get the BigObject. 

Thanks for your help in finding this last time!

**Comment by emallen1973** [comment]
Tricesimo,
Can you tell me the steps you followed to obtain the super-zoom image from Christie's website?
Thanks in advance.

**Comment by emallen1973** [comment]
This is the image I am trying to download:
https://www.christies.com/lot/lot-pablo-picasso-la-couseuse-6321052/?from=searchresults&intObjectID=6321052

**Comment by Tricesimo** [comment]
That's funny! I just downloaded that picture myself yesterday!

So, to begin, I am using Firefox as my browser, and I have installed the Dezoomify attachment. I have also downloaded the latest version of dezoomify-rs into a folder on my desktop.

Here's what I did:
1. From the page you provided, click on the Superzoom link. 
2. Right click on the image, select "This Frame", and then "Show Only This Frame" - this will now switch the view so the tab says "Big Object Base"
3. Activate the Dezoomify attachment
4. Zoom in and out until the Dezoomify attachment finds something
5. Click on the Dezoomify attachment, and it will open in a new page, with a jpg pre-filled. This can't be downloaded as-is. 
6. Copy the long string of text between the "files/" and the "/0/0_0.jpg"
7. Use Notepad to create a text file with the following text

{
  "Image": {
    "Url": "https://www.christies-media.com/api/files/649206d1-250a-4911-a262-6bdd7e4926b0/superzoom_files",
    "xmlns": "http://schemas.microsoft.com/deepzoom/2008",
    "Format": "jpg",
    "Overlap": "0",
    "TileSize": "256",
    "Size": {
      "Height": "16384",
      "Width": "16384"
    }
  }
}

The text you've copied is in that first line, after "files/" and before "/superzoom_files" - you can use this format for any other superzooms on that site, just overwrite the file as needed.

8. Save that file as "christies.json" in a desktop folder (wherever your Dezoomify-rs.exe is)
9. Launch Dezoomify-rs. It opens in a new desktop window.
10. Drag that json file from your desktop folder into that Dezoomify-rs window
11. Delete the quotes that appear before and after the filename
12. Hit Enter, and then select the size of the image you want

Notes: There will always be a lot of white space surrounding it. Not sure how to prevent that, so I use photoshop to crop it. 
Sometimes, the biggest size file won't be available - you'll know if a bunch of gibberish appears in the screen. If so, close that window and start again from step 9.
If the download is working, you'll get a progress meter. The file should get saved in the same folder as where the Dezoomify-rs file is. 
Sometimes you'll get a message where a couple of tiles couldn't be found. If so, just reload the file, it should eventually work.

Hope this helps!

**Comment by emallen1973** [comment]
Well, I was going to follow your indications, but now the superzoom page at
christie's gives gives this message:

502 Bad Gateway
------------------------------
nginx/1.13.8

**Comment by emallen1973** [comment]
I tried to do it with the following image
https://www.christies-media.com/assets/19809-64121437-sz/view/iframe

using the dezoomify address below:
https://www.christies-media.com/api/files/ccbf2426-23de-4e91-9b89-bd23bd93e662/superzoom_files/0/0_0.jpg

but I got the error shown in the attached image
![error](https://user-images.githubusercontent.com/84104624/118138762-4fe46300-b3cc-11eb-85f0-cbf61e9916ea.jpg)

**Comment by emallen1973** [comment]
I fixed the problem. I forgo that I needed to change the "Height" and "Width" of the specific image I wanted to download.
Thank you so much for your help.

**Comment by Tricesimo** [comment]
Glad to see it worked! Question for you: where did you find the height/width of the pic you're trying to download? I always leave the JSON as 16384x16384 and just choose whatever option seems to work (0, 1, 2...). I'm sure that changing the JSON would give a better result.

**Comment by emallen1973** [comment]
1. Identify the address with Dezoomify
For instance for
https://www.christies-media.com/assets/940e2d0b-d844-4180-98ea-62b0d0f0bb33/view/iframe
it is:
https://www.christies-media.com/api/files/c9bf024e-1eb4-4669-9e34-ace0dae9cfdb/superzoom_files/0/0_0.jpg

2 Select the string up to "/0/", i.e.
In this case:
https://www.christies-media.com/api/files/c9bf024e-1eb4-4669-9e34-ace0dae9cfdb/superzoom_files

3. Place that string in the address bar:
You will get something like the attached image, containing the Height and Width of the image

4. Then change the Height and Width of the image on your .json file for the specific image

{
"Image": {
"Url": "https://www.christies-media.com/api/files/c9bf024e-1eb4-4669-9e34-ace0dae9cfdb/superzoom_files
![ImageInfo](https://user-images.githubusercontent.com/84104624/118169668-d3af4700-b3ee-11eb-8eab-1b47f09b2b72.jpg)
",
"xmlns": "http://schemas.microsoft.com/deepzoom/2008",
"Format": "jpg",
"Overlap": "0",
"TileSize": "256",
"Size": {
"Height": "16384",
"Width": "16384"
}
}
}

**Comment by Tricesimo** [comment]
Thanks! Excellent collaboration. Happy hunting on Christies. One thing to note is that they only just started putting things in Superzoom this year - prior to this year, most of their images were 3200 pixels along their largest axis, which is still quite good. They have a lot of excellent works by van Gogh, Monet, de Lempicka, Picasso, and many other lesser-known artists.
