### ISSUE TITLE
Issue with tiles under different folders

### ISSUE THREAD

**Issue by tojoshuazhang** [lovasoa/dezoomify-rs#78]
using this page as example: https://gigapixel.museoreinasofia.es/es/mujer-azul-pablo-picasso/#7/83.213/-175.452

it's tiles are contained in multiple sub-folders such as:
https://mncars-gigapixel.s3.eu-central-1.amazonaws.com/AS01618/VIS/TileGroup10/7-0-0.jpg
https://mncars-gigapixel.s3.eu-central-1.amazonaws.com/AS01618/VIS/TileGroup40/7-76-100.jpg

Is there a way to download using dezoomify-rs?

**Comment by lovasoa** [comment]
This is a zoomify image. The zoomify format is supported natively by dezoomify-rs, you can simply pass the URL of the meta-information file. To find this URL, you can manually look for it in your network traffic, or simply use the [dezoomify-extension](https://lovasoa.github.io/dezoomify-extension/) browser addon.

**Comment by tojoshuazhang** [comment]
Thank you!
