### ISSUE TITLE
IIIF image issue

### ISSUE THREAD

**Issue by autur** [lovasoa/dezoomify-rs#8]
Hey, 

Trying to work with images that follow the IIIF protocol:
https://stor.artstor.org/iiif/fpx/carnegie/d0516/05166006.fpx/info.json
https://stor.artstor.org/iiif/fpx/carnegie/d0463/04636006.fpx/info.json

But both web and rs versions of dezoomify fail to grab all the tiles. Dezoomify-rs gives "Client Error: 401 unauthorized" when it fails on each tile. Most likely because it requires some authentication. 

However, I am able to get the full-size image by simply modifying the width value in the URL of the default.jpg file from XHR:
https://stor.artstor.org/iiif/fpx/carnegie/d0516/05166006.fpx/full/3588,/0/default.jpg
I wonder though if there is some other way of modding the URL without having to check the json file for the width, as this is cumbersome. Is it absolutely necessary to provide the actual width? 

As a side note, what kind of resource would I look into if I want to learn more about how to interact with URLs to get what I want? Is this all API? I don't have a computer science background, so this is a little over my head.

**Comment by lovasoa** [comment]
Hello,

  - [This page in dezoomify's wiki explains how to get the full size image by modifying the URL](https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server)
  - [The full IIIF protocol is described here](https://iiif.io/api/image/2.1/#terminology)
  - If you get 401 errors, you will most likely have to set custom HTTP headers to request the tiles. [dezoomify's wiki has a page about accessing protected pages](https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages). Once you've figured out which headers are necessary to avoid the 401 response, you can also set them in dezoomify-rs by ([setting a flag on the command-line when launching dezoomify-rs](https://github.com/lovasoa/dezoomify-rs#command-line-options)):

```
dezoomify-rs -H "HeaderName: HeaderValue" my-url
```

**Comment by autur** [comment]
Thank you! Just had to specify full/full/ 
Honestly had no idea those wiki pages existed. Thanks for all the work you put into documenting this!

**Comment by lovasoa** [comment]
You're right, I will do that

**Comment by autur** [comment]
Hi again. The full jpg approach is now giving 401 errors, however I found the appropriate header (access cookie) to add before the json URL for authorization, so the dezoomify option works. Do you know if this cookie can also be appended to the .jpg URL or somehow embedded ? (something like ...full/full/default.jpg?cookie=...). I looked at the IIIF protocol, but couldn't identify a solution like this.

**Comment by MrChrisWin** [comment]
> Hi again. The full jpg approach is now giving 401 errors, however I found the appropriate header (access cookie) to add before the json URL for authorization, so the dezoomify option works. Do you know if this cookie can also be appended to the .jpg URL or somehow embedded into the browser? (something like ...full/full/default.jpg?cookie=...). I looked at the IIIF protocol, but couldn't identify a solution like this.

Autur, where did you find the access cookie and how did you modify the url path? Thanks.

**Comment by autur** [comment]
@MrChrisWin 
On any page the zoomable artwork, open the Chrome browser Developer Tools, go to Network Activity, and within the "All" tab, find and click on "default.jpg". Under the Request Headers, look for "x-jstor-access-session". Below is an example of how I use it with dezoomify. 

`dezoomify-rs -H "x-jstor-access-session: H4sIAAAAAAAAAJWTS2-bQBSF9_kViHWw5s1MV7WJI3WTRLazqK…3Kyj0_vpbVz8fbm9Fb-RLJPJq05Pughd0UF4ff89tBN8UEAAA" https://stor.artstor.org/iiif/fpx/sslps/c7731863/18890801.fpx/info.json "Ben Shahn illustrations/untitled _0.jpg"`
