### ISSUE TITLE
Can you help me see how this website is built and downloaded

### ISSUE THREAD

**Issue by xiaomayidechuanshuo** [lovasoa/dezoomify-rs#81]
How to download this website "https://digitalcollections.nypl.org/items/a28d6e6b-b317-f008-e040-e00a1806635d"

**Comment by lovasoa** [comment]
It looks like you can use the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) : 

```
https://access.nypl.org/image.php/a28d6e6b-b317-f008-e040-e00a1806635d/tiles/0/12/{{X}}_{{Y}}.png
```
