### ISSUE TITLE
Download from Österreichische Nationalbibliothek 

### ISSUE THREAD

**Issue by Bobdreams** [lovasoa/dezoomify-rs#83]
Hi all, 

Thank for Dezoomify project ! 

I don't find, how download from Österreichische Nationalbibliothek  online library : 

http://digital.onb.ac.at/RepViewer/viewer.faces?doc=DTL_3119148&order=1&view=SINGLE&fbclid=IwAR11Ur-VezJBBzWkKtvkTUHZIYDdw5bBHIEryS9fsm1Ky9O-_CpM09bm0h4

Can you help me ? 

Many thanks !

**Comment by lovasoa** [comment]
You can download the entire image from the original server without any external tool by simply changing the parameters in the URL of one of the image tiles. You can open your browser's network inspector to find the URL of a tile, and then change the x, y, w, and h parameters to cover the entire image.

For instance, one tile has the URL : 

```
http://digital.onb.ac.at/RepViewer/image?doc=DTL_3119148&img=00000015.jpg&hash=5af078d39f168378512cf479bbbec13c59557c6cc36219236e3808fe2e928319329f9ab8be9a5ac9e0a4ce52aba3&w=228&h=285&x=456&y=570&s=1.9&q=70
```

you can change it to 

```
http://digital.onb.ac.at/RepViewer/image?doc=DTL_3119148&img=00000015.jpg&hash=5af078d39f168378512cf479bbbec13c59557c6cc36219236e3808fe2e928319329f9ab8be9a5ac9e0a4ce52aba3&w=5000&h=8000&x=0&y=0&s=1.8&q=85
```

and get this : 

![](http://digital.onb.ac.at/RepViewer/image?doc=DTL_3119148&img=00000015.jpg&hash=5af078d39f168378512cf479bbbec13c59557c6cc36219236e3808fe2e928319329f9ab8be9a5ac9e0a4ce52aba3&w=5000&h=8000&x=0&y=0&s=1.8&q=85)
