### ISSUE TITLE
krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 73:20 Qualified name is invalid

### ISSUE THREAD

**Issue by Boscop** [lovasoa/dezoomify-rs#84]
Why doesn't this work?
```
> dezoomify-rs https://www.360cities.net/image/underwater-photography-virtual-reality-new-caledonia
ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 73:20 Qualified name is invalid:
 - krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 73:20 Qualified name is invalid:
```

This is presumably the xml file:
https://www.360cities.net/embed_iframe/underwater-photography-virtual-reality-new-caledonia.xml?no_hotspots=false&home_main_pano=false&portfolio_view=false&pro_embed=false

Line 73:
![image](https://user-images.githubusercontent.com/535593/99199992-1925eb00-27a3-11eb-9861-a4e3dd66de22.png)

**Comment by lovasoa** [comment]
dezoomify-rs needs the URL of the xml meta-information file, not the URL of the viewer page.

In your case, it is `https://www.360cities.net/embed_iframe/underwater-photography-virtual-reality-new-caledonia.xml?no_hotspots=false&home_main_pano=false&portfolio_view=false&pro_embed=false

You can find it in your browser's network inspector.

**Comment by Boscop** [comment]
Ah, thanks! And how can I specify that I want to download the highest resolution version of the faces?

**Comment by lovasoa** [comment]
You can run `dezoomify-rs --help` to get the list of available options.

**Comment by Boscop** [comment]
@lovasoa Thanks, but when I pass the url to the xml file, it only downloads one of the 6 faces. How can I make it download all (and store as `{left,right,up,down,front,back}.jpg`)?

**Comment by lovasoa** [comment]
Unfortunately, this is not yet possible. Pull requests welcome ! Currently, dezoomify-rs has not notion of multiple images (it does not make the difference between having multiple images available and having multiple resolutions available for the same image). Implementing a way for dezoomify-rs to make this difference would also be a first step towards #37

**Comment by Boscop** [comment]
@lovasoa Thanks. Btw, is there a way to at least give the desired face as arg, to not require user input at runtime? So that I can invoke it 6 times, once for each `--face`?

**Comment by lovasoa** [comment]
Well, you can always feed the image number you are interested in to the standard input. 

```bash
echo 3 | dezoomify-rs "https://example.com"
```

**Comment by Boscop** [comment]
@lovasoa But it's not always the same, it depends on the image in question, how many levels it has etc.
Or can I use dezoomify to query which number is e.g. the `front` face?
So what would be the most automatic way? :)

**Comment by lovasoa** [comment]
I guess you could parse the standard output, but at this point, it would probably be better to just update dezoomify-rs itself. Would you be interested in working on that?

**Comment by Boscop** [comment]
@lovasoa I'm already super busy with too many other things..
Btw, is it possible with dezoomify to download tiles from google streetview, like [this one](https://www.google.com/maps/@28.4738783,-81.467653,3a,90y,183.2h,99.44t/data=!3m7!1e1!3m5!1sAF1QipOeTd6ptZd2-XDmTw2oBjbk-eBT5FqjiyKrew7g!2e10!3e12!7i10692!8i5346)?

**Comment by lovasoa** [comment]
The format is not explicitly supported, but you can use the generic dezoomer : 

```
https://lh3.ggpht.com/p/AF1QipOeTd6ptZd2-XDmTw2oBjbk-eBT5FqjiyKrew7g=x{{X}}-y{{Y}}-z5
```



![google](https://user-images.githubusercontent.com/552629/100526348-3194fd00-31c8-11eb-82a3-2215501c05ea.jpg)

**Comment by Boscop** [comment]
@lovasoa Ah great, thanks! Btw, how can I determine the largest zoom level available? :)

**Comment by lovasoa** [comment]
By zooming in on the image on your browser with your network monitor on.

**Comment by Boscop** [comment]
@lovasoa Thanks! Btw, do you by any change also know a tool that can convert an equirectangular image to 6 cubemap face images? I tried several but they all didn't work.
E.g. I tried this one: https://360toolkit.co/convert-spherical-equirectangular-to-cubemap
But it produced artifacts [like this](https://user-images.githubusercontent.com/535593/100528844-7a0ce480-31e1-11eb-9c13-5e25f8e12272.png) in almost all faces.
Btw, I also tried after cropping the height to be half the width:
> mogrify -crop 10752x5376 equirectangular.jpg

It still didn't generate the faces correctly.

And I tried this one: https://jaxry.github.io/panorama-to-cubemap/
But it created a weird [black area](https://user-images.githubusercontent.com/535593/100528872-c0fada00-31e1-11eb-8b96-1853181f807a.png) (in both chrome and FF).

I also tried this one: https://github.com/sunset1995/py360convert
But couldn't get it to run: https://github.com/sunset1995/py360convert/issues/12
And that tool doesn't seem to generate 6 image files either. I need 6 separate image files.

Do you know a (CLI) tool that works for this? :)

**Comment by lovasoa** [comment]
No I don't. Sorry :)
