### ISSUE TITLE
zoomify seadragon viewer page is being misdetected as IIIF image

### ISSUE THREAD

**Issue by haringk** [lovasoa/dezoomify-rs#86]
### Site name and desciption
https://orion2020v5b.spaceforeverybody.com/

### Example URLs
https://orion2020v5b.spaceforeverybody.com/

### Current error message
They use OpenSeaDragon script. Using web script the image downloaded contains annotations, using dezoomify-rs (mac and windows) I get this error:

`Found the following zoom levels:`
`0. orion2020v5b.spaceforeverybody.com (62596 x 38467 pixels,  9348 tiles)`
`1. orion2020v5b.spaceforeverybody.com (62596 x 38467 pixels,  9348 tiles)`
`Which level do you want to download?`
`0`
`[ETA:0s] ########################################    0/0    Computing the URLs of the image tiles...`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/1024,0,512,512/512,512/0/default.jpg). Retrying tile download in 2.48s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/0,0,512,512/512,512/0/default.jpg). Retrying tile download in 2s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/512,0,512,512/512,512/0/default.jpg). Retrying tile download in 2.24s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/3072,0,512,512/512,512/0/default.jpg). Retrying tile download in 3.44s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/3584,0,512,512/512,512/0/default.jpg). Retrying tile download in 3.68s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/4096,0,512,512/512,512/0/default.jpg). Retrying tile download in 3.92s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/6144,0,512,512/512,512/0/default.jpg). Retrying tile download in 2.88s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/7680,0,512,512/512,512/0/default.jpg). Retrying tile download in 3.6s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/2560,0,512,512/512,512/0/default.jpg). Retrying tile download in 3.2s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/4608,0,512,512/512,512/0/default.jpg). Retrying tile download in 2.16s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/7168,0,512,512/512,512/0/default.jpg). Retrying tile download in 3.36s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/1536,0,512,512/512,512/0/default.jpg). Retrying tile download in 2.72s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/2048,0,512,512/512,512/0/default.jpg). Retrying tile download in 2.96s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/5120,0,512,512/512,512/0/default.jpg). Retrying tile download in 2.4s.`
`[2020-11-17T08:00:21Z WARN  dezoomify_rs] network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/6656,0,512,512/512,512/0/default.jpg). Retrying tile download in 3.12s.`
`[ETA:16h] #---------------------------------------    1/9348 Requesting the tiles...`
`[ETA:12h] #---------------------------------------    2/9348 Unable to download tile 'https://orion2020v5b.spaceforeverybody.com/0,0,512,512/512,512/0/default.jpg'. Cause: network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/0,0,512,512/512,512/0/default.jpg)`
`[ETA:8h] #---------------------------------------    4/9348 Unable to download tile 'https://orion2020v5b.spaceforeverybody.com/512,0,512,512/512,512/0/default.jpg'. Cause: network error: HTTP status client error (404 Not Found) for url (https://orion2020v5b.spaceforeverybody.com/512,0,512,512/512,512/0/default.jpg)`
`...`

**Comment by haringk** [comment]
Sure, can I report the issue to dezoomify for the first part?

**Comment by lovasoa** [comment]
This is a zoomify image, you can use the dezoomify browser extension to find the meta-information URL to pass to dezoomify-rs : 

```
https://orion2020v5b.spaceforeverybody.com/ORIONFINAL/ImageProperties.xml
```

**Comment by lovasoa** [comment]
> Sure, can I report the issue to dezoomify for the first part?

If you also found a bug in the dezoomify web application, you can report it too, but your issue report on this issue mentioned only dezoomify-rs.

**Comment by lovasoa** [comment]
It looks like this page doesn't trigger our IIIF false-positive detection heuristic in https://github.com/lovasoa/dezoomify-rs/blob/master/src/iiif/mod.rs#L48-L69

**Comment by haringk** [comment]
> This is a zoomify image, you can use the dezoomify browser extension to find the meta-information URL to pass to dezoomify-rs :
> 
> ```
> https://orion2020v5b.spaceforeverybody.com/ORIONFINAL/ImageProperties.xml
> ```

It works perfectly at 99,999% :-)

![Schermata 2020-11-17 alle 13 16 29](https://user-images.githubusercontent.com/74597541/99389309-247a3300-28d7-11eb-993a-4094ae2dac16.png)

just two frames lost
`ERROR Only 36993 tiles out of 36995 could be downloaded. The resulting image was still created.`
