### ISSUE TITLE
Allow to specify the number of digits used for numbering the downloaded files

### ISSUE THREAD

**Issue by jsbien** [lovasoa/dezoomify-rs#87]
To put in the proper order the downloaded files I have to rename them. So I would prefer e.g. `dezoomified000.jpg` over `dezoomified.jpg`, `dezoomified001.jpg` over `dezoomified1.jpg` etc.
I use the one-liner

`curl "https://polona.pl/iiif/item/MTI2MzI0NjU/manifest.json" | jq -r ".items[].id" | xargs -n 1 dezoomify-rs -l`

suggested in https://github.com/lovasoa/dezoomify/issues/416.

Perhaps it can be done somehow on the script level?

**Comment by lovasoa** [comment]
Fixed in v2.6.1

**Comment by jsbien** [comment]
Thank you very much, but how to compile the new version?

**Comment by lovasoa** [comment]
You don't have to compile it yourself, just wait for the continuous deployment servers to do it. Once the binaries are available, you can download them for the releases page: https://github.com/lovasoa/dezoomify-rs/releases

**Comment by lovasoa** [comment]
If you *want* to compile it yourself, though, you can. Download the sources, install [rust](https://rustup.rs/), and in the sources directory, run `cargo build --release`.

**Comment by Iskander1220** [comment]
Hello and sorry for my English). Is there the same processing for books from the site belgica.kbr.be? It does not manage to understand the algorithm for obtaining [links for pages](https://belgica.kbr.be/BELGICA/doc/SYRACUSE/16493973/le-livre-des-fais-d-armes-et-de-chevalerie-ms-10476). If suddenly you have a decision, please share.

**Comment by lovasoa** [comment]
No, there is nothing automatic. You would have to write a small script.

**Comment by Iskander1220** [comment]
Write the script can, but it fails to understand how to get links to images. Maybe you know how?

**Comment by jsbien** [comment]
I used
`https://polona.pl/iiif/item/MTI2MzI0NjE/manifest.json" | jq -r ".items[].id" | xargs -n 1 ./dezoomify-rs -l --parallelism 1 --timeout 60s --retry-delay 60s`

**Comment by Iskander1220** [comment]
Cancel) I already understood how to form links for Belgica
