### ISSUE TITLE
Please allow to start numbering from the specified number

### ISSUE THREAD

**Issue by jsbien** [lovasoa/dezoomify-rs#89]
There 2 reasons for this.
1. Now the first file has no number at all. I have to rename it by hand to dezoomified_0000.*. If numbering from 1 is needed or preferred, all files have to be renamed.
2. Occasionally there is a need to resume downloading or to download just a specific page. Using the appropriate number at this stage would be less error-prone than renaming the file(s) later by hand.

**Comment by lovasoa** [comment]
Dezoomify-rs is not a mass downloading tool. It can only download a single file. You can call or several times to download several files, but it doesn't "start" numbering anywhere. You can specify the output image filename to whatever you want, you don't have to rename the file later.
