### ISSUE TITLE
failed to download

### ISSUE THREAD

**Issue by PandaBalls** [lovasoa/dezoomify-rs#93]
ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - custom: The 'custom' dezoomer cannot handle this URI
 - zoomify: The 'zoomify' dezoomer cannot handle this URI
 - generic: The 'generic' dezoomer cannot handle this URI
 - pff: The 'pff' dezoomer cannot handle this URI
 - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
 - nypl: The 'nypl' dezoomer cannot handle this URI
 - google_arts_and_culture: Unable to download required data: network error: error sending request for url (https://artsandculture.google.com/asset/light-in-the-dark/ZQFouDGMVmsI2w): operation timed out
 - iiif: Unable to download required data: network error: error sending request for url (https://artsandculture.google.com/asset/light-in-the-dark/ZQFouDGMVmsI2w): operation timed out
 - deepzoom: Unable to download required data: network error: error sending request for url (https://artsandculture.google.com/asset/light-in-the-dark/ZQFouDGMVmsI2w): operation timed out
 - krpano: Unable to download required data: network error: error sending request for url (https://artsandculture.google.com/asset/light-in-the-dark/ZQFouDGMVmsI2w): operation timed out

dezoomify-rs expects a zoomable image meta-information file URL. To find this URL, you can use the dezoomify browser extension, which you can download at
- https://lovasoa.github.io/dezoomify-extension/ 
If this doesn't help, then your image may be in a format that is not yet supported by dezoomify-rs.
You can ask for a new format to be supported by opening a new issue on https://github.com/lovasoa/dezoomify-rs/issues

**Comment by PandaBalls** [comment]
I tried this url:
https://artsandculture.google.com/asset/the-piazza-san-marco-in-venice-canaletto/ngEjiEaEofpMEg

**Comment by lovasoa** [comment]
The error says *operation timed out*. This is probably a problem with your network connection. I can download the image without issues with the latest dezoomify-rs.

**Comment by PandaBalls** [comment]
> The error says _operation timed out_. This is probably a problem with your network connection. I can download the image without issues with the latest dezoomify-rs.

I can download with web version or Chrome Extensions version. And I can use Dezoomify-rs for Generic url download ,but failed to download Google art images.( I can open the site by Chrome, Network connection looks fine.

**Comment by PandaBalls** [comment]
I find the problem of my network access, Mac terminal can not access my proxy..
I am trying to fix it.
