### ISSUE TITLE
 Barnes collection 

### ISSUE THREAD

**Issue by enriquemallen** [lovasoa/dezoomify-rs#94]
I followed the instructions to dezoomify the images in the Barnes collection, but I get an error message (see below)
![error](https://user-images.githubusercontent.com/76218730/102632226-697ec880-4114-11eb-9848-dac57b3a8b5f.jpg)

**Comment by lovasoa** [comment]
Trying to download https://collection.barnesfoundation.org/objects/5144/Woman-Seated-on-Striped-Floor/

**Comment by lovasoa** [comment]
I answered on the original issue, on https://github.com/lovasoa/dezoomify/issues/417#issuecomment-748219730
