### ISSUE TITLE
Batch download - Skip image reassembly when a tile fails

### ISSUE THREAD

**Issue by look2020** [lovasoa/dezoomify-rs#97]
Hi, I have been using dezoomify-rs to download lots of images in a batch mode (in Windows). One issue I have is dezoomify-rs will still create an image file even when one or more tiles for that image failed to download. I do add retry-delay in the script, but network issue do occur. I would prefer if dezoomify-rs could have a command-line option to skip creating the image file if a tile of the image cannot be downloaded. Thanks!

**Comment by lovasoa** [comment]
What is your envisioned use case? You want to download the missing tile later yourself, and use dezoomify-rs again locally to reassemble ?
dezoomify-rs can output the images in the iiif format, that is itself tiled. You can use that as a workaround not to have to redownload the whole image.
