### ISSUE TITLE
Issues with setting HTTP headers for Artstor

### ISSUE THREAD

**Issue by luchretius** [lovasoa/dezoomify-rs#98]
I am trying to download images from Artstor that follow the IIIF image protocol. As per instructions given here (https://github.com/lovasoa/dezoomify-rs/issues/8), I typed in the "x-jstor-access-session" header in the command line (so under the "Enter an URL [...]" prompt):

`-H "x-jstor-access-session: H4sIAAAAAAAAAIVTS0_bQB [...] k1c1U32bbA4v1drP9vp7Q5XZMXtqqvPv67eNErIf5z1dH5Y8J6PKfPf8Bvq6r2P0EAAA" "https://stor.artstor.org/iiif/2016/07/02/23/da4a1498-c797-4679-a12a-56649d29d019_deflate.tif/info.json"`

However, I keep on getting the ERROR message especially with the iiif line showing `os error 3`.

I am sure the .json URL is correct as it is auto-generated by my browser extension and I verified the location of the "default.jpg" images via Network. Am I setting the HTTP header incorrectly?

**Comment by lovasoa** [comment]
Yes, this is the right way of setting headers. What is the full command you type and the full response and error message you get ?

**Comment by luchretius** [comment]
Thanks for the reply!

Here are my steps: I first copied the 'x-jstor-access-session' value on my active Artstor page, and then the .json URL as identified by the extension. The full command was therefore:
`-H "x-jstor-access-session: H4sIAAAAAAAAAK2VTW_bOBCG7_0Vhs-ly--P3Nq0KBZY7C6c5LBYFMVwOExUqJYhyQGCIv99aUmOE8vBLoqeBM07Q758SA5_vFksllVaLi4WS8oCcjJWBsl1FAkEl8kH56PCLLRdvt0n45RdAbKO2vsKietR-jZJyQImRMVszoFpNJx5SJlZCFkGIVWZaKxopwoeUXqNSkWnIIJPHlSW6JQkIsxxzN7tpvQQvZCZFHNaR6Yz1wyUlwzQJBWDz8X5WAK7_m5f0rc7GgL3UI-DCCu4kF4FbaUZpGo7DG7kythVQbASZlozpO_VZi9mqLtxnK5rXgZ6fPm_n_k9Yt_tw_8sfpTYEbUzwaph7BKbDC2F4JxLXjwdFDooriwJYmQmx8y08ZpFbzOLQknluRdO8UNN_7Cloei3TddX_a6vms3TTE9iNRexpfTC7NFuYctdmBJHiLtxnEJw5e1KuELrqB89bNewuaWj8szBKN2UM3SUn2_XEHtcfCnfx7cn_AT30ionZwgLQW54OWSnCCl4nZ3QTCrNmZJgmLcAzAgHlrhFL-kMwlTdV2kH9ZzgX9R2zeaZ_WXb1DQBXN5cfVovF1_-G2182ELXfe3ge3eO713fby_evasbhPqu6fqLmm4BH7qHDZ7BvaZMbft_gI7WlvDaAS0gjTila_kpVScF14kjI1KGaZstA5M948pImT2ZjHlG9XPb7LZzoB-gq3DUzm8557MrI08NBfLcJUKWlSudAZ0pTaF0Bo7CBzAYOcxvyk8bsmGGyJ06sjkCd8WCjEEz7TSymLhgQWEQBFGVZvfrHBk3czRjVNqeRbSWFVayODJl07RNLGSLISZNKahf5Eg57aSaUVKudC01MyYxosrOsUSKijEYKBlmHQoSmig4MzO2ptuzHW6MD_fzteNkZ75OHSkCHaKNLDiRykMTCioukWlJ5SDJrEJ2P4lquoFdf3yMrDk-RjW8JuxeEaDv2-EuTwu9vBym_XRzsHJ1PQTer6-vrv9cH6KXY7RuNqnZfP39j48HYT3Wf_7wlPn3IbD3_-bxX-gKc8E8CAAA" "https://stor.artstor.org/iiif/2016/05/11/01/d0a9ae96-20fc-4b62-aeb1-9dc2cef954f9_deflate.tif/info.json"`

The error message was the following: 
![image](https://user-images.githubusercontent.com/68496843/104045692-d5fe5c00-51d6-11eb-89fc-5aced0d8bd9d.png)

**Comment by lovasoa** [comment]
It doesn't sound like a problem specific to artsor, but an issue accessing a path on your own computer. Can you download images from other sites, such as google arts and culture, with dezoomify-rs ? Can you relaunch your command adding `--dezoomer iiif --logging debug` and paste the full output here ?

**Comment by luchretius** [comment]
No problem. I have been using dezoomify-rs on other websites without difficulty; it seems that it is just with Artstor that my dezoomify-rs does not seem to work. I just logged into Arstor and this is my input:
`-H "x-jstor-access-session: H4sIAAAAAAAAAIWUy27bMBBF9_kKQ-vQ4UsimVVTNyi6KBo4ySIogmA4JGO1imWIVAAjyL9X1sPOq-1K0L0zw6szkp6OZrOsdNnsdJYFo4wquMqFDtJbYfPcOkaNzJWU2orseFeMY3UJSKJvHkv0dLQ2o-WtxkJZ4IoraTSzoEEo4zVYbpCbofrXWC2UZkxxRlBYSiQNnBgvHYGAHmVOrfZu6GjGDsUd8156hC6jkhSlEMI6LBjV6D0M1W07lucguBNME5TGEWmVJjYwIJ5qa7Bw0vliaIE2rXYtqWl9LzxCNQxh3WzOmZZM0aK3ys2QRc2NmrPuwvJxiHso1zsvQBWHMTHWr4WEr-93B58hpriTf86eOu2wF661Ggh32pgnY4xSymjHd3L89LiBIwZliBQYiDSi46kUEk4h71agtRQw9aTtxvdN39YxlalNZb3en7Q3y_cmNt69CnuIa7cbiPEuwkMcqweQ7TBsldLm9OSkqhGqVR3TaeXvAbdxu8ZD-f7opQ--aXxzsF7uqNeeZ7fd9fn4DTXJODNa0PwduVwx1elGvSVHvUIegiUFGiCSOyBa80CCdti9yRSCdR-Qc-Vj6Vqo3oO78E2s19dxnz9r6sqP3LLry_NlNrv9P9HpUYqPeOKqKWOqNyvfzKv206ZDet-Am0eIc8B5-_sDqrtEF92SDtYhc1Xfly8j_wP5kD2L6fCFUCq7P4bo9QreGNOnU7V_MSClpmcwrnKx6COdX0_4Lq964Wx5dXn1Yzmpi0FFeHB-fbf4_mUylkP_18_7yptJ2OU_ev4D1f3QJ_8EAAA" "https://stor.artstor.org/iiif/2017/01/03/21/2db1d3bc-1839-462e-883c-3b6eb88e568f_deflate.tif/info.json" --dezoomer iiif --logging debug`

The full output is the following:
`ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - custom: The 'custom' dezoomer cannot handle this URI
 - google_arts_and_culture: The 'google_arts_and_culture' dezoomer cannot handle this URI
 - zoomify: The 'zoomify' dezoomer cannot handle this URI
 - generic: The 'generic' dezoomer cannot handle this URI
 - pff: The 'pff' dezoomer cannot handle this URI
 - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
 - nypl: The 'nypl' dezoomer cannot handle this URI
 - iiif: Unable to download required data: Input/Output error: The system cannot find the path specified. (os error 3)
 - deepzoom: Unable to download required data: Input/Output error: The system cannot find the path specified. (os error 3)
 - krpano: Unable to download required data: Input/Output error: The system cannot find the path specified. (os error 3)

dezoomify-rs expects a zoomable image meta-information file URL. To find this URL, you can use the dezoomify browser extension, which you can download at
- https://lovasoa.github.io/dezoomify-extension/
If this doesn't help, then your image may be in a format that is not yet supported by dezoomify-rs.
You can ask for a new format to be supported by opening a new issue on https://github.com/lovasoa/dezoomify-rs/issues`

Unfortunately it does not seem to have changed with the new command.

**Comment by lovasoa** [comment]
the options go before the input url

**Comment by luchretius** [comment]
Thanks for your patience!! I tried again, changing the order of the options, but to no avail.. 

Input:
`Enter an URL or a path to a tiles.yaml file:
-H "x-jstor-access-session: H4sIAAAAAAAAAIVUy07cMBTd8xVR1mSwHT9ZdWaAqouqaIAFqhByrm0mbZhEsYM0Qvx785zwaqssrJxz7r0n58p5PoqiODdxdBrFzAmQqSOUtw-1VpGMKpFBxrmlGZD4uBPDqM41JN7WTzlYjAaqGikQkHJHlUECUwxOccVTIpngjhOpYFD_GtVLRld4mS7FGRYrwtlatVWUsQvJL1ZnSA3qelQr5CRre2MCkmacooyAlsZiRq00Rg7qphnlFDNNFKcJAiUTihROJKU8sVgzSgUnRuKhRDdh25WEurE98KSLoQnmGHX2CREY9VRe9c2FWCixwO2B2djEPOa7jnO68EMb78u3QIC3793gJUDwHfwzem6xeSdESpH2vVts9BNjjBDCSFA1MfawQgLghEpoCi6hKiWJEgISgjSzUktJUz3VhH1l-6JvOx_y0IS83B0mHcj8Iwm1NW_MznazfaW9v_f60Y_qIchmaLYNoTo9OSlK0MW29OG0sA8a9n6_g1l-GL2xzta1rWfq9Y567CW6a8-X43epUUywkiliH5JjAosWV-J9csgKIM5lCQelE0qMTqQkLnHSABEUaZeZT5Iz-VNuGl18DO7S1r7c3fiD_7guCzvmFt9cnW_i6O7_iU6fwj_LE7Z17kNZbW29KJovVRvpQ63Nwmu_0LBofn-Saufosl3STM2ei_Ihf235H5EP3mMf5hvCqWivLe3xQr8mxHx1iuYvhA6h7jMYV7le95bOb6b4rq6H38Xm-ur6x2ZC1wMK-tHY3f36-9lEbIb6r6uD8nYCOv9HL38ArVNR0_sEAAA" --dezoomer iiif --logging debug "https://stor.artstor.org/iiif/2017/01/03/21/2db1d3bc-1839-462e-883c-3b6eb88e568f_deflate.tif/info.json"`

The output remains the same:
`ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - custom: The 'custom' dezoomer cannot handle this URI
 - google_arts_and_culture: The 'google_arts_and_culture' dezoomer cannot handle this URI
 - zoomify: The 'zoomify' dezoomer cannot handle this URI
 - generic: The 'generic' dezoomer cannot handle this URI
 - pff: The 'pff' dezoomer cannot handle this URI
 - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
 - nypl: The 'nypl' dezoomer cannot handle this URI
 - iiif: Unable to download required data: Input/Output error: The system cannot find the path specified. (os error 3)
 - deepzoom: Unable to download required data: Input/Output error: The system cannot find the path specified. (os error 3)
 - krpano: Unable to download required data: Input/Output error: The system cannot find the path specified. (os error 3)

dezoomify-rs expects a zoomable image meta-information file URL. To find this URL, you can use the dezoomify browser extension, which you can download at
- https://lovasoa.github.io/dezoomify-extension/
If this doesn't help, then your image may be in a format that is not yet supported by dezoomify-rs.
You can ask for a new format to be supported by opening a new issue on https://github.com/lovasoa/dezoomify-rs/issues`

Am I doing wrong somewhere again?

**Comment by lovasoa** [comment]
aaaah!

**Comment by lovasoa** [comment]
You hadn't put the full program output so far. I see a "Enter an URL or a path to a tiles.yaml file:". You have to launch the program with the options! You are writing `-H` as if it were the file name itself. 

You have to launch dezoomify-rs from a terminal window, by typing its name and the options, not by double clicking on it from your file explorer.

**Comment by lovasoa** [comment]
Here is a video demonstrating how to launch dezoomify-rs on windows: https://youtu.be/tld7w32KqqI

**Comment by luchretius** [comment]
I see the problem now! Yes, I tried using commander in the method demonstrated and it worked. Thank you so much for your help and patience, keep up the good work! 👍 :)

**Comment by anaveem** [comment]
@luchretius Are you still able to download Artstor images the same way as you did in January?

I'm now getting 401 errors "HTTP status client error (401 Unauthorized)..." even when I use the access session cookie and I'm wondering whether other people get the same error. It's basically not authorizing me.

If you're reading this, could you try downloading this: [your library URL to Artstor]/#/asset/IBWA_DB_10313292287

My code for example:
`dezoomify-rs -H x-jstor-access-session:H4sIAAAAAAAAAL1WTW8bNxC951cIOocOP4ZfvrlGW-TQtJDtQ1AUwZAc2lusJWF3ZcAN_N_L1a5-rLWDIGit0-q9Ifn4ODPk13ez2bxK89n5bK6cJJec1wQeBFhPKUN2GmLUgmecv--D4xhdYWQtNQ9VJK4H6u-REtrLwH1iROQYZCmZ84YYcpXQkEkq5mAEM46IygiZyInsyRoBUQqRU_AkIKOJcojebMbw7AJ6A45Zlw0DCIEFboBpTEjcOXIYhiG46e76IV2zoS3wgPUwiTDSOdD9ViVsqWo9qFdw5uBMeHkm-Lgypvtq2bMZ63aYqG1Xz4EuPv_fL30RY9f28J-zrwU8eC24U8Y6sZ2-wPUeLz9hhTc7hkbGeBEha8scV54p4rl8RWTKKXQopBMOd2O6xzVtB31cpuqhShus9wvtuT-oaVfLm3KGO65Z1TSqdd9c_byYz_4amdhQeraPw07C4xrb9kuL9-04z-DyZljlruvW5x8-1KuI9d2q7c5rusX42D4u4yF8r2lBmZpmr-jkALfY015UOZLqvvqHfqnx9ijk6f2J19YqxSdC904LrgFOjXY8qCy1LNmLffYWtz1qzYKRYIwhTCRfMLrtqm7TVavl1OlqSn7DUFUqTquXvNxlptJnBl5w7-N6gctbOjBHEgbq6LR_zNshYI6v5zXXk6Q2_NRjKwWHxGPxWGkGplQx6uwYV1rK7EjnsUMcb-_XZrVZT939CdsqPuO-NzGUBSv3Vu_lKqu8VZMCRI-UgxOsNDvOgHPHEKxjBDZFL5xIJkw0L-j2xZQY8OPi-17Rfd5OJMtTsZ4ct4kiy8oGBtFqhtFJxqNwJZtj4Mj_f4OLVuMn2WAnrS0H5Laok8EDAwuRhcQF86r4ShhUuZXeRKy2E7ETZ7mQJkZjWHFYFrG6pC6YxHw20YcElLx6E7HcTBL3VKsiBB9MYN6KVFqZL1q5jAwklfOXpbVl-zZlBmKqtpSZ1JMykymooEMql7ko7VdAeTzkAMxZkAgEQIdb8z8ss7Gxtd3-baDAHN4GNb5GbF4hsOuabYsczbi83Cr6dLFTcnW9BS4W11fXvy926OWAFplLwvWqrtovv33akYthjpsrdsAuP4_YvN_Gu6d_AeHamfLSCQAA https://stor.artstor.org/iiif/2016/05/22/13/2f02f45d-b4db-404a-aefa-f223578197fc_deflate.tif/info.json`
