### ISSUE TITLE
KBR Bibliotek

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#99]
Hello,
I've been head-butting myself for several days with this link:
https://uurl.kbr.be/1558104
I can access the mosaic images:
https://viewerd.kbr.be/display/A/1/4/9/4/2/7/0/0000-00-00_00/zoomtiles/BE-KBR00_A-1494270_0000-00-00_00_0001/3-0- 0.jpg
But whenever I view them in a browser. If I do it with another browser, nothing.
I dont know. I suppose they have established some session or similar system.
Thank you very much for everything.
Greetings,

**Comment by lovasoa** [comment]
Did you try reproducing the HTTP headers sent by your browser in dezoomify-rs ? 

See https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages

**Comment by CharlyAlonso** [comment]
Hello again,
Yes, I have tried; but I fear that my knowledge does not allow me to advance further.
Nor am I clear that it is feasible.
I don't know, it's very weird. It is as if it only shows the "squares" that it has downloaded in the explorer's cache.
Anyway, I don't know ...
Anyway, thank you very much for everything.
Greetings,

**Comment by lovasoa** [comment]
You can have a look at this issue opened in dezoomify, which mentions dezoomify-rs: https://github.com/lovasoa/dezoomify/issues/120

**Comment by CharlyAlonso** [comment]
BIG, BIG lovasoa!

dezoomify-rs --header "Referer: https://viewerd.kbr.be/" "https://viewerd.kbr.be/display/A/1/4/9/4/2/7/0/0000 -00-00_00 / zoomtiles / BE-KBR00_A-1494270_0000-00-00_00_0001 / 3 - {{X}} - {{Y}}. Jpg "

It works perfectly!

Thank you, thank you, thank you very much ...

**Comment by lovasoa** [comment]
you're welcome 🙂
